### ISSUE TITLE
Installing beta release

### ISSUE THREAD

**Issue by Caerdon** [Wutname1/SpartanUI#10]
I can't seem to get a working beta release for BfA beta.  I have no other addons enabled.

I tried the easy path first (setting Spartan UI release type to Beta in Curse and installing it).  I get hundreds of errors on startup... some from Bartender, some from SpartanUI.  Here are two examples:
---------------------------
Message: AceLocale-3.0: SpartanUI: Missing entry for 'Frames/DisplayOpts'
Time: Sat Jun 23 10:09:17 2018
Count: 1
Stack: AceLocale-3.0: SpartanUI: Missing entry for 'Frames/DisplayOpts'
...ace\AddOns\SpartanUI_PartyFrames\scripts\Options.lua:23: in function <...ace\AddOns\SpartanUI_PartyFrames\scripts\Options.lua:22>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>
---------------------------
Message: Interface\AddOns\Bartender4\Bartender4.lua:155: attempt to index global 'MainMenuExpBar' (a nil value)
Time: Sat Jun 23 10:09:16 2018
Count: 1
Stack: Interface\AddOns\Bartender4\Bartender4.lua:155: attempt to index global 'MainMenuExpBar' (a nil value)
Interface\AddOns\Bartender4\Bartender4.lua:155: in function `HideBlizzard'
Interface\AddOns\Bartender4\Bartender4.lua:61: in function <Interface\AddOns\Bartender4\Bartender4.lua:45>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>
---------------------------

I tried getting tricky and starting to disable various optional parts of Spartan, installing libraries separate, etc... but decided I'd just check in here after a bunch of monkeying around to see if this is expected, or if there are just some extra dependencies or instructions for getting beta going at this point (or maybe it's just not working at the moment?)

Thanks!

**Comment by Caerdon** [comment]
Looks like it might be the Classic theme that causes a lot of the errors.  Switching to the Fel theme, I was able to eventually get it (mostly) working with only a few errors.

**Comment by Wutname1** [comment]
> Message: AceLocale-3.0: SpartanUI: Missing entry for 'Frames/DisplayOpts'

This should not be an issue in Beta 5 or 6. 

> Message: Interface\AddOns\Bartender4\Bartender4.lua:155: attempt to index global 'MainMenuExpBar' (a nil value)

Update bartender4 to the latest alpha

**Comment by Caerdon** [comment]
I have beta 6 installed and the latest Bartender alpha now, and I get the following error immediately on launch (I get around 79 total errors all similar to this but for different entries):

Message: AceLocale-3.0: SpartanUI: Missing entry for 'Frames/DisplayOpts'
Time: Sun Jun 24 14:52:15 2018
Count: 1
Stack: AceLocale-3.0: SpartanUI: Missing entry for 'Frames/DisplayOpts'
...ace\AddOns\SpartanUI_PartyFrames\scripts\Options.lua:23: in function <...ace\AddOns\SpartanUI_PartyFrames\scripts\Options.lua:22>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by Wutname1** [comment]
Ok, I am able to replicate. something did not build right. Will figure it out and have a beta7 up soon.

**Comment by Caerdon** [comment]
Thanks!  Beta 7 cleared up the launch issue when I'm using Fel.  When I try and switch it to Classic style, I get an error, and then when I do a reload UI, I get a ton of the following:

Message: AceLocale-3.0: SpartanUI: Missing entry for 'Frames/DisplayOptsPartyDesc'
Time: Sun Jun 24 14:52:15 2018
Count: 1
Stack: AceLocale-3.0: SpartanUI: Missing entry for 'Frames/DisplayOptsPartyDesc'
...ace\AddOns\SpartanUI_PartyFrames\scripts\Options.lua:24: in function <...ace\AddOns\SpartanUI_PartyFrames\scripts\Options.lua:22>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:529: in function `InitializeAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:644: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>

Locals: <none>

**Comment by Wutname1** [comment]
That line doesn't exist in beta7, make sure all files updated.

**Comment by Caerdon** [comment]
Hmm... I'm pretty sure I deleted the Spartan UI addon folders, downloaded beta 7 and placed them there, and started things up.  I'll go back through my steps one more time to make sure.

Do I need to also clear out my SavedVariables?

**Comment by Caerdon** [comment]
I saw you posted a beta 8.  I tried that one out, and all of my errors appear to have cleared up!  Thanks!  🥇
