### ISSUE TITLE
Hey if got a Problem with my monk and Spartan Ui

### ISSUE THREAD

**Issue by kokosnuss77** [Wutname1/SpartanUI#102]
This is the error. This is only on my Monk i play.
Message: ...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:128: attempt to index field '?' (a nil value)
Time: Fri Sep 14 20:50:15 2018
Count: 31
Stack: ...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:128: attempt to index field '?' (a nil value)

Locals:

**Comment by dgrenner** [comment]
I had the same issue on my monk.

A workaround to get rid of the error is to change in the file classpower.lua, from line 127 to:
```
			if(i > numActive) then
				if (element[i] ~= nil) then
					element[i]:Hide()
					element[i]:SetValue(0)
				end
			else
				if (element[i] ~= nil) then
					element[i]:Show()
					element[i]:SetValue(cur - i + 1)
				end
			end
```
I had a similar issue later, and had to do the same change at line 144 in the same file.

**Comment by Wutname1** [comment]
#112 is likely the same thing as this. If the error is still present in the new update let me know.
