### ISSUE TITLE
No longer able to move

### ISSUE THREAD

**Issue by Baelea** [Wutname1/SpartanUI#103]
with the drop of the new version (5.0 i believe) all of my ui items locations have been reset (mainly player, target, and minimap) to default locations and they cannot be moved whatsoever. this makes the UI completely useless to me. items need to be able to be moved this is a requirement for me to even consider this UI, i wish i would have not downloaded the update. please help i cannot even play correctly right now.

**Comment by Baelea** [comment]
ok i reverted to an older version, but we gadda get the moving thing figured out that is crucial please

**Comment by Wutname1** [comment]
Did you update with the game open?

**Comment by Baelea** [comment]
no completely closed wow/blizzard app

**Comment by Baelea** [comment]
is nobody else having this issue? you guys still able to move the frames around holding the alt key? /suimove still disabled

**Comment by Whatsatotem** [comment]
mines workin like it always has

**Comment by Baelea** [comment]
well i reverted to a 4.6ish version and it worked fine even put my items back in the correct place automatically. tried 5.0 again and still had the same issues. just downloaded 5.02 and whatever issue i had is now gone. everything is working fine, everything is in the correct place and moveable once again.
