### ISSUE TITLE
New error on logging onto a character - Unit-FrameSpawn.lua

### ISSUE THREAD

**Issue by Mercian** [Wutname1/SpartanUI#107]
1x ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:203: Usage: SUI_focusFrame:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[C]: in function `SetPoint'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:203: in function `AddMover'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:312: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:300>
[C]: ?
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:540: in function `EnableAddon'
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1192: in function <FrameXML\UIParent.lua:1090>

**Comment by Wutname1** [comment]
looks like you moved your frames and it got corrupted somehow. `/suihelp > Reset Movable Frames`

**Comment by Mercian** [comment]
Thanks, this helped!
