### ISSUE TITLE
Auto Quest Accept / Auto quest reward , On even when I have them off

### ISSUE THREAD

**Issue by redbeardtek** [Wutname1/SpartanUI#111]
Deleted spartanUI , reinstalled. Same issue. It auto accepts quests and auto turn ins, as well as auto selects quest reward , even tho all options are off. Any help would be great.

Thank you

**Comment by Wutname1** [comment]
![image](https://user-images.githubusercontent.com/704321/47755070-f3385700-dc6a-11e8-87b6-ded3ffcd011c.png)

Known issue, will hopefully be fixed in next update. to turn off a module completely visit this screen
