### ISSUE TITLE
Bug Bag error :P 

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#113]
![image](https://user-images.githubusercontent.com/41389109/45859028-dcc2e580-bd25-11e8-8ccd-88eb9adf5873.png)

**Comment by Whatsatotem** [comment]
and another one that is too long to screenshot:

1x [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'oUF_Spartan_RaidFrames_ClassicRaidUnitButton25:SetSize()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetSize'
...\SpartanUI_RaidFrames\scripts\FrameStyle_Classic.lua:53: in function <...\SpartanUI_RaidFrames\scripts\FrameStyle_Classic.lua:42>
...\SpartanUI_RaidFrames\scripts\FrameStyle_Classic.lua:237: in function `styleFunc'
SpartanUI\libs\oUF\ouf.lua:348: in function <SpartanUI\libs\oUF\ouf.lua:265>
(tail call): ?
(tail call): ?
FrameXML\RestrictedFrames.lua:758: in function <FrameXML\RestrictedFrames.lua:750>
[C]: ?
[C]: ?
FrameXML\RestrictedFrames.lua:777: in function `CallMethod'
[string "		local header = self:GetParent()..."]:51: in function <[string "		local header = self:GetParent()..."]:1>
(tail call): ?
[C]: ?
FrameXML\RestrictedExecution.lua:484: in function <FrameXML\RestrictedExecution.lua:447>
FrameXML\SecureGroupHeaders.lua:116: in function <FrameXML\SecureGroupHeaders.lua:110>
FrameXML\SecureGroupHeaders.lua:166: in function <FrameXML\SecureGroupHeaders.lua:123>
FrameXML\SecureGroupHeaders.lua:488: in function `SecureGroupHeader_Update'
FrameXML\SecureGroupHeaders.lua:62: in function <FrameXML\SecureGroupHeaders.lua:60>

Locals:
InCombatSkipped

**Comment by Wutname1** [comment]
Ya, these are some of the in combat errors and plagued SUI for a long time. 5.1 is supposed to Target this stuff.
