### ISSUE TITLE
Transparent player frame colours

### ISSUE THREAD

**Issue by Dogs1005** [Wutname1/SpartanUI#116]
Hi there,
What's happened to the player frame colour in transparent mode. there were plans to implement this but it doesn't seem to have materialized.
Someone on here has suggested the code that needs to be made to the style.lua code and before the update today, it worked a treat. But with the update it removed my modifications and now the suggested code doesn't work anymore.
Is there any chance to add this in future spartui updates as the default blue doesn't match my colour scheme.
The code in question is in the \World of Warcraft\Interface\AddOns\SpartanUI_Style_Transparent\style.lua

			PlayerColor = {
				name = L['PlayerFramesColor'],
				type = 'color',
				hasAlpha = true,
				order = 1,
				width = 'full',
				get = function(info)
					return unpack(SUI.DB.Styles.Transparent.Color.PlayerFrames)
				end,
				set = function(info, r, b, g, a)
					SUI.DB.Styles.Transparent.Color.PlayerFrames = {r, b, g, a}
					module:SetColor()
				end
			}

**Comment by Wutname1** [comment]
Sorry for the delay in responding ![image](https://user-images.githubusercontent.com/704321/47755353-ef590480-dc6b-11e8-8ce0-d2c83b6c09cf.png)
