### ISSUE TITLE
Auto hand in and auto quest pickup keep coming back on

### ISSUE THREAD

**Issue by Faithwhite** [Wutname1/SpartanUI#118]
Hi, My auto quest pickup, hand in and choose reward keep reticking themselves each time i log in even when I refresh my browser which is driving me nuts I keep having to open the ui and unticking them which kinda usurps the feature being effortless. Otherwise I love the programming ty for any help in advance

**Comment by Wutname1** [comment]
If you still have issues after the next patch let me know.
