### ISSUE TITLE
signs ????????? (Part 2)

### ISSUE THREAD

**Issue by Hubbotu** [Wutname1/SpartanUI#12]
Hey. There is an error. https://github.com/Wutname1/oUF_AuraBars (Correctly: ARIAL**N**.TTF). 

The problem remained.
Words from two phrases (Example: Torment the Weak) The first word consists of ????

https://imgur.com/a/z0EuWqD
Screenshot
1. All perfectly.
2. Text does not fit
3.Text does not fit

**Comment by Wutname1** [comment]
So only the **N**arrow version of Arial works properly?

(The N in the filename stands for Narrow variation of the font)

**Comment by Wutname1** [comment]
Updated https://github.com/Wutname1/oUF_AuraBars
