### ISSUE TITLE
error when leaving vehicle bar

### ISSUE THREAD

**Issue by Mercian** [Wutname1/SpartanUI#121]
I did this shooting quest for the seeker. When I finished I got this error:

6x [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' hat versucht die geschützte Funktion 'SUI_FramesAnchor:SetParent()' aufzurufen.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetParent'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:55: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:53>
[C]: ?
[C]: ?
[C]: in function `Hide'
FrameXML\SecureStateDriver.lua:103: in function <FrameXML\SecureStateDriver.lua:95>
FrameXML\SecureStateDriver.lua:127: in function <FrameXML\SecureStateDriver.lua:119>

Locals:
InCombatSkipped

**Comment by Wutname1** [comment]
Known issue unfortunately. Hope to have it resolved in SUI 5.1 unitframe re-write.
