### ISSUE TITLE
Hunter Pet bar returns to original position after moving

### ISSUE THREAD

**Issue by Madnezz01** [Wutname1/SpartanUI#122]
I'm using the Minimal Style setup. When I move the hunter pet bar it returns to the original position. I have tried resetting and moving via the bartender frae co-ordinates, but it allways jumps back to the top of the screen after i move the mouse.

**Comment by itegumo** [comment]
This issue also affect the menu bar when using the Minimal Style. I keep my menu bar on the right side, middle-vertical position, and it moves it to the top-right corner. Even when I move it back, a few seconds later, right back at the top right. Pet bar always moves to the top-center of the screen, no matter where I move it to. I have only noticed this issue when using Minimal Style.
