### ISSUE TITLE
Arena issue: attempt to call method 'ForceUpdateTags' (a nil value)

### ISSUE THREAD

**Issue by Sabran** [Wutname1/SpartanUI#124]
I'm getting the following error when going into an arena:

`Message: Interface\AddOns\SpartanUI\libs\oUF\arena.lua:127: attempt to call method 'ForceUpdateTags' (a nil value)
Time: Sat Oct  6 21:48:44 2018
Count: 3
Stack: Interface\AddOns\SpartanUI\libs\oUF\arena.lua:127: attempt to call method 'ForceUpdateTags' (a nil value)
Interface\AddOns\SpartanUI\libs\oUF\arena.lua:127: in function <Interface\AddOns\SpartanUI\libs\oUF\arena.lua:79>
[C]: ?

Locals: self = SUI_Arena3 {
 0 = <userdata>
 TextUpdate = <function> defined @Interface\AddOns\SpartanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:97
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:208
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:314
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:221
 ARENA_PREP_OPPONENT_SPECIALIZATIONS = <table> {
 }
 UNIT_HEALTH_FREQUENT = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\health.lua:166
 BossGraphic = <unnamed> {
 }
 __elements = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\power.lua:236
 Castbar = <unnamed> {
 }
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\healthprediction.lua:200
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:243
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\threatindicator.lua:90
 UNIT_HEALTH = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\healthprediction.lua:200
 style = "SUI_PlayerFrames_Classic"
 artwork = <unnamed> {
 }
 UNIT_EXITED_VEHICLE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:46
 SmoothBar = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_Smooth.lua:17
 UNIT_CONNECTION = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:408
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:378
 UNIT_ABSORB_AMOUNT_CHANGED = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\healthprediction.lua:200
 UNIT_HEAL_PREDICTION = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\healthprediction.lua:200
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:193
 RaidTargetIndicator = <unnamed> {
 }
 LevelSkull = <unnamed> {
 }
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:265
 Power = <unnamed> {
 }
 UNIT_SPELLCAST_START = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:107
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\power.lua:236
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\raidtargetindicator.lua:62
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\castbar.lua:292
 ARENA_OPPONENT_UPDATE = <table> {
 }
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\power.lua:236
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\power.lua:236
 UNIT_PET = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:248
 UNIT_THREAT_LIST_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\elements\threatindicator.lua:90
 HealthPrediction = <table> {
 }
 id = "3"
 UNIT_EXITING_VEHICLE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:46
 UNIT_FACTION = <table> {
 }
 ThreatIndicator = <unnamed> {
 }
 ColorUpdate = <function> defined @Interface\AddOns\SpartanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:138
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:46
 Name = `

**Comment by KKempoo** [comment]
I'm getting a similar one to                                                                                                                                                         3x SpartanUI\libs\oUF\arena-Arena.lua:127: attempt to call method 'ForceUpdateTags' (a nil value)
SpartanUI\libs\oUF\arena-Arena.lua:127: in function <SpartanUI\libs\oUF\arena.lua:79>
[C]: ?

Locals:
self = SUI_Arena1 {
 0 = <userdata>
 TextUpdate = <function> defined @SpartanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:97
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @SpartanUI\libs\oUF\ouf.lua:208
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:314
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:221
 ARENA_PREP_OPPONENT_SPECIALIZATIONS = <table> {
 }
 UNIT_HEALTH_FREQUENT = <function> defined @SpartanUI\libs\oUF\elements\health.lua:166
 BossGraphic = <unnamed> {
 }
 __elements = <table> {
 }
 UNIT_POWER_FREQUENT = <function> defined @SpartanUI\libs\oUF\elements\power.lua:236
 Castbar = <unnamed> {
 }
 UNIT_HEAL_ABSORB_AMOUNT_CHANGED = <function> defined @SpartanUI\libs\oUF\elements\healthprediction.lua:200
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:243
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @SpartanUI\libs\oUF\elements\threatindicator.lua:90
 UNIT_HEALTH = <function> defined @SpartanUI\libs\oUF\elements\healthprediction.lua:200
 style = "SUI_PlayerFrames_Classic"
 artwork = <unnamed> {
 }
 mover = <unnamed> {
 }
 UNIT_EXITED_VEHICLE = <function> defined @SpartanUI\libs\oUF\ouf.lua:46
 SmoothBar = <function> defined @SpartanUI\libs\oUF_Plugins\oUF_Smooth.lua:17
 UNIT_CONNECTION = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:408
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:378
 UNIT_ABSORB_AMOUNT_CHANGED = <function> defined @SpartanUI\libs\oUF\elements\healthprediction.lua:200
 UNIT_HEAL_PREDICTION = <function> defined @SpartanUI\libs\oUF\elements\healthprediction.lua:200
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:193
 RaidTargetIndicator = <unnamed> {
 }
 LevelSkull = <unnamed> {
 }
 UNIT_SPELLCAST_DELAYED = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:265
 Power = <unnamed> {
 }
 UNIT_SPELLCAST_START = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:107
 UNIT_POWER_BAR_SHOW = <function> defined @SpartanUI\libs\oUF\elements\power.lua:236
 RAID_TARGET_UPDATE = <function> defined @SpartanUI\libs\oUF\elements\raidtargetindicator.lua:62
 UNIT_SPELLCAST_STOP = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:292
 ARENA_OPPONENT_UPDATE = <table> {
 }
 UNIT_MAXPOWER = <function> defined @SpartanUI\libs\oUF\elements\power.lua:236
 UNIT_DISPLAYPOWER = <function> defined @SpartanUI\libs\oUF\elements\power.lua:236
 UNIT_PET = <function> defined @SpartanUI\libs\oUF\ouf.lua:248
 UNIT_THREAT_LIST_UPDATE = <function> defined @SpartanUI\libs\oUF\elements\threatindicator.lua:90
 HealthPrediction = <table> {
 }
 id = "1"
 UNIT_EXITING_VEHICLE = <function> defined @SpartanUI\libs\oUF\ouf.lua:46
 UNIT_FACTION = <table> {
 }
 ThreatIndicator = <unnamed> {
 }
 ColorUpdate = <function> defined @SpartanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:138
 UNIT_ENTERED_VEHICLE = <function> defined @SpartanUI\libs\oUF\ouf.lua:46
 Name = <unnamed> {
 }
 unit = "arena1"
 Health = <unnamed> {
 }
 UNIT_POWER_BAR_HIDE = <function> defined @SpartanUI\libs\oUF\elements\power.lua:236
 UNIT_MAXHEALTH = <table> {
 }
 UNIT_SPELLCAST_FAILED = <function> defined @SpartanUI\libs\oUF\elements\castbar.lua:165
}
event = "ARENA_PREP_OPPONENT_SPECIALIZATIONS"
id = 1
specID = 253
(*temporary) = nil
(*temporary) = SUI_Arena1 {
 0 = <userdata>
 TextUpdate = <function> defined @Interfac

**Comment by Wutname1** [comment]
Issue with oUF library, oUF was updated in the 5.0.13

If the issue returns please reopen.
