### ISSUE TITLE
list of bugs that have popped up recently

### ISSUE THREAD

**Issue by cutdachez** [Wutname1/SpartanUI#125]
May not be sui issue. Just checking,

3x AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: Attempt to register unknown event "CHAT_MSG_BN_CONVERSATION"
[C]: in function `RegisterEvent'
AskMrRobot\Libs\AceEvent-3.0\AceEvent-3.0-4.lua:33: in function `OnUsed'
...atz\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:168: in function `RegisterEvent'
...rfaceWhisperInvite\WhisperInviteAdvanced-2.1.7.lua:438: in function `RegisterChannel'
...rfaceWhisperInvite\WhisperInviteAdvanced-2.1.7.lua:428: in function `RegisterAllChannels'
...rfaceWhisperInvite\WhisperInviteAdvanced-2.1.7.lua:133: in function <...rfaceWhisperInvite\WhisperInviteAdvanced.lua:129>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ddOns\ArekosGratz\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...ddOns\ArekosGratz\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...ddOns\ArekosGratz\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
...
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ddOns\ArekosGratz\libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...ddOns\ArekosGratz\libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...ddOns\ArekosGratz\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1192: in function <FrameXML\UIParent.lua:1090>

**Comment by Wutname1** [comment]
This would be a issue with AskMrRobot
