### ISSUE TITLE
New bug 

### ISSUE THREAD

**Issue by lectrcsprx** [Wutname1/SpartanUI#128]
Message: [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'SUI_FramesAnchor:SetParent()'.
Time: Sun Oct 14 12:53:49 2018
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'SUI_FramesAnchor:SetParent()'.

Locals: <none

**Comment by Wutname1** [comment]
Known issue due to how SUI spawns frames, only happen if you are in combat when someone joins the party/raid.  This is the main issue targeted by the unitframe re-write that will be in SUI 5.1.
