### ISSUE TITLE
UI not usable...

### ISSUE THREAD

**Issue by Darkrenzo** [Wutname1/SpartanUI#13]
Just did the update and my UI is no longer usable. When I log in it looks good for about 5 seconds and then the minimap goes blank and I cant clink on any icons.
Then when I do a /reload the whole UI dissapears and I am left with just the bartender boxes with icons that I can still not click. I will add images to show what I mean.
![wowscrnshot_062518_203910](https://user-images.githubusercontent.com/40565431/41846142-20cd82d2-78b9-11e8-8d06-148d563b4126.jpg)
![wowscrnshot_062518_203930](https://user-images.githubusercontent.com/40565431/41846143-21047058-78b9-11e8-9e11-4893dfe3f206.jpg)

**Comment by Darkrenzo** [comment]
Would also like to add that if I try to reload for a second time, the game become extremely choppy.

**Comment by Darkrenzo** [comment]
So after doing some testing of my addons I have found that Spartan UI is no longer working with the MoveAnything addon.
Now since it has not bee updated since Jan 18 and Spartan UI was updated (for me) today, I can only assume that there is something in Spartan's code that makes them clash.

**Comment by Wutname1** [comment]
What version is listed on /shihelp
