### ISSUE TITLE
Player, Pet, and NPC/Mob Frames Missing

### ISSUE THREAD

**Issue by Rhallan** [Wutname1/SpartanUI#130]
I just installed the latest update and my player image and health bar is gone, When I select a mob I get a white and grey bar for the mob - no name, or it's health.

Here is the error I got, not sure if it is helpful or not - 

Date: 2018-10-30 00:41:55
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\SpartanUI\libs\oUF\ouf.lua line 348:
   Attempted to use invalid tag [SUI_ColorClass].
Debug:
   [C]: error()
   ...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:710: Tag()
   SpartanUI\components\Nameplates.lua:114: styleFunc()
   SpartanUI\libs\oUF\ouf.lua:348:
      SpartanUI\libs\oUF\ouf.lua:265
   (tail call): ?
   SpartanUI\libs\oUF\ouf.lua:787:
      SpartanUI\libs\oUF\ouf.lua:758
Locals:
(*temporary) = "Attempted to use invalid tag [SUI_ColorClass]."

AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  ACP, vr259 
  BadBoy, vv8.0.13
  BagBrother, v
  Bagnon, v8.0.7
  Bartender4, v4.8.1
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BugSack, vv8.0.2
  BuyEmAll, v3.5.0
  DBMCore, v@project-version@
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GatherMate2, v1.42.1
  InFlightLoad, v8.0.005
  Informant, v8.0.6159 (SwimmingSeadragon)
  NPCScan, v8.0.1.13
  Pawn, v2.2.31
  Prat30, vr1178      
  Prat30Libraries, v
  Skillet, v4.06
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  SpartanUI, v5.1-Alpha-1
  SpartanUIArtwork, v5.1-Alpha-1
  SpartanUIFilmEffects, v5.1-Alpha-1
  SpartanUIPartyFrames, v5.1-Alpha-1
  SpartanUIPlayerFrames, v5.1-Alpha-1
  SpartanUIRaidFrames, v5.1-Alpha-1
  SpartanUISpinCam, v5.1-Alpha-1
  SpartanUIStyleFel, v5.1-Alpha-1
  SpartanUIStyleMinimal, v5.1-Alpha-1
  SpartanUIStyleTransparent, v5.1-Alpha-1
  SpartanUIStyleWar, v5.1-Alpha-1
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20181027
  Titan, v5.14.12.80000
  TitanMicroMenu, v1.0.2
  TitanBag, v5.14.12.80000
  TitanClock, v5.14.12.80000
  TitanCurrenciesMulti, v5.29.1
  TitanGold, v5.14.12.80000
  TitanGuild, v8.0.0.0
  TitanLocation, v5.14.12.80000
  TitanLootType, v5.14.12.80000
  TitanMail, v7.35
  TitanPerformance, v5.14.12.80000
  TitanProfessionsMulti, v6.11
  TitanRepair, v5.14.12.80000
  TitanReputations, vv1.17
  TitanSocial, v8.0.1
  TitanVolume, v5.14.12.80000
  TitanXP, v5.14.12.80000
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=5f1)

**Comment by Rhallan** [comment]
Here is another Error Code -

Date: 2018-10-30 02:57:39
ID: 1
Error occured in: Global
Count: 1
Message: ...partanUI_PlayerFrames\scripts\FrameStyle_Classic.lua line 1882:
   Attempted to use invalid tag [curhpdynamic].
Debug:
   [C]: error()
   ...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:710: Tag()
   ...partanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:297:
      ...partanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:237
   ...partanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:1882: styleFunc()
   SpartanUI\libs\oUF\ouf.lua:348:
      SpartanUI\libs\oUF\ouf.lua:265
   (tail call): ?
   SpartanUI\libs\oUF\ouf.lua:707: Spawn()
   ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:18: SUI_PlayerFrames_Classic()
   ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:305:
      ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:300
   (tail call): ?
   [C]: ?
   [string "safecall Dispatcher[1]"]:9:
      [string "safecall Dispatcher[1]"]:5
   (tail call): ?
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:558: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:571: EnableAddon()
   ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:651:
      ...xternal\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:636
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:446: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:565: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1192:
      ..\FrameXML\UIParent.lua:1090
Locals:
None
AddOns:
  Swatter, v8.0.6162 (SwimmingSeadragon)
  ACP, vr259 
  BadBoy, vv8.0.13
  BagBrother, v
  Bagnon, v8.0.7
  Bartender4, v4.8.1
  BeanCounter, v8.0.6157 (SwimmingSeadragon)
  BugSack, vv8.0.2
  BuyEmAll, v3.5.0
  DBMCore, v@project-version@
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  GatherMate2, v1.42.1
  InFlightLoad, v8.0.005
  NPCScan, v8.0.1.13
  Pawn, v2.2.31
  Prat30, vr1178      
  Prat30Libraries, v
  Skillet, v4.06
  SlideBar, v8.0.6160 (SwimmingSeadragon)
  SpartanUI, v5.1-Alpha-1
  SpartanUIArtwork, v5.1-Alpha-1
  SpartanUIFilmEffects, v5.1-Alpha-1
  SpartanUIPartyFrames, v5.1-Alpha-1
  SpartanUIPlayerFrames, v5.1-Alpha-1
  SpartanUIRaidFrames, v5.1-Alpha-1
  SpartanUISpinCam, v5.1-Alpha-1
  SpartanUIStyleFel, v5.1-Alpha-1
  SpartanUIStyleMinimal, v5.1-Alpha-1
  SpartanUIStyleTransparent, v5.1-Alpha-1
  SpartanUIStyleWar, v5.1-Alpha-1
  Stubby, v8.0.6161 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20181027
  Titan, v5.14.12.80000
  TitanMicroMenu, v1.0.2
  TitanBag, v5.14.12.80000
  TitanClock, v5.14.12.80000
  TitanCurrenciesMulti, v5.29.1
  TitanGold, v5.14.12.80000
  TitanGuild, v8.0.0.0
  TitanLocation, v5.14.12.80000
  TitanLootType, v5.14.12.80000
  TitanMail, v7.35
  TitanPerformance, v5.14.12.80000
  TitanProfessionsMulti, v6.11
  TitanRepair, v5.14.12.80000
  TitanReputations, vv1.17
  TitanSocial, v8.0.1
  TitanVolume, v5.14.12.80000
  TitanXP, v5.14.12.80000
  ZygorGuidesViewer, v7.0
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=5c6)

**Comment by Wutname1** [comment]
Roll back off of the alpha releases.
