### ISSUE TITLE
Rep / experience Status bars refuse to show in 5.0.6

### ISSUE THREAD

**Issue by marblewood** [Wutname1/SpartanUI#133]
No matter what I do, they're invisible. They briefly pop up for a fraction of a second if I modify any of their parameters.

**Comment by Xatrith** [comment]
Same here

**Comment by Deathmettal** [comment]
Got the same problems. I now work withe the Bartender Status Bars till it's repaired.

**Comment by Wutname1** [comment]
This was fixed in #132 and released as 5.0.7 this morning.
