### ISSUE TITLE
Vehicle UI not appearing.

### ISSUE THREAD

**Issue by Sappermentti** [Wutname1/SpartanUI#135]
So as of the latest addon patch (5.0.7) I've noticed that the vehicle UI is not activating for me. Worked just fine before it as i recall.

Ofcourse i could just use the default blizzard vehicle UI but honestly, i'd rather not. I've just grown so accustomed to Spartan over the years.
![nayttokuva 51](https://user-images.githubusercontent.com/44980100/48366834-a8c9c800-e6b7-11e8-9c81-d181b1532466.png)

**Comment by Wutname1** [comment]
Try to toggle the use blizzard vehicle UI option

**Comment by Sappermentti** [comment]
I have. Didn't help. 
However, switching from the classic skin to something else ('War' in my case) seems to be a kind-of-sot-of fix. Though i still get the bug if i switch back to classic.

**Comment by Sappermentti** [comment]
Update; So i've tried deleting my WTF folder and reinstalling SpartanUI & Bartender 4. Didn't do nothing.

I've also gone ahead and tried turning off different modules of SUI just to see which one's causing it. Seems to be the artwork module. 

Tried using BugGrabber to see if there was any error messages. This came up but only after leaving the vehicle, so i have no idea if it's even relevant or not:

1x [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'SUI_FramesAnchor:SetParent()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetParent'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:65: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:63>
[C]: ?
[C]: ?
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:100: in function <FrameXML\SecureStateDriver.lua:95>
FrameXML\SecureStateDriver.lua:127: in function <FrameXML\SecureStateDriver.lua:119>

Locals:
InCombatSkipped

**Comment by raineday** [comment]
I get the same problem. when looking at the changes made i believe it has something to do with Fixes #79 Status bars not hiding in pet battles

**Comment by raineday** [comment]
so my finding for the vehicleui not working is in the World of Warcraft\interface\addons\SpartanUI_Artwork\statusbar.lua

current release shows this 

`-- Hide with SpartanUI
			RegisterStateDriver(SpartanUI, 'visibility', '[petbattle][overridebar][vehicleui] hide; show')
`

in order to get the vehicleui without blizzards vehicleui works with this
`-- Hide with SpartanUI
			RegisterStateDriver(SpartanUI, 'visibility', '[petbattle][overridebar] hide; show')
`

but i believe the request for #79 was to have the status-plate-exp and status-plate-rep hide when the pet battles are active.

I guess this is a short term fix until a proper fix.
