### ISSUE TITLE
Conflict between SpartanUI and moveanything.

### ISSUE THREAD

**Issue by Xatrith** [Wutname1/SpartanUI#136]
Hello,

My buff/debuff on my character and my target are located above the respective portraits. And when there is more than 5 or 6 debuffs, they hide an other important bar : the one that appears when you fight against the last boss of tol dagor making it impossible to see. And somehow if i try to move it with an other add on like "move anything" the bar seems locked by spartan ui (tried to deactivate it while bartender is still active, works fine).

Can you look into it please ?

Xatrith

**Comment by Sappermentti** [comment]
This is just a hunch, but have you tried holding down Alt and dragging the power bar someplace else? Works with party frames, i'm wondering if this'll work too.

**Comment by Xatrith** [comment]
Seems like it's not working :
![image](https://user-images.githubusercontent.com/37808408/49691627-13e7ac80-fb47-11e8-8e0c-a6440d5e846f.png)

And it's the right bar because if i hide it, it disappear correctly : 
![image](https://user-images.githubusercontent.com/37808408/49691631-2f52b780-fb47-11e8-86be-c078fff2c1df.png)

Somehow, the other add on say that spartan ui is somehow implicated : 
![image](https://user-images.githubusercontent.com/37808408/49691652-85bff600-fb47-11e8-87cb-6fd90ca9d5f9.png)
