### ISSUE TITLE
SpartanUI - vehicle bar is not displayed

### ISSUE THREAD

**Issue by Lujuya** [Wutname1/SpartanUI#139]
SpartanUi - since 4 updates, the AddOn own vehicle bar is no longer displayed. But not even the game. But as soon as I get into a vehicle there is nothing there, no attacks or anything else. you only see the surroundings. Is it because of the Bartender4 has not yet a new update?

**Comment by Wutname1** [comment]
What skin are you using?

**Comment by Lujuya** [comment]
Sorry, I do not quite understand. I use SpartanUI and Bartender4. It is set that the Blizzard UI should not be used.
 

Gesendet: Dienstag, 11. Dezember 2018 um 07:34 Uhr
Von: wutname1 <notifications@github.com>
An: Wutname1/SpartanUI <SpartanUI@noreply.github.com>
Cc: Lujuya <spielmitspass@web.de>, Author <author@noreply.github.com>
Betreff: Re: [Wutname1/SpartanUI] SpartanUI - vehicle bar is not displayed (#139)


What skin are you using?

**Comment by Wutname1** [comment]
What spartanui skin/style are you using?

**Comment by Lujuya** [comment]
Ah ok, is classic
Am 11.12.18, 07:34, wutname1 <notifications@github.com> schrieb:
What skin are you using?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Wutname1/SpartanUI","title":"Wutname1/SpartanUI","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Wutname1/SpartanUI"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Wutname1 in #139: What skin are you using?"}],"action":{"name":"View Issue","url":"https://github.com/Wutname1/SpartanUI/issues/139#issuecomment-446088819"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Wutname1/SpartanUI/issues/139#issuecomment-446088819",
"url": "https://github.com/Wutname1/SpartanUI/issues/139#issuecomment-446088819",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Wutname1/SpartanUI] SpartanUI - vehicle bar is not displayed (#139)",
"sections": [
{
"text": "",
"activityTitle": "**wutname1**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Wutname1",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Wutname1/SpartanUI\",\n\"issueId\": 139,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Wutname1/SpartanUI\",\n\"issueId\": 139\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Wutname1/SpartanUI/issues/139#issuecomment-446088819"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 419518003\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Khiswow** [comment]
I know it's an old post, but the issue is back. Since a week or so the vehicule frame is missing when using the classic  skin (tested with war and it's back). The keybinds works fine but there's no art except the 2 bars.

Regards

**Comment by Mercian** [comment]
Same for me. the issue is happening since last Update. I'm using following version:
SUI Version: 5.2.1
SUI Build 467
Bartender 4 Version: 4.8.4
