### ISSUE TITLE
Make the default profile... the default?

### ISSUE THREAD

**Issue by Caerdon** [Wutname1/SpartanUI#14]
One thing I've grown to dislike about UI addons is the tendency to default to per-character profiles.  I have to believe the desire to have a different UI per toon is the exception rather than the rule.

It'd be great if the Default profile was automatically the selected profile for any toon that doesn't currently have any settings saved for the addon as this would allow the UI to just look great without a lot of prompts after getting it set up once on your first toon.

**Comment by Wutname1** [comment]
I like where your head is at. now i am going to write a wall of text as i think through this. 

**Generally speaking:** The reason you see this so much is that a lot of addons use a library called Ace3 made by some of the admins of WowAce (aka CurseForge, aka Curse.com). Ace3 Is a extremely useful suite of tools that simplifies specific tasks like Managing the Database, Creating the Options UI, and tons of other items.  While not all addons use the Ace3 options UI the majority at least use it for managing the DB or some other function. 

**Now why does this matter?** Ace3 defaults on load to create a profile for the character (as you noted). To change this SUI would need to reload the UI, to have someone load into the game just for SUI to detect its been used before and force a 2nd reload right away would lead to a lot of users to think something is wrong. That is not ideal. 

**Now to expand on your idea.** The best way to handle this is some changes to the setup wizard. Make setting up a profile/switching to/copying from the first thing a user is asked to do. This way we give people more control over how things are handled up front. 

Let me know what your thoughts are

**Comment by Wutname1** [comment]
You know as i am thinking about this [i actually did started a little bit on this at one point](https://github.com/Wutname1/SpartanUI/blob/master/Core/Framework.lua#L394). I remember trying to setup the profile copy part for the setup wizard. But the default profile / new profile option was not part of it back then.

Excuse the hack job paint work but this is sort of what i am thinking at the moment:
![wizard prompts](https://user-images.githubusercontent.com/704321/41928191-fc58a716-7939-11e8-8360-167a0f734e5c.png)

**Comment by Caerdon** [comment]
Seems like that should be sufficient!

**Comment by Wutname1** [comment]
Rather than promote the use of 'one profile to rules them all' The feature has been changed to a Profile Copy.  Perfect example of why promoting the use of a default profile is a bad idea: 

https://discordapp.com/channels/265564257347829771/456526639736815627/481395862258450443
> Hey I had a random idea/question. Would it be possible to make the status bars for tracking exp/rep/AP have a way to have them be different on each of your characters?
