### ISSUE TITLE
Long Yellow Bar in middle of screen

### ISSUE THREAD

**Issue by Lynyxx** [Wutname1/SpartanUI#142]
![yellow bar screenshot](https://user-images.githubusercontent.com/45806581/49841787-ef7a1300-fd86-11e8-9494-15a8b858fbd3.png)

After the update today and the new patch this yellow bar keeps appearing across my screen.  I don't know where it came from and I've looked at all my addons and Spartan is the only one with bar options.  Searched through those and can't see any changes made.

Please help!

**Comment by Coolranch** [comment]
I am experiencing the same except my bar is blue.  How can I disable the player frame in the middle of screen that appears during combat?

**Comment by patrickzero** [comment]
Same problem here,is the recurses bar in my case the runic power

**Comment by DDelvin** [comment]
Confirmed as well on Demon hunter, both specs.

**Comment by Wutname1** [comment]
Supposedly it is the Personal Resource Display Nameplate that is causing it. I cannot reproduce it, I have tried on my DH, DK, or Druid so it will take a little bit for me to find a fix. Could someone post their SpartanUI.lua WTF file? (Not blizz moved the install path with 8.1 it is now 
C:\Program Files\Blizzard\World of Warcraft\_retail_\WTF\Account\**AccountName**\SavedVariables

You can disable that nameplate here: 
![image](https://user-images.githubusercontent.com/704321/49885130-1d4d6f00-fdfc-11e8-90a2-33d181f60464.png)

**Comment by DDelvin** [comment]
>Could someone post their SpartanUI.lua WTF file?
File itself or just a textdump?

**Comment by patrickzero** [comment]
[SpartanUI.zip](https://github.com/Wutname1/SpartanUI/files/2673333/SpartanUI.zip)

**Comment by patrickzero** [comment]
THiS?

**Comment by Wutname1** [comment]
Thanks both of you. I will see if i can find what exactly is causing it latter tonight.

**Comment by mamanoodles** [comment]
I am getting this as well on my shadow priest :)

**Comment by Zabbel** [comment]
Same here with my Monk. For me it is the energy bar....

**Comment by siberia60** [comment]
Got the same issue. Long bar sometimes shows up. It's basically the resource bar.

**Comment by kocheise** [comment]
i don't have a yellow long bar i have a blue long bar when i go in to combat on all my toon's and so dose my gild members have the same thing going on too them too was wondering if there is a fix for it ?

**Comment by siberia60** [comment]
Hey Wutname1.

Wondering if there's any update on this issue? Do tell if you need more information, like lua dump files or anything. (I'll need you to tell me what and how to get said info.)

We are all very invested into helping you fix this.

Thank you for all the amazing work you have done so far!

**Comment by MrCellophane09** [comment]
I am getting a blue bar when mounting. Is there a fix or a workaround for this besides reloading the UI every single time?
