### ISSUE TITLE
Main Profile Keeps Getting Messed Up

### ISSUE THREAD

**Issue by SlydeRule** [Wutname1/SpartanUI#143]
I setup a profile on my main and copied it to an alt, both were good.  The next day I copied it to a second alt and then all 3 were messed up.  I fixed the main again, and copied it to the other two, checked them all and all were good.  Then the next day I copied to another alt and now all 4 profiles are messed up.  Why is this happening???  Where are these files stored so I can make a backup?

**Comment by Wutname1** [comment]
I know this is a bit old but. Are you copying via the SUI setup wizard or via the /sui options screen? I have not seen this ever occur using the setup wizard. If you copy via the setup wizard it should never effect the other profiles. 

the config for SUI is stored in "World of Warcraft\_retail_\WTF\Account\WUTNAME1\SavedVariables"

**Comment by SlydeRule** [comment]
Thanks for the reply.  I was using the Copy Profile from the Profiles section of the Spartan UI.  I finally got all my alts UIs set by by going directly to the Bartender addon Copy Profile.  Thanks.

**Comment by SlydeRule** [comment]
Thanks for the reply.  I was using the Copy Profile from the Profiles section of the Spartan UI.  I finally got all my alts UIs set by by going directly to the Bartender addon Copy Profile.  Thanks.
 
 
-----Original Message-----
