### ISSUE TITLE
Spartan and Titan panel

### ISSUE THREAD

**Issue by Kamear** [Wutname1/SpartanUI#145]
I am stuck using titan panel 5.14.7.8000 because anything newer than that version has an error and closes the bars. According to Titan the issue is in the ace 3 libraries. They are pointing the finger at other add-ons not updating their ace libraries. Truth be known I will stop using titan panel when and if the older version stops working completely because there is no way in hell I'm giving up Spartan. Spartan is the best addon period. I would like to keep both though. Any ideas on this issue?

**Comment by Wutname1** [comment]
All SpartanUI builds dynamically pull down the latest version of all Ace3 libraries when SUI is released. So as long as you are on the latest SUI version you should also have the latest Ace3 versions.
