### ISSUE TITLE
Tooltip Colour(?) LUA error

### ISSUE THREAD

**Issue by Crystalinn** [Wutname1/SpartanUI#149]
Message: Interface\AddOns\SpartanUI\components\Tooltips.lua:314: attempt to index local 'colors' (a nil value)
Time: Wed Jan 16 17:00:43 2019
Count: 1
Stack: Interface\AddOns\SpartanUI\components\Tooltips.lua:314: attempt to index local 'colors' (a nil value)
Interface\AddOns\SpartanUI\components\Tooltips.lua:314: in function <Interface\AddOns\SpartanUI\components\Tooltips.lua:258>
[C]: ?
[C]: in function `SetUnit'
Interface\FrameXML\UnitFrame.lua:474: in function `UnitFrame_UpdateTooltip'
Interface\FrameXML\UnitFrame.lua:460: in function <Interface\FrameXML\UnitFrame.lua:447>

Locals: self = GameTooltip {
 0 = <userdata>
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 SetVoidDepositItem = <function> defined =[C]:-1
 Hide = <function> defined =[C]:-1
 comparing = false
 SetSocketGem = <function> defined =[C]:-1
 SUIBorder = <unnamed> {
 }
 TopOverlay = <unnamed> {
 }
 default = 1
 SetItemByID = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 updateTooltip = 0.200000
 SetInventoryItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 SetBackdropColor = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
unit = "party2"
unitLevel = 0
colors = nil
qColor = nil
totColor = nil
lvlLine = nil
line = 2
sex = <table> {
 1 = ""
 2 = "Male "
 3 = "Female "
}
creatureClassColors = <table> {
 elite = "ELITE"
 worldboss = "World BossBoss"
 rareelite = "RARE-ELITERare"
 rare = "RARERare"
}
className = nil
classToken = nil
uName = "Unknown"
uRealm = nil
gName = nil
_ = nil
_ = 0
gRealm = nil
gender = ""
realmRelation = 1
nameString = "Unknown"
(*temporary) = <function> defined =[C]:-1
(*temporary) = GameTooltipTextLeft1 {
 0 = <userdata>
}
(*temporary) = "|c%s%s"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'colors' (a nil value)"
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @Interface\FrameXML\ActionButton.lua:74
 HealBot_Action_HealUnit2BarCount10 = HealBot_Action_HealUnit2BarCount10 {
 }
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 MerchantItem9ItemButtonStock = MerchantItem9ItemButtonStock {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 Recount_MainWindow_Bar6 = Recount_MainWindow_Bar6 {
 }
 SetTrainerServiceTypeFilter = <function> defined =[C]:-1
 StoreMicroButtonAlertGlowBottom = StoreMicroButtonAlertGlowBottom {
 }
 BT4Button46Shine5 = BT4Button46Shine5 {
 }
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 398
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFr

**Comment by Wutname1** [comment]
Where were you when you got this error? Do you recal what you may of moused over?

**Comment by Crystalinn** [comment]
If I remember right, I got this LUA in Zuldazar while looking for a group for the Child of Rezan wq. As for the mousing over part, it could've been someone also awaiting a queue, the Child of Rezan, myself via healbot, a UI element. I'm not too sure. I was playing a blood elf paladin, if that's any help at all.
