### ISSUE TITLE
No name tag profile 

### ISSUE THREAD

**Issue by lieladragon** [Wutname1/SpartanUI#15]
Im still have the same issues as i posted on the discord. Here is what the lua error is showing me

Message: ARKINV_Frame1Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
Message: ARKINV_Frame3Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
Message: ARKINV_Frame4Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
Message: ARKINV_Frame5Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
Message: ARKINV_Frame6Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
Message: ARKINV_Frame7Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
Message: ARKINV_Frame8Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
Message: ARKINV_Frame9Changer: Couldn't find relative frame: $parentContainer
Time: Tue Jun 26 22:24:29 2018
Count: 4
It goes on to 15 and then this:

Message: Error loading Interface\AddOns\SpartanUI_RaidFrames\scripts\Unit-RaidFrames.lua
Time: Tue Jun 26 22:24:29 2018
Count: 3
Message: Interface\AddOns\SpartanUI\components\Buffs.lua:106: Attempt to register unknown event "PARTY_CONVERTED_TO_RAID"
Time: Tue Jun 26 22:24:32 2018
Count: 1
Stack: Interface\AddOns\SpartanUI\components\Buffs.lua:106: Attempt to register unknown event "PARTY_CONVERTED_TO_RAID"
[C]: in function `RegisterEvent'
Interface\AddOns\SpartanUI\components\Buffs.lua:106: in function <Interface\AddOns\SpartanUI\components\Buffs.lua:90>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:571: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:9594: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:9605: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:2356: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2349>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1185: in function <Interface\FrameXML\UIParent.lua:1081>

Locals: <none>
Message: Interface\AddOns\SpartanUI\components\Minimap.lua:319: attempt to call global 'GetPlayerMapPosition' (a nil value)
Time: Tue Jun 26 22:24:32 2018
Count: 1
Stack: Interface\AddOns\SpartanUI\components\Minimap.lua:319: attempt to call global 'GetPlayerMapPosition' (a nil value)
Interface\AddOns\SpartanUI\components\Minimap.lua:319: in function `UpdateCoords'
Interface\AddOns\SpartanUI\components\Minimap.lua:324: in function `MinimapCoords'
Interface\AddOns\SpartanUI\components\Minimap.lua:287: in function `ModifyMinimapLayout'
Interface\AddOns\SpartanUI\components\Minimap.lua:155: in function <Interface\AddOns\SpartanUI\components\Minimap.lua:103>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:571: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
...
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1185: in function <Interface\FrameXML\UIParent.lua:1081>

Locals: <none>
Message: Interface\AddOns\SpartanUI\components\Objectives.lua:125: Attempt to register unknown event "PARTY_CONVERTED_TO_RAID"
Time: Tue Jun 26 22:24:32 2018
Count: 1
Stack: Interface\AddOns\SpartanUI\components\Objectives.lua:125: Attempt to register unknown event "PARTY_CONVERTED_TO_RAID"
[C]: in function `RegisterEvent'
Interface\AddOns\SpartanUI\components\Objectives.lua:125: in function <Interface\AddOns\SpartanUI\components\Objectives.lua:91>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:571: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:9594: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:9605: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:2356: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2349>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1185: in function <Interface\FrameXML\UIParent.lua:1081>

Locals: <none>
Message: ...ddOns\SpartanUI_PartyFrames\scripts\Spawn-Frames.lua:104: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
Time: Tue Jun 26 22:24:32 2018
Count: 1
Stack: ...ddOns\SpartanUI_PartyFrames\scripts\Spawn-Frames.lua:104: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
[C]: in function `RegisterEvent'
...ddOns\SpartanUI_PartyFrames\scripts\Spawn-Frames.lua:104: in function <...ddOns\SpartanUI_PartyFrames\scripts\Spawn-Frames.lua:33>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:571: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:9594: in function `LoadAddOn'
Interface\AddOns\ArkInventory\ArkInventory.lua:9605: in function `BlizzardAPIHook'
Interface\AddOns\ArkInventory\ArkInventory.lua:2356: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2349>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1185: in function <Interface\FrameXML\UIParent.lua:1081>

Locals: <none>
Message: ...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:467: Attempt to register unknown event "UNIT_POWER"
Time: Tue Jun 26 22:24:32 2018
Count: 1
Stack: ...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:467: Attempt to register unknown event "UNIT_POWER"
[C]: in function `RegisterEvent'
...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:467: in function <...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:464>
...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:477: in function <...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:471>
...nterface\AddOns\SpartanUI\libs\oUF\elements\tags.lua:661: in function `Tag'
...partanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:345: in function <...partanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:226>
...partanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:1792: in function `styleFunc'
Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:267: in function <Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:197>
(tail call): ?
Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:560: in function `Spawn'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:11: in function `SUI_PlayerFrames_Classic'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:172: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:168>
(tail call): ?
...
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1185: in function <Interface\FrameXML\UIParent.lua:1081>

Locals: <none>
Message: ...y\Externals\curse\svn\Ace3-AceEvent\AceEvent-3.0.lua:33: Attempt to register unknown event "FORGE_MASTER_OPENED"
Time: Tue Jun 26 22:24:33 2018
Count: 1
Stack: ...y\Externals\curse\svn\Ace3-AceEvent\AceEvent-3.0.lua:33: Attempt to register unknown event "FORGE_MASTER_OPENED"
[C]: in function `RegisterEvent'
...y\Externals\curse\svn\Ace3-AceEvent\AceEvent-3.0.lua:33: in function `OnUsed'
...urse\svn\CallbackHandler-1.0\CallbackHandler-1.0.lua:168: in function `RegisterEvent'
Interface\AddOns\ArkInventory\ArkInventory.lua:2451: in function <Interface\AddOns\ArkInventory\ArkInventory.lua:2349>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:558: in function `EnableAddon'
...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:651: in function <...y\Externals\curse\svn\Ace3-AceAddon\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:488: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:1185: in function <Interface\FrameXML\UIParent.lua:1081>

Locals: <none>
Message: Interface\AddOns\SpartanUI\components\Minimap.lua:319: attempt to call global 'GetPlayerMapPosition' (a nil value)
Time: Tue Jun 26 22:35:09 2018
Count: 3013
Stack: Interface\AddOns\SpartanUI\components\Minimap.lua:319: attempt to call global 'GetPlayerMapPosition' (a nil value)
Interface\AddOns\SpartanUI\components\Minimap.lua:319: in function <Interface\AddOns\SpartanUI\components\Minimap.lua:316>

Locals: (*temporary) = nil
(*temporary) = "player"
(*temporary) = "attempt to call global 'GetPlayerMapPosition' (a nil value)"
Timer = <function> defined =[C]:-1
UpdateCoords = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:316

**Comment by Wutname1** [comment]
As discussed in Discord, these are already fixed. Looks like Twitch is not detecting BFA and is installing the legion version of SUI.
