### ISSUE TITLE
Seal of wartorn fate (suggestion)

### ISSUE THREAD

**Issue by superjew78** [Wutname1/SpartanUI#150]
I know these quest turn-ins are blacklisted but is it possible to not have spartan auto accept the quest for war resources? Every time i want to purchase these with gold i have to turn off all the auto turn in options because it automatically selects the quest for the war resources. It doesnt turn it in but it selects it.

**Comment by Wutname1** [comment]
Can you post the link to the quest on wowhead?

**Comment by superjew78** [comment]
https://www.wowhead.com/currency=1580/seal-of-wartorn-fate

I noticed if you disable auto-turn in trivial quests then it wont do it but if its an option you like on then it will auto select it
