### ISSUE TITLE
error while doing quest

### ISSUE THREAD

**Issue by KKempoo** [Wutname1/SpartanUI#151]
1x [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'SUI_FramesAnchor:SetParent()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetParent'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:65: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:63>
[C]: ?
[C]: ?
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:100: in function <FrameXML\SecureStateDriver.lua:95>
FrameXML\SecureStateDriver.lua:127: in function <FrameXML\SecureStateDriver.lua:119>

Locals:
InCombatSkipped

**Comment by KKempoo** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'SUI_FramesAnchor:SetParent()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetParent'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:65: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:63>
[C]: ?
[C]: ?
[C]: in function `Show'
FrameXML\SecureStateDriver.lua:100: in function <FrameXML\SecureStateDriver.lua:95>
FrameXML\SecureStateDriver.lua:127: in function <FrameXML\SecureStateDriver.lua:119>

Locals:
InCombatSkipped

**Comment by Wutname1** [comment]
This is due to you being in combat when joining a group or entering a vehicle that modifies your unit frames.
