### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hubbotu** [Wutname1/SpartanUI#152]
Message: Interface\AddOns\SpartanUI\components\Minimap.lua:82: attempt to call method 'GetName' (a nil value)
Time: Fri Feb 22 12:27:23 2019
Count: 1
Stack: Interface\AddOns\SpartanUI\components\Minimap.lua:82: attempt to call method 'GetName' (a nil value)
Interface\AddOns\SpartanUI\components\Minimap.lua:82: in function <Interface\AddOns\SpartanUI\components\Minimap.lua:77>
Interface\AddOns\SpartanUI\components\Minimap.lua:114: in function <Interface\AddOns\SpartanUI\components\Minimap.lua:113>

Locals: MouseFocus = DethsFrameLib_1.1_Frame_1 {
 GetAlignHelper = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:283
 _fill_h = false
 OnSetWidth = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:503
 SetHeight = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:462
 _layout = "FLOW"
 _texture = DethsFrameLib_1.1_Texture_3 {
 }
 OnSetHeight = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:503
 _defaults_minHeight = 10
 GetParent = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/ParentFrame.lua:132
 _flexible = false
 SetWidth = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:441
 GetType = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:330
 IsEnabled = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:405
 SetEnabled = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:412
 OnSetSize = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:503
 GetRequiredHeight = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:299
 SetSize = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:472
 _maxChildWidth = 904.000244
 SetMinHeight = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:455
 SetColors = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/ParentFrame.lua:136
 SetAlignment = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:305
 _defaults_minWidth = 10
 SetDirection = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:317
 _alignment = "TOPLEFT"
 _alignHelper = DethsFrameLib_1.1_Texture_1 {
 }
 _parent_frame = <table> {
 }
 GetPadding = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:295
 GetAlignment = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:285
 Enable = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:407
 SetMinWidth = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\DethsFrameLib.lua:434
 _spacing = 10
 PositionChildren = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:171
 _requiredHeight = 495.000185
 _defaults_isEnabled = true
 SetPadding = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:372
 Resize = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:473
 _SetSize = <function> defined =[C]:-1
 GetLayout = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:293
 GetSpacing = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:301
 SetSpacing = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:382
 _children = <table> {
 }
 Contains = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:105
 SetLayout = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:327
 GrowChildren = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:117
 _borderColor = <table> {
 }
 GetChildren = <function> defined @Interface\AddOns\Dejunk\Libs\DethsFrameLib\Objects/Frame.lua:289
 Remove = <f

**Comment by Wutname1** [comment]
Looks like an issue with Dejunk minimap icon & finding how its attached. I looked at the moste recent version of Dejunk and dont see a issue i also installed the addon and am unable to get the error.
