### ISSUE TITLE
Transparency Slider not adjusting properly

### ISSUE THREAD

**Issue by FleshTorpedo** [Wutname1/SpartanUI#153]
Hello! I noticed that the transparency slider doesnt change the background of the bottom status bars (the bars that track exp, honor, azerite, etc, etc... Their background transparency seems to be independent of the rest of the UI. I hope bringing you this information can be beneficial to you and the community. 

Thanks!

**Comment by Wutname1** [comment]
Unfortunetly due to the layers and glowing fill used in status bars making them transparent does not result in anything that looks decent.
