### ISSUE TITLE
WorldQuestCompleteAlertFrame

### ISSUE THREAD

**Issue by DeathRedeemed** [Wutname1/SpartanUI#154]
I cannot get this frame to move... It's location is horizontally center, vertically it is up and out off the screen, I am only able to see the very bottom of the frame.

This has been a recent issue... I have tried multiple addons (moveanything, dominos) to fix it with no luck. I have re-setup my entire interface, deleted all addons and then re-installed and set up 1 by 1 and I am still having this issue.

Please help!

**Comment by Wutname1** [comment]
Frame is not being touched by SUI.
