### ISSUE TITLE
Swatter catches error during fight

### ISSUE THREAD

**Issue by Stryke69** [Wutname1/SpartanUI#158]
Hope you can help

Date: 2019-04-01 17:07:42
ID: 12
Error occured in: AddOn: SpartanUI
Count: 1
Message: Note: AddOn SpartanUI attempted to call a protected function (SUI_focustargetFrame:SetScale()) during combat lockdown.
Debug:
   [C]: SetScale()
   ...ace\AddOns\SpartanUI_Style_War\Module-UnitFrames.lua:1208: PositionFrame()
   ...ace\AddOns\SpartanUI_Style_War\Module-UnitFrames.lua:1159:
      ...ace\AddOns\SpartanUI_Style_War\Module-UnitFrames.lua:1156
   [C]: ?
   [C]: ?
   [C]: Show()
   ..\FrameXML\SecureStateDriver.lua:100:
      ..\FrameXML\SecureStateDriver.lua:95
   ..\FrameXML\SecureStateDriver.lua:127:
      ..\FrameXML\SecureStateDriver.lua:119
Locals:
None
AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  Ace3, v
  ACP, vr259 
  AdvancedInterfaceOptions, v1.2.9
  ArkInventory, v30824
  ArkInventoryRules, v10300
  ArkInventoryRulesExample, v10000
  ArkInventorySearch, v10300
  AtlasLoot, vv8.09.00
  AtlasLootBattleforAzeroth, vv8.09.00
  Auctionator, v8.1.0
  AzeritePowerWeights, v8.1.13
  Bartender4, v4.8.2
  CanIMogIt, v8.1.5v1.14
  DBMCore, v8.1.13-6-g75e043524
  DBMDefaultSkin, v
  DBMSpellTimers, v
  DBMStatusBarTimers, v
  DBMVPDeutschweiblich, v8.1.11
  DejaCharacterStats, v800r103
  Details, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Dominos, v8.1.3
  DominosCast, v
  DominosEncounter, v
  eAlignUpdated, v8.1.0
  EasyScrap, v19
  Farmer, v2.6.3
  FarmHud, v8.1-1-release
  FishingBuddy, v1.9.29
  FlightMapEnhanced, v3.0.17
  GarrisonCommanderBroker, v3.1.0 1.1.0
  GatherMate2, v1.43.6
  GTFO, v4.46.17
  HandyNotes, vv1.5.5
  HandyNotesBattleForAzerothTreasures, v1
  HandyNotesBrokenShore, vv1.30
  HandyNotesDungeonLocations, v1.45
  Informant, v8.1.6246 (SwimmingSeadragon)
  MaxDps, v8.1.3.1
  MaxDpsHunter, v8.1.5
  MrFish, v2.4.3 80100
  Notes, v8.1.0
  OPie, vWalnut 1
  Pawn, v2.2.39
  RangeDisplay, vv4.8.4
  Routes, vv1.6.1
  Scrap, v13.15
  ScrapMerchant, v13.15
  SpartanUI, v5.0.12
  SpartanUIArtwork, v5.0.12
  SpartanUIPartyFrames, v5.0.12
  SpartanUIPlayerFrames, v5.0.12
  SpartanUIRaidFrames, v5.0.12
  SpartanUIStyleFel, v5.0.12
  SpartanUIStyleMinimal, v5.0.12
  SpartanUIStyleTransparent, v5.0.12
  SpartanUIStyleWar, v5.0.12
  Stubby, v8.1.6274 (SwimmingSeadragon)
  TheUndermineJournal, v5.4.20190330
  Titan, v5.17.0.80100
  TitanBag, v5.17.0.80100
  TitanClock, v5.17.0.80100
  TitanCurrenciesMulti, v6.3
  TitanGold, v5.17.0.80100
  TitanMail, v7.35
  TitanPerformance, v5.17.0.80100
  TitanRepair, v5.17.0.80100
  TradeSkillMaster, vv4.7.6
  TradeSkillMasterAppHelper, vv4.0.2
  WeakAuras, v2.11.6
  WIM, v602
  WorldQuestTab, v8.1.03
  WorldQuestTracker, v
  WoWGatheringNodes, v02.18.19
  xCT, v4.4.9
  BlizRuntimeLib_deDE v8.1.5.80100 <none>
  (ck=83c)

**Comment by Wutname1** [comment]
Known issue due to the way frames are built currently if you are in combat. Hopefully will be resolved with the next major version of SUI
