### ISSUE TITLE
Some irritating error?

### ISSUE THREAD

**Issue by Erielan** [Wutname1/SpartanUI#159]
Hi!
I got some irritating bug/error/whatever you call it. There is a frame that when I get dmg, or get healed from any source, it appears in the middle of my screen. I will provide screen shot of it. I don't know how to hide it. I (think) tried everything. Disabling every addon, disabling only Spartan UI, enabling only Spartan UI, clearing cache. I even deleted and re-downloaded addon and the whole game! Nothing worked for me. I really love Spartan UI and I can't play WoW without it. I hope you could help with hiding it because it's incredible irritating.
Ps. Sorry for any grammatical errors since English is not my native language.

![spartan ui error](https://user-images.githubusercontent.com/49399892/55724161-1da4f200-5a0b-11e9-9874-ae11c198e15c.png)

**Comment by BattleQueen** [comment]
yeah the same problem i have!

**Comment by Wutname1** [comment]
https://github.com/Wutname1/SpartanUI/issues/142
