### ISSUE TITLE
Pandas cant load bfa theme

### ISSUE THREAD

**Issue by BattleQueen** [Wutname1/SpartanUI#162]
![image](https://user-images.githubusercontent.com/43797051/55956482-5d1a4b00-5c64-11e9-829b-a901357f1588.png)

**Comment by Wutname1** [comment]
Re-Launch the game & make sure everything is installed, Green boxes like that means wow cannot find the image files.

**Comment by BattleQueen** [comment]
i installed everything yesterday.. the problem is that i dont have a faction ...

**Comment by Wutname1** [comment]
Ohhh ya, completely forgot about that.
