### ISSUE TITLE
tried to call protected function

### ISSUE THREAD

**Issue by KKempoo** [Wutname1/SpartanUI#164]
1x [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'oUF_Spartan_RaidFrames_ClassicRaidUnitButton40:Hide()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `Hide'
...Ons\SpartanUI_RaidFrames\scripts\Global-Features.lua:83: in function `PostUpdateDebuffs'
...\SpartanUI_RaidFrames\scripts\FrameStyle_Classic.lua:200: in function <...\SpartanUI_RaidFrames\scripts\FrameStyle_Classic.lua:42>
...\SpartanUI_RaidFrames\scripts\FrameStyle_Classic.lua:237: in function `styleFunc'
SpartanUI\libs\oUF\ouf.lua:348: in function <SpartanUI\libs\oUF\ouf.lua:265>
(tail call): ?
(tail call): ?
FrameXML\RestrictedFrames.lua:758: in function <FrameXML\RestrictedFrames.lua:750>
[C]: ?
[C]: ?
FrameXML\RestrictedFrames.lua:777: in function `CallMethod'
[string "		local header = self:GetParent()..."]:51: in function <[string "		local header = self:GetParent()..."]:1>
(tail call): ?
[C]: ?
FrameXML\RestrictedExecution.lua:484: in function <FrameXML\RestrictedExecution.lua:447>
FrameXML\SecureGroupHeaders.lua:116: in function <FrameXML\SecureGroupHeaders.lua:110>
FrameXML\SecureGroupHeaders.lua:173: in function <FrameXML\SecureGroupHeaders.lua:130>
FrameXML\SecureGroupHeaders.lua:495: in function `SecureGroupHeader_Update'
FrameXML\SecureGroupHeaders.lua:62: in function <FrameXML\SecureGroupHeaders.lua:60>

Locals:
InCombatSkipped

**Comment by Wutname1** [comment]
known issue due to the graphics used in SUI frames & being in combat while the group is modified. cant be solved without a full unitframe rebuild (currently in progress) Slated for 5.1
