### ISSUE TITLE
Minimap tooltip not working

### ISSUE THREAD

**Issue by mamanoodles** [Wutname1/SpartanUI#169]
When I try to hover over fishing pools, battle pets, quest markers, nothing happens. Normally you can see what wild pet it is by hovering over a green paw but since I updated this morning- nothing. I disabled every single addon one at a time and it's this addon :[

**Comment by Wutname1** [comment]
I cant reproduce your bug did you customize the tooltip position at all? /sui > Modules > Tooltips
if so go to that screen and reset the position the patch may of messed it up. Please let me know

**Comment by mamanoodles** [comment]
I reset the tooltip thing btw, no change :[

**Comment by xKokonzo** [comment]
I have the same problem with the actual Version of the Addon. If SUI is deactivated the Tooltip/hover works. Any suggestions :( ?

**Comment by Wutname1** [comment]
What version are you on if you type /sui version

**Comment by xKokonzo** [comment]
Thanks for reply. Version: 5.1.3 / Build 101 / Bartender4 version 4.8.3
