### ISSUE TITLE
Camera doesn't reset.

### ISSUE THREAD

**Issue by Stepkiller** [Wutname1/SpartanUI#17]
Hello, as soon as I downloaded this addon my camera didn't reset to the position behind me and I have tried different characters and different options but nothing works. I quit the game and logged back in on a character and the camera worked, then I logged in to another character and the camera didn't work, so I logged back to the other character again and the camera didn't work again. This is quite annoying so I would really appreciate any help at all, thx.

**Comment by Stepkiller** [comment]
And I don't even have the addon activated on these characters so I am really confused here O.o

**Comment by Wutname1** [comment]
This is a known issue with world of Warcraft and is not related to any one addon. https://us.battle.net/forums/en/wow/topic/6607331923 if you disable the spin cam feature of SpartanUI nothing in spartanui will touch the camera.
