### ISSUE TITLE
Bars not hidden after exiting vehicle

### ISSUE THREAD

**Issue by Necessities3788** [Wutname1/SpartanUI#171]
I checked around and found a few other bugs pertaining to exiting vehicles but didn't find this one.

I have the art style set to War with the scale set to max.

When I exit a vehicle the stance/forms and the minibar/bags bars which are normally hidden with the extendable graphics at the top of the screen are no longer hidden even though the graphics are still closed. I've attached an image so that you can understand my woefully inadequate attempts to explain the issue.

EDIT: I forgot to mention that if I extend the graphics, then hide them again the bars are hidden like normal.

Thanks!

![WoWScrnShot_062519_223359](https://user-images.githubusercontent.com/52228097/60149271-c147a800-9799-11e9-9576-cf82efe75d8c.jpg)

**Comment by Whatsatotem** [comment]
ahh yea i remember this issue,  had it on my shaman, its not just the vehicles that did it, the buttons are also completely inactive whether the box is opened or closed
had this issue on my shaman while raiding in the first raid of the xpac, (haven't had it recently though) that this would happen while i was trying to control my primal fire elemental but i couldn't drop the meteor cause the buttons were broke.  not sure it has anything to do with vehicles, however, if you aren't updated to SUI 5.1.1 see that first

**Comment by Wutname1** [comment]
Thanks for the info im looking into this one right now the screenshot helps alot, the fact that it shows your only a lvl 9 worgen makes it easy to test.

**Comment by Necessities3788** [comment]
@Whatsatotem did bring up a good point as to information that I forgot to give. 

-I am running that latest version of the SpartanUI addon (5.1.1). 
-The addon was downloaded and installed through the Twitch app.
-I have no other addons that effect the bars but just in case it matters, here is my addon list including the ones that were automatically downloaded by SpartanUI:
          Mount Journal Enhanced
          All The Things
          Bartender4
          WorldQuestTracker
          Details! Damage Meter
          Bagnon
          NPCScan
          Total RP 3
          Overachiever
