### ISSUE TITLE
Auto selling Mechagon spare parts

### ISSUE THREAD

**Issue by loundy** [Wutname1/SpartanUI#175]
Auto loot seems to be scrapping all Mechagon spare parts, including Chain Ignitercoil (epic) and Energy Cell (superior).

**Comment by Wutname1** [comment]
https://www.wowhead.com/item=168327/chain-ignitercoil
https://www.wowhead.com/item=166971/empty-energy-cell
https://www.wowhead.com/item=170500/energy-cell

**Comment by loundy** [comment]
another one for you to add when you get a moment 
168135, --Titans Blood

**Comment by Wutname1** [comment]
Thanks. Added.
