### ISSUE TITLE
Mouseover / Hoverover Tooltips Show off-screen

### ISSUE THREAD

**Issue by Zirkonwolf** [Wutname1/SpartanUI#176]
The item tooltip that shows details about the current highlighted item clip off screen but reloading UI temporarily fixes the issue until combat starts and ends. Then the issue happens again. See side by side comparison.

![SpartainUI Normal](https://user-images.githubusercontent.com/50084305/60412097-bbc8d400-9b84-11e9-9a51-8a885fbd4f2c.png)

![SpartainUI Broken](https://user-images.githubusercontent.com/50084305/60412374-ae601980-9b85-11e9-80d4-cdd4c908f2c6.png)

**Comment by Wutname1** [comment]
This is a blizzard bug. If you go to Modules > Enabled Modules and disable Tooltips SUI no longer will interact with any game tooltips and the issue still happens.
