### ISSUE TITLE
(BUG 8.2) Object description frames

### ISSUE THREAD

**Issue by Raikishin** [Wutname1/SpartanUI#177]
Hello, 

The object description frame comes out of the screen after 10 minutes, I have to disable the addon and then reload it, same with the minimap, from 8.2.

![WoWScrnShot_070119_110622](https://user-images.githubusercontent.com/52405207/60424948-c1a8ce80-9bf1-11e9-951d-d19ec19d31cf.jpg)

**Comment by Wutname1** [comment]
The screenshot shows a tooltip bug that is a known blizzard issue.

**Comment by Wutname1** [comment]
Please post a screenshot of the minimap issue.
