### ISSUE TITLE
Lua error:  SetPoint failed

### ISSUE THREAD

**Issue by fireymerlin** [Wutname1/SpartanUI#181]
I just installed SpartanUI.  
When I log on or reloadui, I get this error.

1x FrameXML\UIParent.lua:2203: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: BuffFrame:SetPoint.
[C]: in function `SetPoint'
FrameXML\UIParent.lua:2203: in function `UIParent_UpdateTopFramePositions'
FrameXML\PlayerFrame.lua:316: in function `PlayerFrame_ResetPosition'
FrameXML\PlayerFrame.lua:200: in function `OnEvent'
FrameXML\UnitFrame.lua:933: in function <FrameXML\UnitFrame.lua:931>

**Comment by Wutname1** [comment]
What skin are you using?

**Comment by fireymerlin** [comment]
I figured it out.  If I use the mover for the buffs, it generates the
errors.
