### ISSUE TITLE
Setup Wizard - interrupt announcer 

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#182]
![image](https://user-images.githubusercontent.com/41389109/61178797-e0786f00-a5ba-11e9-85c7-64551c4a4fe9.png)

Have the options show up from the modules into the setup wizard

**Comment by Wutname1** [comment]
Turns out most of the code was there, it was broken.

**Comment by Deiveron** [comment]
Having issues with the announcer. it announces but announces incomplete. doesnt show the spell just gives 
![WoWScrnShot_081719_225826](https://user-images.githubusercontent.com/54242736/63226589-7babc800-c1a9-11e9-9b4b-ccf501a05ca0.jpg)

**Comment by Wutname1** [comment]
@Deiveron  %sl was changed to %spell 
I added a %sl to %spell compatability for 5.2.3 61d019659996bab0e79bee6f2da6fa511b35ed2a
