### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by superjew78** [Wutname1/SpartanUI#184]
Date: 2019-07-19 04:16:15
ID: 1
Error occured in: AddOn: SpartanUI_PlayerFrames
Count: 1
Message: Note: AddOn SpartanUI_PlayerFrames attempted to call a protected function (UNKNOWN()) during combat lockdown.
Debug:
   [C]: ?
   [C]: ?
   [C]: SetParent()
   ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:55:
      ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:53
   [C]: ?
   [C]: ?
   [C]: Hide()
   ..\FrameXML\SecureStateDriver.lua:103:
      ..\FrameXML\SecureStateDriver.lua:95
   ..\FrameXML\SecureStateDriver.lua:127:
      ..\FrameXML\SecureStateDriver.lua:119
Locals:
None
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Ace3, v
  AskMrRobot, v78
  Auctionator, v8.2.0
  AutoRepair, v
  BagBrother, v
  Bagnon, v8.2.0
  Bartender4, v4.8.3
  BFAInvasionTimer, vv8.2.2
  CollectMe, v2.10.1
  DBMAzerothBfA, v
  DBMCore, v8.2.6
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DerangementPetBattleCooldowns, vv1.1.5
  GarrisonMissionManager, vv59
  GarrisonMissionManagerLoadOnLogin, vv1
  HandyNotes, vv1.5.5
  HandyNotesWarfrontRares, v0.5.0
  HHPH, v2
  InFlightLoad, v8.2.003
  InProgressMissions, v8.1.25
  Livestock, v2.7.9
  MaxDps, v8.2.0.2
  MaxDpsDeathKnight, v8.1.5
  Omen, v3.2.2
  Paste, v1.4.10
  Pawn, v2.2.46
  PetJournalEnhanced, v2.9.30
  PetTracker, v8.2.0
  PetTrackerBreeds, v8.2.0
  PetTrackerJournal, v8.2.0
  PetTrackerSwitcher, v8.2.0
  PetTrackerUpgrades, v8.2.0
  Recount, vv8.2.0a
  Rematch, v4.9.10
  Scrap, v8.2.0
  ScrapSpotlight, v8.2.0
  SlideBar, v7.3.1 (<%codename%>)
  SmexyMats, v8.1.0.3
  SpartanUI, v5.1.9
  SpartanUIArtwork, v5.1.9
  SpartanUIFilmEffects, v5.1.9
  SpartanUIPartyFrames, v5.1.9
  SpartanUIPlayerFrames, v5.1.9
  SpartanUIRaidFrames, v5.1.9
  SpartanUISpinCam, v5.1.9
  SpartanUIStyleFel, v5.1.9
  SpartanUIStyleMinimal, v5.1.9
  SpartanUIStyleTransparent, v5.1.9
  SpartanUIStyleWar, v5.1.9
  tdBattlePetScript, v80100.01
  tdBattlePetScriptRematch, v80100.01
  TomCats, v1.0.12
  TomCatsMechagon, v1.0.12
  TomCatsNazjatar, v1.0.12
  TomTom, vv80200-1.0.3
  WeakAuras, v2.13.4
  WorldBossTimers, vv1.4
  WorldQuestsList, v89
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=5fc)

**Comment by Wutname1** [comment]
Known issue, will be resolved with the SUI 6.0 Unit frame re-write
