### ISSUE TITLE
F.E.A.S.T on autosell 

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#186]
https://www.wowhead.com/item=170211/recipe-famine-evaluator-and-snack-table

i dont know if the common version (item=168368) is the same way, but i got the uncommon one and it autosold (i cant use it till i learn rank 2, so im carrying it around)

**Comment by Wutname1** [comment]
c6187a03f0c8004779d6e9b6cc796ab52bfb197e got misstagged
