### ISSUE TITLE
Status bar disabled when you disable the minimap module

### ISSUE THREAD

**Issue by zerocool145** [Wutname1/SpartanUI#189]
by deactivating the minimap module, the status bars are deactivated, I think those bars should be attached to the artwork.
This is because I need the module disabled but the active bars for the Azerite and the honor

![minid](https://user-images.githubusercontent.com/53354031/61980702-1fe08b80-afbd-11e9-8c71-d041f35f7c36.png)

![minia](https://user-images.githubusercontent.com/53354031/61980835-70f07f80-afbd-11e9-9efa-524a14841567.png)

**Comment by Wutname1** [comment]
I cannot replicate, (Mine works fine when i disable minimap) 

Can you ensure LUA errors are on by putting this in your chat "/console scripterrors 1" then try to disable the minimap again.

 If no errors popup then can you post your SpartanUI.lua from the WTF folder?
`World of Warcraft\_retail_\wtf\Account\USERNAME\SavedVariables\SpartanUI.lua`
It might be some setting is messed up.
