### ISSUE TITLE
Stagger Bar (Brewmaster Monk Spec)

### ISSUE THREAD

**Issue by InfinityBored1996** [Wutname1/SpartanUI#194]
Not sure if this is bug or enhancement. I'm not able to see my stagger bar anywhere on screen. Not under my unit frame or anywhere for that matter. Not sure if others are getting the same error or if i'm missing a setting in the interface options. I'm using the War style.

**Comment by Wutname1** [comment]
What version of SUI are you running?

**Comment by InfinityBored1996** [comment]
5.1.11.zip

**Comment by InfinityBored1996** [comment]
update: when i turn on personal resources from wow interface settings a bar for stagger will then appear but even that has a weird glitch sometime (attached screenshot) the green spec is the filled in part and the empty bar is where it should fill in hope this helps. Would be great to have this on my personal unit frame
![glitch](https://user-images.githubusercontent.com/53909585/62746552-e0cb2500-ba15-11e9-9161-728ce3465422.PNG)
