### ISSUE TITLE
Classic Spartan UI_Hunter Pet Happiness

### ISSUE THREAD

**Issue by Duramax007** [Wutname1/SpartanUI#195]
I am new to this UI but it seems to be working great mostly.  I can not see my pets Happiness level while using the UI.  I see an option for health bar to change based on happiness but it is not working.  If i disable player bar and use the blizzard default it shows that my pet is in the red and very unhappy but the UI appears normal with SpartanUI.

Thank You

**Comment by Wutname1** [comment]
Added in ae34c8b0613a87bf291b59e416172b1bb4edd970
