### ISSUE TITLE
Error on launch with beta 13

### ISSUE THREAD

**Issue by Caerdon** [Wutname1/SpartanUI#20]
Stack trace below:

Message: Interface\AddOns\SpartanUI\core\Framework.lua:1205: bad argument #1 to 'match' (string expected, got nil)
Time: Mon Jul  9 10:11:04 2018
Count: 834
Stack: Interface\AddOns\SpartanUI\core\Framework.lua:1205: bad argument #1 to 'match' (string expected, got nil)
[C]: in function `match'
Interface\AddOns\SpartanUI\core\Framework.lua:1205: in function `comma_value'
Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:236: in function <Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:128>
Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:464: in function <Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:461>

Locals: (*temporary) = nil
(*temporary) = "^([^%d]*%d)(%d*)(.-)$"
(*temporary) = "string expected, got nil"

**Comment by Wutname1** [comment]
Fixed in dfbc7241a9d32705439110261988513f56449596
