### ISSUE TITLE
Cant see combo points as druid

### ISSUE THREAD

**Issue by GrillBanditten** [Wutname1/SpartanUI#204]
well as the title says "Cant see combo points as druid", and i am using version 5.2.3-classic
windows cllient.

**Comment by Wutname1** [comment]
I had a feeling this would pop up. It's going to have to wait until I get a druid to 20...

**Comment by GrillBanditten** [comment]
Does it work with rogues`?
Would like to borrow you mine :D
since this UI is as awesome as it is :D

**Comment by Wutname1** [comment]
I managed to get my druid to 5, I will be leveling it this weekend (If i can get on)

**Comment by GrillBanditten** [comment]
really appreciate your effort :)

**Comment by AkashaTV** [comment]
Yeah I really like the UI but its unusable as a rogue=( Theres no combo point tracker/indicator. Its not just druids.

**Comment by Wutname1** [comment]
Rogue's should have combo points i leveled one to 10 on Tuesday without issue. what skin were you using

**Comment by GrillBanditten** [comment]
Dont know what you did in the 5.2.5 update, but i can now see my combo points...

**Comment by Wutname1** [comment]
Are you on the alpha builds? I did a change that i was hoping would fix it but was not 100% sure (im lvl 16)

**Comment by GrillBanditten** [comment]
nope release 5.2.5

**Comment by Wutname1** [comment]
Fixed in 5.2.6. reason you were able to see them before this release was that you had finally trained shred. Previously it used the existence of that spell to see if you had cat form
