### ISSUE TITLE
Lastest update for retail.

### ISSUE THREAD

**Issue by BigShanUK** [Wutname1/SpartanUI#207]
The addon is not loading and there is no such command to open the addon settings aswell.

**Comment by wichtler1980** [comment]
Unfortunately, the addon does not work anymore since today's update :(

**Comment by BigShanUK** [comment]
> Unfortunately, the addon does not work anymore since today's update :(

5.2.3 is still working 👍

**Comment by wichtler1980** [comment]
5.2.4 does not Work have a link to 5.2.3

**Comment by tylhan94** [comment]
I'm also having issues with latest spartanui update. can someone explain how to roll back to 5.2.3?

**Comment by Emeraldlily** [comment]
Need help with roll back to 5.2.3 since update does not work

**Comment by BigShanUK** [comment]
You can download 5.2.3 here https://www.curseforge.com/wow/addons/spartan-ui/files - delete the updated sparta first and copy the files over addons location

**Comment by Emeraldlily** [comment]
Thanks!!

**Comment by wichtler1980** [comment]
Thanks man!!

**Comment by Wutname1** [comment]
Fixed. in new update. Sorry everyone. this was the issue... 
![image](https://user-images.githubusercontent.com/704321/64034442-4b9ee600-cb14-11e9-8541-91187764b6fc.png)
1 letter.
