### ISSUE TITLE
Combo points for Rogue aren't shown/tracked

### ISSUE THREAD

**Issue by AkashaTV** [Wutname1/SpartanUI#208]
I really really like the layout and UI overall but as a Rogue main, without displayed combo points its functionally unusable=(

**Comment by AkashaTV** [comment]
This is Classic btw. And the version is the current one up on twitch app.

**Comment by Wutname1** [comment]
Combo points are under your player frame. What skin are you using? I leveled a rogue to 10 on the War skin with 0 issues.

**Comment by AkashaTV** [comment]
Sec ill post a screenshot.
![image](https://user-images.githubusercontent.com/54716228/64052721-98eb7980-cb4d-11e9-97bc-d01c1f2094ba.png)

**Comment by AkashaTV** [comment]
That mob has 2 combo points on it but its not displayed anywhere that I can see.

**Comment by Wutname1** [comment]
****
![image](https://user-images.githubusercontent.com/704321/64056753-40bb7400-cb5b-11e9-9630-291bba899fc5.png)

**Comment by AkashaTV** [comment]
Whelpl logged in today and that area is borked=( 
![image](https://user-images.githubusercontent.com/54716228/64298384-58bc3a80-cf43-11e9-98f0-ad5c942d1256.png)

**Comment by Wutname1** [comment]
What version are you on?
