### ISSUE TITLE
UI won't load, options not working

### ISSUE THREAD

**Issue by snuttis68** [Wutname1/SpartanUI#209]
After latest update through Twitch, SpartanUI no longer works.
All my old styles are gone and /sui no longer has any effect.

Old classic bars are at the bottom, map at top right and odd white lines on the side

Lua-error shows this:

`
Date: 2019-08-30 19:39:08
ID: -5
Error occured in: Global
Count: 1
Message: ..\AddOns\SpartanUI_Style_Fel\Style.lua line 42:
   attempt to index field 'DBMod' (a nil value)
Debug:
   SpartanUI_Style_Fel\Style.lua:42:
      SpartanUI_Style_Fel\Style.lua:41
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:540: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:450: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:569: TimeManager_LoadUI()
   ..\FrameXML\UIParent.lua:1210:
      ..\FrameXML\UIParent.lua:1108
Locals:
None
AddOns:
  Swatter, v7.3.1 (<%codename%>)
  Atlas, vv1.44.06
  AtlasArena, vv1.07.03
  AtlasBattlegrounds, vv1.44.01
  AtlasBurningCrusade, vv1.44.01
  AtlasCataclysm, vv1.44.01
  AtlasClassicWoW, vv1.44.01
  AtlasClassOrderHalls, vv1.44.01
  AtlasDungeonLocs, vv1.44.01
  AtlasLegion, vv1.44.01
  AtlasMistsofPandaria, vv1.44.01
  AtlasOutdoorRaids, vv1.44.01
  AtlasScenarios, vv1.44.00
  AtlasTransportation, vv1.44.01
  AtlasWarlordsofDraenor, vv1.44.01
  AtlasWorldEvents, vv3.25
  AtlasWrathoftheLichKing, vv1.44.01
  AtlasLoot, vv8.10.00
  AtlasLootBattleforAzeroth, vv8.10.00
  AtlasLootBurningCrusade, vv8.10.00
  AtlasLootCataclysm, vv8.10.00
  AtlasLootClasses, vv3.1
  AtlasLootClassic, vv8.10.00
  AtlasLootLegion, vv8.10.00
  AtlasLootMistsofPandaria, vv8.10.00
  AtlasLootWarlordsofDraenor, vv8.10.00
  AtlasLootWrathoftheLichKing, vv8.10.00
  Bartender4, v4.8.4
  DBMCore, v8.2.15
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  LibSharedMedia30, v3.0-112
  Omen, v3.2.2
  SlideBar, v7.3.1 (<%codename%>)
  SpartanUI, v5.2.4
  SpartanUIArtwork, v5.2.4
  SpartanUIPartyFrames, v5.2.4
  SpartanUIPlayerFrames, v5.2.4
  SpartanUIRaidFrames, v5.2.4
  SpartanUISpinCam, v5.2.4
  SpartanUIStyleFel, v5.2.4
  SpartanUIStyleMinimal, v5.2.4
  SpartanUIStyleTransparent, v5.2.4
  SpartanUIStyleWar, v5.2.4
  Titan, v5.18.2.80200
  TitanBag, v5.18.2.80200
  TitanClock, v5.18.2.80200
  TitanGold, v5.18.2.80200
  TitanLocation, v5.18.2.80200
  TitanLootType, v5.18.2.80200
  TitanPerformance, v5.18.2.80200
  TitanRepair, v5.18.2.80200
  TitanVolume, v5.18.2.80200
  TitanXP, v5.18.2.80200
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=65a)

**Comment by Wutname1** [comment]
Click refresh in the twitch app and update to 5.2.5
