### ISSUE TITLE
Getting white bars in player frame and not able to add padding between Party frames

### ISSUE THREAD

**Issue by Larzie** [Wutname1/SpartanUI#210]
Date: 2019-08-31 02:07:26
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\SpartanUI\libs\SUF\elements\pvpindicator.lua line 69:
   attempt to call global 'UnitIsMercenary' (a nil value)
Debug:
   ...\AddOns\SpartanUI\libs\SUF\elements\pvpindicator.lua:69:
      ...\AddOns\SpartanUI\libs\SUF\elements\pvpindicator.lua:41
   (tail call): ?
   SpartanUI\libs\SUF\SUF.lua:213:
      SpartanUI\libs\SUF\SUF.lua:196
   (tail call): ?
Locals:
self = SUI_playerFrame {
 0 = <userdata>
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\portrait.lua:87
 TextUpdate = <function> defined @Interface\AddOns\SpartanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:97
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\SUF.lua:196
 ComboPoints = <unnamed> {
 }
 SUI_ClassIcon = <unnamed> {
 }
 UNIT_SPELLCAST_FAILED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:183
 unitEvents = <table> {
 }
 PARTY_LEADER_CHANGED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\leaderindicator.lua:59
 UNIT_PET = <function> defined @Interface\AddOns\SpartanUI\core\SUF.lua:236
 UNIT_HEALTH_FREQUENT = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\health.lua:177
 StatusText = <unnamed> {
 }
 GroupRoleIndicator = <unnamed> {
 }
 UNIT_POWER_FREQUENT = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 BuffAnchor = <unnamed> {
 }
 __elements = <table> {
 }
 PLAYER_UPDATE_RESTING = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\restingindicator.lua:58
 Castbar = <unnamed> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 UNIT_MAXHEALTH = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\health.lua:177
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\combatindicator.lua:58
 UNIT_FLAGS = <table> {
 }
 UNIT_FACTION = <table> {
 }
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 Health = <unnamed> {
 }
 artwork = <unnamed> {
 }
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 UNIT_POWER_BAR_HIDE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\raidtargetindicator.lua:62
 PLAYER_TARGET_CHANGED = <function> defined @Interface\AddOns\SpartanUI\core\SUF.lua:236
 UNIT_CONNECTION = <table> {
 }
 Debuffs = <unnamed> {
 }
 Portrait = <unnamed> {
 }
 SmoothBar = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_Smooth.lua:17
 GROUP_ROSTER_UPDATE = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:466
 RaidTargetIndicator = <unnamed> {
 }
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:291
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:434
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:353
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\combatindicator.lua:58
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:329
 Level = <unnamed> {
 }
 UNIT_AURA = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\auras.lua:306
 UNIT_SPELLCAST_START = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:107
 PORTRAITS_UPDATED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\portrait.lua:87
 PvPIndicator = <unnamed> {
 }
 ClassPower = <table> {
 }
 Buffs = <unnamed> {
 }
 LeaderIndicator = <unnamed> {
 }
 mover = <unnamed> {
 }
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:213
 ThreatIndicator = <unnamed> {
 }
 ColorUpdate = <function> defined @Interface\AddOns\SpartanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:138
 RestingIndicator = <unnamed> {
 }
 Name = <unnamed> {
 }
 Power = <unnamed> {
 }
 SUI_RaidGroup = <unnamed> {
 }
 CombatIndicator = <unnamed> {
 }
 style = "SUI_PlayerFrames_Classic"
 UNIT_MODEL_CHANGED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\portrait.lua:87
}
event = "PLAY
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Adapt, v2.3.0-classic
  AtlasLootClassic, vv1.1.7-beta1
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.4
  Bartender4, v4.8.4
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  BrightleafNameplateClassColors, v1.0
  ChatLinkIcons, v2.0
  ClassicAuraDurations, v
  ClassicCastbars, vv1.0.2
  ClassicCastbarsOptions, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  FiveSecondRule, v1.1
  HideRaidManager, v1.0
  Informant, v8.2.6374 (SwimmingSeadragon)
  OmniCC, v8.1.1
  Prat30, v3.2.30
  Prat30Libraries, v
  Questie, v4.0.12 BETA
  QuestLogEx, v1.2
  SpartanUI, v5.2.5
  SpartanUIArtwork, v5.2.5
  SpartanUIFilmEffects, v5.2.5
  SpartanUIPartyFrames, v5.2.5
  SpartanUIPlayerFrames, v5.2.5
  SpartanUIRaidFrames, v5.2.5
  SpartanUISpinCam, v5.2.5
  SpartanUIStyleFel, v5.2.5
  SpartanUIStyleMinimal, v5.2.5
  SpartanUIStyleTransparent, v5.2.5
  SpartanUIStyleWar, v5.2.5
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VendorPrice, v1.1.4
  WeaponSwingTimer, v4.0.2
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=5a3)

![Wow_gAZyAOs5Ym](https://user-images.githubusercontent.com/8709379/64056537-35d10580-cb94-11e9-997b-a5c998976a9e.jpg)

**Comment by Wutname1** [comment]
Fixed in https://github.com/Wutname1/SUF/commit/ad79b5331a07f4a44e109aad92aa4d98d9da9018
