### ISSUE TITLE
Spartan UI scale of entire game too big

### ISSUE THREAD

**Issue by niceasbryan** [Wutname1/SpartanUI#211]
Scaling of all the menus, map, namplates etc. are too big. Trying to scale it down. Seems like its to scaling everythinng to my 1080 monitor.

**Comment by Wutname1** [comment]
Can you post a screenshot?

**Comment by niceasbryan** [comment]
Firgured it our finally. thanks for responding. For those of you who may have same problem the solution is under System>Advanced>UI Scale slider at the bottom. make sure to check it and change it to what works for you.
