### ISSUE TITLE
Integration with RealMobHealth

### ISSUE THREAD

**Issue by IAmDragon** [Wutname1/SpartanUI#212]
Title. Would be really nice to stop seeing "100/100" when I have an addon for that

**Comment by Wutname1** [comment]
This is planned for SUI 6.0

With unitframes being redesigned making the needed changed in 5.X would just slow everything else down.

**Comment by draknyte1** [comment]
Could you insert the relevant few lines of code into the target getHealth() getter? If it can already return a value, it should be deasily doable to add in something like this, right? Really the most major place beyond the tooltip.

```
-- Borrowed this from another addon as an example.
		if RealMobHealth and RealMobHealth.GetUnitHealth then 
			unit.health, unit.healthmax = RealMobHealth.GetUnitHealth(unitid)
		else
			unit.health = UnitHealth(unitid) or 0
			unit.healthmax = UnitHealthMax(unitid) or 1
		end
```
