### ISSUE TITLE
Spartan UI Castbar error

### ISSUE THREAD

**Issue by m3mphis2019** [Wutname1/SpartanUI#216]
Message: ...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:440: attempt to call upvalue 'UnitChannelInfo' (a nil value)
Time: Sun Sep  1 18:26:37 2019
Count: 1
Stack: ...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:440: attempt to call upvalue 'UnitChannelInfo' (a nil value)
...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:440: in function <...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:434>
(tail call): ?

Locals: self = SUI_playerFrame {
 0 = <userdata>
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\portrait.lua:87
 TextUpdate = <function> defined @Interface\AddOns\SpartanUI_PlayerFrames\scripts\FrameStyle_Classic.lua:97
 PLAYER_UPDATE_RESTING = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\restingindicator.lua:58
 __tags = <table> {
 }
 PLAYER_ENTERING_WORLD = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\SUF.lua:196
 ComboPoints = <unnamed> {
 }
 SUI_ClassIcon = <unnamed> {
 }
 UNIT_SPELLCAST_FAILED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:183
 unitEvents = <table> {
 }
 PARTY_LEADER_CHANGED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\leaderindicator.lua:59
 UNIT_PET = <function> defined @Interface\AddOns\SpartanUI\core\SUF.lua:236
 UNIT_HEALTH_FREQUENT = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\health.lua:177
 StatusText = <unnamed> {
 }
 GroupRoleIndicator = <unnamed> {
 }
 UNIT_POWER_FREQUENT = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 BuffAnchor = <unnamed> {
 }
 __elements = <table> {
 }
 Castbar = <unnamed> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 UNIT_MAXHEALTH = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\health.lua:177
 PLAYER_REGEN_DISABLED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\combatindicator.lua:58
 UNIT_FLAGS = <table> {
 }
 UNIT_FACTION = <table> {
 }
 UNIT_MAXPOWER = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 Health = <unnamed> {
 }
 artwork = <unnamed> {
 }
 UNIT_DISPLAYPOWER = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 UNIT_POWER_BAR_HIDE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\power.lua:247
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\raidtargetindicator.lua:62
 PLAYER_TARGET_CHANGED = <function> defined @Interface\AddOns\SpartanUI\core\SUF.lua:236
 UNIT_CONNECTION = <table> {
 }
 Debuffs = <unnamed> {
 }
 Portrait = <unnamed> {
 }
 SmoothBar = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_Smooth.lua:17
 GROUP_ROSTER_UPDATE = <table> {
 }
 UNIT_SPELLCAST_CHANNEL_STOP = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:466
 RaidTargetIndicator = <unnamed> {
 }
 unit = "player"
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:291
 UNIT_SPELLCAST_CHANNEL_UPDATE = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:434
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:353
 PLAYER_REGEN_ENABLED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\combatindicator.lua:58
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:329
 Level = <unnamed> {
 }
 UNIT_AURA = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\auras.lua:306
 UNIT_SPELLCAST_START = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:107
 PORTRAITS_UPDATED = <function> defined @Interface\AddOns\SpartanUI\libs\SUF\elements\portrait.lua:87
 PvPIndicator = <unnamed> {
 }
 ClassPower = <table> {
 }
 Buffs = <unnamed> {
 }
 LeaderIndicator = <unnamed> {
 }
 mover = <unnamed> {
 }
 UNIT_SPELLCA

**Comment by Wutname1** [comment]
What version of spartanui are you running

**Comment by IllyaMyshakov** [comment]
I'm getting a similar error when I cast Drain Life on my Warlock.

(using latest versions available through Twitch Client App)
SUI Version: 5.2.6
SUI Build: 505
Bartender4 version: 4.8.5

**Comment by Wutname1** [comment]
Fixed in SUF: Wutname1/SUF@6eaaebf
