### ISSUE TITLE
Show / Hide Buffs/De-Buffs

### ISSUE THREAD

**Issue by kingchenc** [Wutname1/SpartanUI#218]
Is there a option that we can show or hide or what we want for buffs over the player, target, target bars?

So, is there too a option to disable blizzard buffs/debuffs?

And last, the timer is too big, need resize option pls

**Comment by Wutname1** [comment]
> Is there a option that we can show or hide or what we want for buffs over the player, target, target bars?

Yes but it depends on the skin you are using. SUI 6.0 will fix the fragmentation and give you alot more customization

> So, is there too a option to disable blizzard buffs/debuffs?

No, Blizzard does not allow addons to cancel some buffs. As such limiting you to only having the buffs on the player frame would leave you unable to cancel buffs sometimes. (usually the worst times)



>And last, the timer is too big, need resize option pls

 This is part of a blizzard timer ill see what i can do with the 6.0 rewrite

**Comment by Shinrai** [comment]
You can however impose the blizzard buffs over any other adding buff display then set their alpha to 0. Basically making the right click available cancel available. The down side being that you can only do this to one buff display.
