### ISSUE TITLE
Elite Graphic

### ISSUE THREAD

**Issue by Krysia1979** [Wutname1/SpartanUI#22]
Are you guys going to add or is there already an option for an elite graphic on the target frame?

**Comment by Wutname1** [comment]
All skins indicate an elite, but in their own way some add a gold background some add the normal gold dragon. What skin are you using?

**Comment by Krysia1979** [comment]
Currently using Fel

**Comment by Wutname1** [comment]
Fel Displays an Elite by adding a Gold Gradient to entire frame, this puts the most noticeable spot is on the bottom behind the name and behind the portrait. 

![wowscrnshot_071118_100851](https://user-images.githubusercontent.com/704321/42581603-c4d9aef6-84f2-11e8-9045-6f908707b035.jpg)
