### ISSUE TITLE
MobInfo 2

### ISSUE THREAD

**Issue by kingchenc** [Wutname1/SpartanUI#220]
Is there support coming for mobinfo 2?

**Comment by Wutname1** [comment]
Yes in 6.0

**Comment by Wutname1** [comment]
Sorry I thought this was a mob health. I will have to look into mobinfo

**Comment by kingchenc** [comment]
Real Mob Info and Mob Info 2 is a bit different, both Addons not working with Spartan Gui, i see you have Real Mob Info in 6.0, hope Mob Info 2 too <3
