### ISSUE TITLE
SpartanUI Classic with RealMobHealth

### ISSUE THREAD

**Issue by Stewioie** [Wutname1/SpartanUI#227]
I use RMB addon for target health instead of percentage, but SpartanUI still shows 100 for all npc and players
![WoWScrnShot_090319_180200](https://user-images.githubusercontent.com/43112534/64189670-0c0a2e00-ce75-11e9-84fe-f6e1fa2a4ae0.jpg)

**Comment by Wutname1** [comment]
#212 - Duplicate
