### ISSUE TITLE
Vanilla Party Members/Info Slide-across

### ISSUE THREAD

**Issue by draknyte1** [Wutname1/SpartanUI#228]
Just Curious if this should be hidden in Classic?

Using SUI 5.2.3

![image](https://user-images.githubusercontent.com/3060479/64189725-c5b0d100-ce6c-11e9-8dbe-733a1590b69f.png)
![image](https://user-images.githubusercontent.com/3060479/64189739-cb0e1b80-ce6c-11e9-8efb-9bbb59986b50.png)

**Comment by Wutname1** [comment]
Raid icons are possible in classic, that is a blizzard window.

**Comment by draknyte1** [comment]
Yeah, but shouldn't it be hidden when using the SpartUI party-frames module?
That's my query here. It clips inside SUI stuff and looks disgusting.
