### ISSUE TITLE
Disable character frames not saving

### ISSUE THREAD

**Issue by glitchi256** [Wutname1/SpartanUI#229]
Im new to addons so bear with me. The frames that show your character health/portrait, as well as enemy ones, ive disabled in order to use a HUD style UI for combat and reduce screen clutter. It disables them, but whenever I reload the UI or restart the game this setting isnt saving and they come back, even though in Spartan UI they are shown as unchecked. Checking/unchecking again makes them disappear again.

**Comment by Wutname1** [comment]
#222  - Duplicate
