### ISSUE TITLE
Minimap

### ISSUE THREAD

**Issue by MadJack71** [Wutname1/SpartanUI#230]
![Снимок3423](https://user-images.githubusercontent.com/54885814/64237226-9cdc1a80-cf04-11e9-885d-d657ea059b8b.PNG)
How can I hide map in the corner?

**Comment by Wutname1** [comment]
Looks like an error is keeping the minimap module from loading properly. 

Turn on  LUA errors with '/console scriptErrors 1'
Once errors are on you can /reload and see if any errors popup
If you get more than 1 error i would recommend installing Bugsack and Bug grabber.
BugSack - https://www.curseforge.com/wow/addons/bugsack
BugGrabber -  https://www.curseforge.com/wow/addons/bug-grabber
These will put the errors into a bag icon on your minimap and make them less annoying.

**Comment by phutsler** [comment]
I have this same issue, but there are no errors being thrown by SUI itself.  Just a few from other mods.  My concoction of mods weirdly works just fine on my secondary computer, as well.

Though, it does seem like the Minimap module is simply not loading.  The options for it are completely absent under Modules in SUI's settings.
![SUI Settings](https://user-images.githubusercontent.com/16967985/64442889-4ef71c00-d096-11e9-8953-3a5ed27fe851.JPG)

**Comment by phutsler** [comment]
So, I'm actually throwing no errors at all.  I reverted the couple mods that had errors to previous versions, which fixed all their errors.  Still no Minimap module in SUI, even with no errors to speak of.  :(

**Comment by phutsler** [comment]
I've got the same problem.  Here are the Errors I'm being thrown when I have the Minimap module enabled:

`Message: Interface\AddOns\SpartanUI\components\Minimap.lua:231: Minimap:SetPoint(): Wrong object type for function
Time: Fri Sep  6 11:21:44 2019
Count: 1
Stack: Interface\AddOns\SpartanUI\components\Minimap.lua:231: Minimap:SetPoint(): Wrong object type for function
[C]: in function `SetPoint'
Interface\AddOns\SpartanUI\components\Minimap.lua:231: in function <Interface\AddOns\SpartanUI\components\Minimap.lua:169>
[C]: ?
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function `EnableAddon'
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:693: in function <Interface\FrameXML\UIParent.lua:658>

Locals: <none>`

`Message: Interface\AddOns\SpartanUI\components\Minimap.lua:122: attempt to index field 'ZoneText' (a nil value)
Time: Fri Sep  6 11:21:44 2019
Count: 1
Stack: Interface\AddOns\SpartanUI\components\Minimap.lua:122: attempt to index field 'ZoneText' (a nil value)
Interface\AddOns\SpartanUI\components\Minimap.lua:122: in function `ShapeChange'
...erface\AddOns\SpartanUI_Style_Fel\Module-Artwork.lua:342: in function `MiniMap'
...erface\AddOns\SpartanUI_Style_Fel\Module-Artwork.lua:253: in function `EnableArtwork'
Interface\AddOns\SpartanUI_Style_Fel\Style.lua:56: in function <Interface\AddOns\SpartanUI_Style_Fel\Style.lua:41>
[C]: ?
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:70: in function <...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:527: in function `EnableAddon'
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:540: in function `EnableAddon'
...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:620: in function <...\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:353: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:424: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:693: in function <Interface\FrameXML\UIParent.lua:658>

Locals: <none>`
