### ISSUE TITLE
Erro with Drain Life/Mana/Soul Warlock

### ISSUE THREAD

**Issue by maylersaid** [Wutname1/SpartanUI#231]
Message: ...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:440: attempt to call upvalue 'UnitChannelInfo' (a nil value)
Time: Wed Sep  4 09:31:31 2019
Count: 2
Stack: ...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:440: attempt to call upvalue 'UnitChannelInfo' (a nil value)
[C]: ?
...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:440: in function <...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:434>
(tail call): ?

**Comment by Wutname1** [comment]
Fixed in SUF: 6eaaebf60d7de3a358bc4b9fcca9b0122fad5492
