### ISSUE TITLE
Classic - Hunter - Pet Happiness

### ISSUE THREAD

**Issue by MidnightJay** [Wutname1/SpartanUI#233]
I've searched in the options along with bartender and cannot seem to find a spot to turn on the option for pet happiness for hunters to determine when the pet needs to be fed.

Can you advise where this option is located so I can use this amazing UI for my hunter.

Thanks!

**Comment by Wutname1** [comment]
What skin are you using it should be on your pets frame

**Comment by MidnightJay** [comment]
I've tried a few (War one currently) and it doesn't show it anywhere on the pet frame that I can find, I disable the UI and it shows just fine.

Do you have a screenshot of where it should be located and maybe that will help me?

Thanks!

**Comment by Wutname1** [comment]
It should be on the left side of all the frames 
![image](https://user-images.githubusercontent.com/704321/64371151-835ecf80-cfe5-11e9-9955-c339bdc6e63a.png)

Addition ref: https://github.com/Wutname1/SpartanUI/commit/ae34c8b0613a87bf291b59e416172b1bb4edd970

**Comment by Wutname1** [comment]
Do you have your pet out when you load the game? Summon your pet and /reload see if it appears i wonder if there is a bug relating to it updating.

**Comment by MidnightJay** [comment]
I don't have the happiness icon at all.  Yes it's out when loading the game, then I stable, reload ui and still have nothing.  The icon is missing all together.

I even tried stabling the pet, logging out, logging back in and getting the pet out of the stable and no change

![image](https://user-images.githubusercontent.com/54946502/64390967-21619280-d004-11e9-96d6-92ab836c26bf.png)

**Comment by Wutname1** [comment]
If one of you are up to helping me test (No hunter atm)  I need a hunter to update a file:
https://raw.githubusercontent.com/Wutname1/oUF_PetHappiness/master/oUF_PetHappiness.lua 
That file needs to replace your current one at:
`World of Warcraft\_classic_\Interface\AddOns\SpartanUI\libs\oUF_PetHappiness`

**Comment by MidnightJay** [comment]
updated the file and no change unfortunately .... happiness icon still doesn't show up

**Comment by MidnightJay** [comment]
Let me know if you want me to try testing anything else.  

Note I've disabled everything expect for SUI and Bartender and the issue occurs.  If you need to redo a complete package with a test name I can install and test it too if you need to.

thanks for taking the time to fix this, SUI is by far my favorite ... possibly ever.

**Comment by AlwaysOnTheHunt** [comment]
Hello.

I have the same issue on my hunter. :( The happiness icon on the pet frame won't show at all. Tried to look at the settings, but no results. I tried to replace the updated file, as MidnightJay where instructed to, and it didn't work sadly. :(  Really like SpartanUI, so i hope it will be fixed. 
Regards! :)

**Comment by Wutname1** [comment]
So I leveled a hunter to 10 today and I am unable to replicate. 

The happiness icon appears on the left of the pet frame on all the skins for me. https://imgur.com/a/BaV2JbK


Try putting this in your chat for me:
`/script print(SUI_petFrame.PetHappiness)`
You should get a output in your chat of `table: <guid>`
Example:
![image](https://user-images.githubusercontent.com/704321/64558928-ad2c3500-d30a-11e9-97a2-84c53b0161a2.png)

- If you get Nil then please run `/script print(SUI.IsClassic)` let me know if you get true or false. 
- If you get a table then please run `/script SUI_petFrame.PetHappiness:Show()` and let me know if it appears

**Comment by StingMcRay** [comment]
When i run the script i get this output : 
![afbeelding](https://user-images.githubusercontent.com/18048706/64563186-04ec8f80-d34f-11e9-9978-f595b69e56ee.png)

**Comment by MidnightJay** [comment]
I get:  table: 00000235A2A78F10

**Comment by Wutname1** [comment]
You will always get a diffrent table ID (it is random.) Does /script SUI_petFrame.PetHappiness:Show() make it appear?

**Comment by MidnightJay** [comment]
Oh sorry missed that, I was checking while at work lol

So I did that part and no change sadly

![image](https://user-images.githubusercontent.com/54946502/64571073-df945d00-d31f-11e9-9fdf-c941b40e41ec.png)

**Comment by MidnightJay** [comment]
So I was hoping it was due to the updated oUF_PatHappiness.lua file you gave me so I installed the original one again that came with the download and still no change.

I'm at a loss

**Comment by Wutname1** [comment]
Try these 3 commands me know what happens:

`/script print(SUI_petFrame.PetHappiness:IsVisible())`
`/script SUI_petFrame.PetHappiness:Show()`
`/script print(SUI_petFrame.PetHappiness:IsVisible())`

We are looking to see if the state is changing between true & false after running the Show() command.

**Comment by MidnightJay** [comment]
Just ran the 3 above scripts and the both values return as 'true'
![image](https://user-images.githubusercontent.com/54946502/64650210-e2548800-d3db-11e9-99ed-6d56a9f97f9c.png)

**Comment by Wutname1** [comment]
😢 
ok lets try manually clearing where it is and setting it to be below the pet frame. 
`/script SUI_petFrame.PetHappiness:ClearAllPoints()`
`/script SUI_petFrame.PetHappiness:SetPoints('TOP', SUI_petFrame, 'BOTTOM', 0, -10)`

**Comment by MidnightJay** [comment]
Tried that and no change.  Value is still showing true

**Comment by Dhubhghall** [comment]
Hi,
as of today and the new release i have the same problem. Pet happiness wont show and i tried everything above. I reverted back to the old release and pet happiness is still gone....

**Comment by Road-block** [comment]
Does it show if you move it outside of the petframe? It might be a strata issue.

**Comment by Wutname1** [comment]
@Road-block that was the idea behind the above script commands i posted.

Would anyone having this issue be willing to give the latest 6.0 Alpha a try for me? https://www.curseforge.com/wow/addons/spartan-ui/files/2813567

**Comment by Thorsteenster** [comment]
Any updates on this?
I just installed on Classic for my Hunter and pet happiness isn't showing after following above steps.
Resolution or move onto another UI AddOn? (First time UI AddOn user...)

**Comment by MidnightJay** [comment]
Hey,

It's been working fine since your last update. Good job!

**Comment by Thorsteenster** [comment]
Ha, I'll have to DL the latest, I got mine last week just before the latest release. TY!
