### ISSUE TITLE
"OnLoad" Error?

### ISSUE THREAD

**Issue by icyzephyr** [Wutname1/SpartanUI#239]
I get this error when loading WoW BfA.  I also seem to lose positioning of my mini-map from bottom center to upper right corner anytime I zone or exit a vehicle, not sure if they're related, but its certainly annoying :( I have to Reload my UI to get it back to its proper bottom center positioning.

Date: 2019-09-08 10:15:00
ID: 1
Error occured in: Global
Count: 1
Message: [string "*:OnLoad"] line 51:
   attempt to compare number with nil
Debug:
   [C]: ?
   [string "*:OnLoad"]:51:
      [string "*:OnLoad"]:37
   [string "*:OnLoad"]:81:
      [string "*:OnLoad"]:70
Locals:

AddOns:
  MoncaiCompare, v7.2.0
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Altoholic, vr191
  AzeritePowerWeights, v8.2.8
  AzeriteTooltip, v2.0.6
  Bagnon, v8.2.0
  BagnonChampion, v3.0
  Bartender4, v4.8.7
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  DataStore, vr66
  DataStoreAchievements, vr48
  DataStoreAgenda, vr30
  DataStoreAuctions, vr51
  DataStoreCharacters, vr44
  DataStoreContainers, vr60
  DataStoreCrafts, vr83
  DataStoreCurrencies, vr39
  DataStoreGarrisons, vr25
  DataStoreInventory, vr54
  DataStoreMails, vr53
  DataStorePets, vr45
  DataStoreQuests, vr47
  DataStoreReputations, vr44
  DataStoreSpells, vr33
  DataStoreStats, vr32
  DataStoreTalents, vr62
  DugisGuideViewerZ, v8.765
  EasyDeleteConfirm, v
  GTFO, v4.49.1
  Informant, v8.2.6374 (SwimmingSeadragon)
  ItemLinkLevel, v1.8
  LeatrixPlus, v8.2.07
  MapCoords, v0.30
  MasterPlanA, vA
  Molinari, v80200.63-Release
  ParagonReputation, v1.24
  Postal, vv3.6.0
  Recount, vv8.2.0c
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v5.2.8
  SpartanUIArtwork, v5.2.8
  SpartanUIPlayerFrames, v5.2.8
  SpartanUIStyleFel, v5.2.8
  SpartanUIStyleMinimal, v5.2.8
  SpartanUIStyleTransparent, v5.2.8
  SpartanUIStyleWar, v5.2.8
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TalkingHeadFrameSettings, v7.0.3.15
  Titan, v5.18.2.80200
  TitanBag, v5.18.2.80200
  TitanClock, v5.18.2.80200
  TitanGold, v5.18.2.80200
  TitanRepair, v5.18.2.80200
  TomCats, v1.3.6
  TomCatsMechagon, v1.3.10
  TradeSkillMaster, vv4.8.7
  TradeSkillMasterAppHelper, vv4.0.4
  WeakAuras, v2.14.6
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v8.2.0.80200 <none>
  (ck=64e)

**Comment by Wutname1** [comment]
Does the issue occur if you disable everything other than bartender and spartanui?

Due to the lack of info in the error message if it does still happen please try a DB reset `/suihelp > Reset Profile`
