### ISSUE TITLE
Nameplates: Show castbar

### ISSUE THREAD

**Issue by Caerdon** [Wutname1/SpartanUI#24]
In a group of mobs, I have no idea who is casting what right now without the ability to see casts.

**Comment by Wutname1** [comment]
Already planned. Leaving open for tracking.

**Comment by Wutname1** [comment]
Initial Support added in a50c8e2f1976805da3458e5328db11e5c6a1e9b8 and Released in 4.6.3

Cast related items still to be added: 
- Castbar Text (will need to auto increase castbar size if on, default will be off)
- Cast Interruptible indicator

**Comment by Wutname1** [comment]
Castbar Text added in 2d1f88a867222a5d8f2edacd1425278cab2d1b89
