### ISSUE TITLE
List of Bugs and Enhancements

### ISSUE THREAD

**Issue by karai17** [Wutname1/SpartanUI#242]
Installed SpartanUI today, liking it for the most part but having some trouble with a few things. I've made a list instead of opening a bunch of individual issues. I'll add to this list as I continue to explore.

## Bugs

* [x] Despite my buff options all being disabled, the blizzard buff bar won't go away.

## General

* [ ] Buffs and Debuffs are on the same row? Would be nice to be able to separate them
* [ ] More text display options for Unit Frames, perhaps the ability to define the data you want? Example: I like having longer health/mana bars that show the player's current and max HP/MP on the left, and then a deficit on the right:
`[ 555 / 999       -444 ][ 55% ]`
* [ ] Integrated buff timers for other players or mobs

## Party Frames

![image](https://user-images.githubusercontent.com/590332/64668117-c03a2480-d432-11e9-854f-3235df9dc062.png)

Here is a list of issues I'm having with Party Frames:

* [ ] Party Frames are too close (buffs overlap other frames) and there is no option to spread them
* [ ] I can't find any way to make them not semi-transparent when a party member is far away
* [ ] Ability to stack party frames horizontally instead of just vertically would be super cool~
* [ ] buffs and debuffs should list after the pvp icon, not over top of it

**Comment by Wutname1** [comment]
>  Despite my buff options all being disabled, the blizzard buff bar won't go away.

SUI only lets you move the blizz buff bar. I have no plans to change this as blizzard does not allow addons to cancel some buffs (mainly in combat) and this can cause issues if you need to cancel a shapeshift buff as you will be unable to from the buffs on your player frame.

Most of your other items will be covered in SUI 6.0 here is the new text system as it is at the moment:

![image](https://user-images.githubusercontent.com/704321/64669854-b6132880-d428-11e9-8cf4-606b53ec1c11.png)


https://youtu.be/lWypMBZobhk?t=158

**Comment by karai17** [comment]
ooh, very cool!

would it be possible to add an option to hide the blizz bar, off by default?
