### ISSUE TITLE
Minimap Tracking

### ISSUE THREAD

**Issue by karai17** [Wutname1/SpartanUI#243]
When I `alt+Z` to hide UI and then return the UI, I get this error and the minimap gets a weird border until I `/reload`

![image](https://user-images.githubusercontent.com/590332/64831149-aae80600-d5aa-11e9-8fc3-df381c502e15.png)

Date: 2019-09-12 22:12:13
ID: 1
Error occured in: Global
Count: 1
Message: ...\SpartanUI_Artwork\Themes\Classic\Module-Minimap.lua line 50:
   attempt to index global 'MiniMapTracking' (a nil value)
Debug:
   ...\SpartanUI_Artwork\Themes\Classic\Module-Minimap.lua:50:
      ...\SpartanUI_Artwork\Themes\Classic\Module-Minimap.lua:32
   ...\SpartanUI_Artwork\Themes\Classic\Module-Minimap.lua:71:
      ...\SpartanUI_Artwork\Themes\Classic\Module-Minimap.lua:64
   [C]: ?
   [C]: ?
   [C]: SetUIVisibility()
   [string "TOGGLEUI"]:4:
      [string "TOGGLEUI"]:1
Locals:
shape = "square"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "ADD"
(*temporary) = <userdata>
(*temporary) = "OVERLAY"
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "attempt to index global 'MiniMapTracking' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.9
  Bartender4, v4.8.7
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicThreatMeter, v1.06
  DBMCore, v1.13.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  HealBot, v1.13.2.0
  HealBotTips, v1.13.2.0
  Informant, v8.2.6374 (SwimmingSeadragon)
  MonkeyBuddy, v
  MonkeyLibrary, v
  MonkeyQuest, v
  MonkeyQuestLog, v
  OmniCC, v8.2.4
  QuestFrameFixer, v1.1.1
  QuestIconDesaturation, v3.1
  Questie, v4.0.18 BETA
  RealMobHealth, v2.9
  SimpleMap, v1.2.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v5.2.9
  SpartanUIArtwork, v5.2.9
  SpartanUIFilmEffects, v5.2.9
  SpartanUIPartyFrames, v5.2.9
  SpartanUIPlayerFrames, v5.2.9
  SpartanUIRaidFrames, v5.2.9
  SpartanUISpinCam, v5.2.9
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.0.5.11302
  TitanClassicAmmo, v1.0.5.11302
  TitanClassicBag, v1.0.5.11302
  TitanClassicClock, v1.0.5.11302
  TitanClassicGold, v1.0.5.11302
  TitanClassicLocation, v1.0.5.11302
  TitanClassicLootType, v1.0.5.11302
  TitanClassicPerformance, v1.0.5.11302
  TitanClassicRepair, v1.0.5.11302
  TitanClassicVolume, v1.0.5.11302
  TitanClassicXP, v1.0.5.11302
  WideQuestLog, v
  WideQuestLogLevels, v
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=6e6)

**Comment by karai17** [comment]
v5.2.9-classic on curseforge is showing as latest.

**Comment by Wutname1** [comment]
Sorry i missread the error message this is an actual error in the classic skin only. I thought it was referring to the minimap module in Classic wow.
