### ISSUE TITLE
Classic - party frame issues

### ISSUE THREAD

**Issue by fathermaxi** [Wutname1/SpartanUI#245]
Sometimes I have to reload ui for party frames to appear and since I started using the minimal skin I don't see player name/hp/mp on them
![Screenshot (210)](https://user-images.githubusercontent.com/55289039/64874631-bb03f200-d64b-11e9-8fb7-d3fcbcf5d08a.png)
Here's the error code, what am I doing wrong?

Date: 2019-09-13 17:20:11
ID: 1
Error occured in: Global
Count: 3
Message: ...ns\SpartanUI_PartyFrames\scripts\Global-Features.lua line 115:
   attempt to call method 'RegisterForClicks' (a nil value)
Debug:
   [C]: ?
   [C]: ?
   ..\FrameXML\RestrictedFrames.lua:641:
      ..\FrameXML\RestrictedFrames.lua:640
   ..\FrameXML\RestrictedFrames.lua:779: CallMethod()
   [string "		local header = self:GetParent()..."]:51:
      [string "		local header = self:GetParent()..."]:1
   (tail call): ?
   [C]: ?
   ..\FrameXML\RestrictedExecution.lua:484:
      ..\FrameXML\RestrictedExecution.lua:447
   ..\FrameXML\SecureGroupHeaders.lua:116:
      ..\FrameXML\SecureGroupHeaders.lua:110
   ..\FrameXML\SecureGroupHeaders.lua:166:
      ..\FrameXML\SecureGroupHeaders.lua:123
   ..\FrameXML\SecureGroupHeaders.lua:488:
      ..\FrameXML\SecureGroupHeaders.lua:387
   [C]: Show()
   ...ddOns\SpartanUI_PartyFrames\scripts\Spawn-Frames.lua:100: UpdateParty()
   ...ddOns\SpartanUI_PartyFrames\scripts\Spawn-Frames.lua:132:
      ...ddOns\SpartanUI_PartyFrames\scripts\Spawn-Frames.lua:128
   [C]: SetCVar()
   SpartanUI\libs\SUF\blizzard.lua:122: DisableBlizzard()
   SpartanUI\libs\SUF\SUF.lua:781: Spawn()
   ...ns\SpartanUI_Style_Transparent\Module-UnitFrames.lua:1396: PlayerFrames()
   ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:307:
      ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:300
   [C]: ?
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:540: EnableAddon()
   ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:620:
      ...face\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:605
   [C]: LoadAddOn()
   ..\FrameXML\UIParent.lua:353: UIParentLoadAddOn()
   ..\FrameXML\UIParent.lua:380: CombatLog_LoadUI()
   ..\FrameXML\UIParent.lua:695:
      ..\FrameXML\UIParent.lua:658
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.45.01
  AtlasClassicWoW, vv1.45.00
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.7-2-gb6977ae
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  Details, v
  DetailsTinyThreat, v
  Peggle, v2.2.3
  Questie, v4.0.13 BETA
  SexyMap, vv3-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v5.2.9
  SpartanUIArtwork, v5.2.9
  SpartanUIFilmEffects, v5.2.9
  SpartanUIPartyFrames, v5.2.9
  SpartanUIPlayerFrames, v5.2.9
  SpartanUIRaidFrames, v5.2.9
  SpartanUISpinCam, v5.2.9
  SpartanUIStyleFel, v5.2.9
  SpartanUIStyleMinimal, v5.2.9
  SpartanUIStyleTransparent, v5.2.9
  SpartanUIStyleWar, v5.2.9
  Stubby, v8.2.6376 (SwimmingSeadragon)
  VuhDo, v3.102
  VuhDoOptions, v3.102
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=48d)

**Comment by karai17** [comment]
I had an issue last night where one of my party members didn't show up in party until I reloaded UI. I am using the default skin.

**Comment by fathermaxi** [comment]
Yeah I reloaded ui more times than I can count it doesn't work. I checked the other party frame styles and minimal and transparent don't show names, hp and mp, classic works fine and fel looks like minimal so I can use that and it looks nice but it seems bugged. Also is there a way to remove the pet bar? Not the functional, bartender one but the visual, SpartanUI one?
