### ISSUE TITLE
OmniCC Support

### ISSUE THREAD

**Issue by karai17** [Wutname1/SpartanUI#248]
I have OmniCC installed so that I can see buff and debuff timers on enemies and party members but the timers aren't showing up on the SpartanUI Frames.

![image](https://user-images.githubusercontent.com/590332/65466526-7f301000-de35-11e9-8c25-13298b36bd1c.png)

**Comment by Wutname1** [comment]
OmniCC is supported but classic does not have buff timers for OmniCC to show you.

**Comment by karai17** [comment]
That's strange... Then how/why is OmniCC even supported in Classic?
