### ISSUE TITLE
/sui is not working in the game

### ISSUE THREAD

**Issue by zhangsux** [Wutname1/SpartanUI#25]
Hi. I'm a user who enjoys WOW in Korea. First, thank you for continuing to provide SpartanUI. 

Recently I installed the latest beta version (BFA-Beta-PrePatchRC). But I have confirmed that the /sui option is not working in the game. 

The launch option is the same in the interface settings. There is no such problem in version 4.4.0 that I am currently using

Is there any way to solve this problem?

**Comment by Wutname1** [comment]
Is the addon loaded at all? I just downloaded the zip and reinstalled it and it's functioning normally.

**Comment by zhangsux** [comment]
The installation was not a problem at all. Erase the interface folder and WTF folder and install only the SpartanUI beta version and the bartender4 but the /sui option is not working. 

Maybe this is a Korean problem? I'll try it again later when the full version comes out.

**Comment by Wutname1** [comment]
You don't need to delete the WTF folder. Addons go in the interface/Addons folder.

**Comment by zhangsux** [comment]
I'm playing now. I'll do what you say later.

**Comment by zhangsux** [comment]
Is the latest beta version 4.5.0? I decompressed file in the AdOn folder without delete the WTF folder. 

But I can't see the Main options window if i type "/SUI" in the chat window. /spin,  /sui version command is working. only /sui is not working.

**Comment by Wutname1** [comment]
Yes, the BFA-Beta version is only for the BFA beta servers.
