### ISSUE TITLE
Target HP bar WOW classic

### ISSUE THREAD

**Issue by hoffa009** [Wutname1/SpartanUI#254]
My target HP bar always shows 100HP regardless of characters actual HP.  When fighting, the HP damage doesnt match what you are actually doing.

**Comment by Wutname1** [comment]
Classic did not have exact health numbers #nochanges. Some addons do show you health numbers by doing the math for you (you hit the target for 50 and did X% of dmg). This is planned to be built into SpartanUI in 6.0. As of SUI 5.2.8 'Real Mob Health' is now supported and can be installed separately.
