### ISSUE TITLE
Artwork not staying clear after reload ui

### ISSUE THREAD

**Issue by Theutus1** [Wutname1/SpartanUI#257]
Two issues a new character cannot import from an older character without impacting the ui on both. Missing player frame on the new character, everything rearranged on the old. 

After changing the artwork to clear, it reloads as white and the error below pops up.

Date: 2019-10-12 12:46:12
ID: 4
Error occured in: Global
Count: 1
Message: ...terface\AddOns\SpartanUI_Style_Minimal\Framework.lua line 173:
   bad argument #1 to 'pairs' (table expected, got nil)
Debug:
   (tail call): ?
   [C]: pairs()
   ...terface\AddOns\SpartanUI_Style_Minimal\Framework.lua:173: SetColor()
   SpartanUI_Style_Minimal\Style.lua:95:
      SpartanUI_Style_Minimal\Style.lua:93
   [C]: ?
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:51:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49
   ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:843:
      ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664
   [C]: ?
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:72:
      ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70
   ...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:290: Fire()
   ...Libs\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:33:
      ...Libs\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:21
   ...Libs\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:67: opacityFunc()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:
None
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AccountantClassic, vv2.11.08.11302
  AtlasLootClassic, vv1.2.3
  AtlasLootClassicDungeonsAndRaids, vv1.2.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  Bartender4, v4.8.8
  BeanCounter, v8.2.6422 (SwimmingSeadragon)
  BiSTracker, v1.4 
  Details, v
  DetailsTinyThreat, v
  eCastingBar, v1.3.0
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  FishingBuddy, v0.6 Beta 1
  FiveSecondRule, v1.13
  Informant, v8.2.6374 (SwimmingSeadragon)
  Mapster, v1.8.5
  MoveAnything, v17.0.5
  NeatPlates, v1.13.2.38
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  Necrosis, v5.0
  OmniCC, v8.2.5
  Pawn, v2.3.7
  Prat30, v3.7.36
  Prat30Libraries, v
  Questie, v4.1.2 BETA 121 dff5a12
  RealMobHealth, v2.13
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SoulSpeak, v8.04-classic
  SpartanUI, v5.2.11
  SpartanUIArtwork, v5.2.11
  SpartanUIFilmEffects, v5.2.11
  SpartanUIPartyFrames, v5.2.11
  SpartanUIPlayerFrames, v5.2.11
  SpartanUIRaidFrames, v5.2.11
  SpartanUISpinCam, v5.2.11
  SpartanUIStyleFel, v5.2.11
  SpartanUIStyleMinimal, v5.2.11
  SpartanUIStyleTransparent, v5.2.11
  SpartanUIStyleWar, v5.2.11
  Spy, v1.0.9
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TBag, v1.13.2.3
  TitanClassic, v1.1.1.11302
  TitanClassicAmmo, v1.1.1.11302
  TitanClassicBag, v1.1.1.11302
  TitanClassicClock, v1.1.1.11302
  TitanClassicGold, v1.1.1.11302
  TitanClassicLocation, v1.1.1.11302
  TitanClassicLootType, v1.1.1.11302
  TitanClassicPerformance, v1.1.1.11302
  TitanClassicRecZone, v1.0.0.2
  TitanClassicRegen, v1.1.0.11302
  TitanClassicRepair, v1.1.1.11302
  TitanClassicVolume, v1.1.1.11302
  TitanClassicXP, v1.1.1.11302
  TomTom, vv11302-1.0.7
  TradeSkillMaster, vv4.8.14
  TradeSkillMasterAppHelper, vv4.0.5
  VendorPrice, v1.2.9
  WeakAuras, v2.15.2
  WeaponSwingTimer, v4.1.0
  WhatsTraining, v1.8.6
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=9dc)

**Comment by Wutname1** [comment]
> Two issues a new character cannot import from an older character without impacting the ui on both.

How are you trying to do this? Via the SUI setup wizard? I use it all the time and have never seen this.
