### ISSUE TITLE
Messy Party Frames

### ISSUE THREAD

**Issue by karai17** [Wutname1/SpartanUI#259]
![image](https://user-images.githubusercontent.com/590332/66729973-f77e6580-ee24-11e9-951a-1fb6f5e99dfb.png)

Is there any way to fix... this issue?

**Comment by karai17** [comment]
Is that a no, then?

**Comment by roweboy1974** [comment]
Yeah, I'm not liking this either. It's difficult if you are a healer to see through the buffs/debuffs.

**Comment by Wutname1** [comment]
There are some buff options in the settings, if you turn on onlyshow player that will resolve the issue. There will be more option in 6.0

**Comment by karai17** [comment]
![image](https://user-images.githubusercontent.com/590332/67360159-90a32f80-f53b-11e9-9b3a-46ec5a236140.png)

There is no option for only displaying player buffs, I already went looking for such an option. Perhaps I am truly blind and cannot see it?

**Comment by Wutname1** [comment]
nope guess it is missing from party options. Another case of the pre-6.0 frame being horibly fragmented and leading to poor customization. 

Try one of the other skins for party frames like war or fel.
