### ISSUE TITLE
Korean Font

### ISSUE THREAD

**Issue by echidna-kr** [Wutname1/SpartanUI#261]
can you update for korean font

2 Points!!!

first Font!

this is notosancjk-kr-regular font link

for 'Media' folder

https://drive.google.com/file/d/1b_QBDQfd5u3AsJNsbHkvVDhDNO_6g_A-/view?usp=sharing

second 'Core/FontHandler.lua'

--------------------------------------------
local FontFaces = {
	['SpartanUI'] = 'Cognosis',
	['Roboto'] = 'Roboto',
	['Roboto-Bold'] = 'Roboto Bold',
	['SUI4'] = 'NotoSans',
	['SUI4cn'] = 'NotoSans (zhCN)',
	['FrizQuadrata'] = 'Friz Quadrata',
	['ArialNarrow'] = 'Arial Narrow',
	['Skurri'] = 'Skurri',
	**['NotoSansCJKkr-Regular'] = 'Noto Sans CJK KR Regular',**
	['Morpheus'] = 'Morpheus'
}

-------------------------------------------
function SUI:GetFontFace(Module)
	if Module then
		if SUI.DB.font.Modules[Module].Face == 'SpartanUI' then
			return 'Interface\\AddOns\\SpartanUI\\media\\font-cognosis.ttf'
		elseif SUI.DB.font.Modules[Module].Face == 'SUI4' then
			return 'Interface\\AddOns\\SpartanUI\\media\\NotoSans-Bold.ttf'
		elseif SUI.DB.font.Modules[Module].Face == 'Roboto' then
			return 'Interface\\AddOns\\SpartanUI\\media\\Roboto-Medium.ttf'
		elseif SUI.DB.font.Modules[Module].Face == 'Roboto-Bold' then
			return 'Interface\\AddOns\\SpartanUI\\media\\Roboto-Bold.ttf'
		elseif SUI.DB.font.Modules[Module].Face == 'FrizQuadrata' then
			return 'Fonts\\FRIZQT__.TTF'
		elseif SUI.DB.font.Modules[Module].Face == 'Arial' then
			return 'Fonts\\ARIAL.TTF'
		elseif SUI.DB.font.Modules[Module].Face == 'ArialNarrow' then
			return 'Fonts\\ARIALN.TTF'
		elseif SUI.DB.font.Modules[Module].Face == 'Skurri' then
			return 'Fonts\\skurri.TTF'
		**elseif SUI.DB.font.Modules[Module].Face == 'NotoSansCJKkr-Regular' then
			return 'Interface\\AddOns\\SpartanUI\\media\\notosancjk-KR-Regular.ttf'**
		elseif SUI.DB.font.Modules[Module].Face == 'Morpheus' then
			return 'Fonts\\MORPHEUS.TTF'
		elseif SUI.DB.font.Modules[Module].Face == 'Custom' and SUI.DB.font.Path ~= '' then
			return SUI.DB.font.Path
		end
	end

	--Failsafe, no module should be undefined as of 5.0
	return 'Interface\\AddOns\\SpartanUI\\media\\Roboto-Bold.ttf'
end

please update~~~~

**Comment by Wutname1** [comment]
Font handler re-wrote in 6.2
