### ISSUE TITLE
Styles still aren't updating correctly... BT4 is installed and updated.

### ISSUE THREAD

**Issue by Dyaxler** [Wutname1/SpartanUI#262]
I'm using this build from CurseForge - SpartanUI - 20480ab (2019-10-17). To rule out an older version getting in the way I purged the older builds of SpartanUI from my Dev client. I like using the Classic skin but Player - Target - TargetTarget & I assume Party Frames are all blank and won't take a style. None of the other Styles are working either.

Is this a known issue?

![image](https://user-images.githubusercontent.com/17400948/67130448-28a8be00-f1b6-11e9-806b-43c819dd032f.png)

**Comment by Wutname1** [comment]
Yes, this is intended at this time. if you are going to run the alpha version of Sparta you I highly recommend joining the discord and selecting the alpha user role.
