### ISSUE TITLE
Raid Frames

### ISSUE THREAD

**Issue by karai17** [Wutname1/SpartanUI#264]
I have a couple issues with the Raid Frames:

1. There is no option to move them, only a button to reset their position. This means I'm stuck looking at the top-left corner of my screen instead of being able to drag the units to a different place.
1. The way that columns are defined don't provide any flexibility. For example, I have my column layout set to 8 columns, 5 units each, ordered by Group. Last night I was in an LBRS group with 6 people and the raid leader had divided us up into groups of 3, yet my frames were displaying as if Group 1 was full and Group 2 only had a single person. This was very confusing to me since our tank wasn't receiving my paladin aura yet showed up in my group. It wasn't until about half way through the run where I realized what happened and was able to resort the raid groups.

What I think would be a better design is for the "Group" option to replicate the Blizzard Raid Frames, or also have a Class option to create a raid frame column for each class. Class Sorting would be beneficial for paladin blessings and would also provide a more organized list of players for healing.

**Comment by Wutname1** [comment]
#1 You can move unitframes in SUI by holding alt and dragging. 
#2 has already been resolved in the 6.0 Alpha builds.

**Comment by karai17** [comment]
Thanks for the update. Are the 6.0 alpha builds relatively stable? Considering the variosu updates you've said will be in 6.0, I'd like to give it a go~
