### ISSUE TITLE
5.2 X beta1 error when loading character

### ISSUE THREAD

**Issue by Khiswow** [Wutname1/SpartanUI#266]
Hi,
I installed the latest beta and when I load a toon, I get this error :

Date: 2019-10-23 18:53:02
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua line 487:
   attempt to index local 'element' (a nil value)
Debug:
   ...rface\AddOns\SpartanUI\libs\SUF\elements\castbar.lua:487: enable()
   SpartanUI\libs\SUF\SUF.lua:124: EnableElement()
   SpartanUI\libs\SUF\SUF.lua:361:
      SpartanUI\libs\SUF\SUF.lua:276
   (tail call): ?
   SpartanUI\libs\SUF\SUF.lua:782: Spawn()
   ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:18: SUI_PlayerFrames_Classic()
   ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:305:
      ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:300
   [C]: ?
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:70:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:527: EnableAddon()
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:540: EnableAddon()
   Ace3\AceAddon-3.0\AceAddon-3.0.lua:620:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:605

**Comment by byaka** [comment]
same for me

**Comment by Wutname1** [comment]
I will have new beta up tomorrow was unable to get to it tonight.

**Comment by Wutname1** [comment]
Should be resolved as of  5.2.11-6-g4322709 (just posted) please let me know if it is not solved
