### ISSUE TITLE
UI minimap crash

### ISSUE THREAD

**Issue by Treaved** [Wutname1/SpartanUI#271]
Date: 2019-11-09 16:15:08
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\SpartanUI\components\Minimap.lua line 572:
   attempt to index field 'FadeIn' (a function value)
Debug:
   SpartanUI\components\Minimap.lua:572: update()
   SpartanUI\components\Minimap.lua:57:
      SpartanUI\components\Minimap.lua:53
Locals:
self = <table> {
 MinimapCoords = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:408
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 baseName = "SpartanUI"
 HideOptions = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:737
 Enable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 update = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:518
 EnableModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 IsModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 OnEnable = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:172
 defaultModuleLibraries = <table> {
 }
 ShapeChange = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:92
 SetupButton = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:466
 SetEnabledState = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 ModifyMinimapLayout = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:274
 enabledState = true
 BuildOptions = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:628
 OnInitialize = <function> defined @Interface\AddOns\SpartanUI\components\Minimap.lua:153
 moduleName = "Component_Minimap"
 GetName = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 IterateModules = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 name = "SpartanUI_Component_Minimap"
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 IsEnabled = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 SetDefaultModuleState = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 DisableModule = <function> defined @Interface\AddOns\Bagnon\common\Wildpants\libs\AceAddon-3.0\AceAddon-3.0.lua:350
}
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = MiniMapTrackingFrame {
 }
 2 = MiniMapMailFrame {
 }
 3 = MiniMapBattlefieldFrame {
 }
 4 = MinimapBackdrop {
 }
 5 = LibDBIcon10_AtlasLoot {
 }
 6 = LibDBIcon10_Bartender4 {
 }
 7 = LibDBIcon10_ClassicLFG_LDB {
 }
 8 = EnxMiniMapIcon {
 }
 9 = LibDBIcon10_GatherLiteMinimapIcon {
 }
 10 = QuestieFrameGroup {
 }
 11 = LibDBIcon10_MinimapIcon {
 }
 12 = TimeManagerClockButton {
 }
 13 = LibDBIcon10_VuhDo {
 }
 14 = QuestieFrame134 {
 }
 15 = QuestieFrame140 {
 }
 16 = QuestieFrame128 {
 }
 17 = QuestieFrame316 {
 }
 18 = QuestieFrame272 {
 }
 19 = QuestieFrame212 {
 }
 20 = QuestieFrame274 {
 }
 21 = QuestieFrame210 {
 }
 22 = QuestieFrame328 {
 }
 23 = QuestieFrame312 {
 }
 24 = QuestieFrame364 {
 }
 25 = QuestieFrame232 {
 }
 26 = QuestieFrame358 {
 }
 27 = QuestieFrame194 {
 }
 28 = QuestieFrame320 {
 }
 29 = QuestieFrame326 {
 }
 30 = QuestieFrame200 {
 }
 31 = QuestieFrame254 {
 }
 32 = QuestieFrame204 {
 }
 33 = QuestieFrame196 {
 }
 34 = QuestieFrame294 {
 }
 35 = QuestieFrame256 {
 }
 36 = QuestieFrame250 {
 }
 37 = QuestieFrame344 {
 }
 38 = QuestieFrame336 {
 }
 39 = QuestieFrame228 {
 }
 40 = QuestieFrame356 {
 }
 41 = QuestieFrame244 {
 }
 42 = QuestieFrame310 {
 }
 43 = Questie
AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.3.3
  AtlasLootClassicData, vv1.3.3
  AtlasLootClassicDungeonsAndRaids, vv1.3.3
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.16
  Bartender4, v4.8.8
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicLFG, v1.1.3
  ClassicThreatMeter, v1.10
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherLite, v1.3.3-classic
  Informant, v8.2.6374 (SwimmingSeadragon)
  MoveAnything, v17.0.5
  Questie, v5.1.0
  Recount, vv1.13.2e
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v5.2.12
  SpartanUIArtwork, v5.2.12
  SpartanUIFilmEffects, v5.2.12
  SpartanUIPartyFrames, v5.2.12
  SpartanUIPlayerFrames, v5.2.12
  SpartanUIRaidFrames, v5.2.12
  SpartanUISpinCam, v5.2.12
  SpartanUIStyleFel, v5.2.12
  SpartanUIStyleMinimal, v5.2.12
  SpartanUIStyleTransparent, v5.2.12
  SpartanUIStyleWar, v5.2.12
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TitanClassic, v1.1.3.11302
  TitanClassicAmmo, v1.1.3.11302
  TitanClassicBag, v1.1.3.11302
  TitanClassicClock, v1.1.3.11302
  TitanClassicGold, v1.1.3.11302
  TitanClassicGuild, v1.0.0.3
  TitanClassicLocation, v1.1.3.11302
  TitanClassicLootType, v1.1.3.11302
  TitanClassicPerformance, v1.1.3.11302
  TitanClassicRecZone, v1.0.0.5
  TitanClassicRegen, v1.1.3.11302
  TitanClassicRepair, v1.1.3.11302
  TitanClassicRestPlus, v1.0.0.1
  TitanClassicVolume, v1.1.3.11302
  TitanClassicXP, v1.1.3.11302
  TitanProfessionsMulti, v1.3
  TomTom, vv11302-1.0.8
  VuhDo, v3.107-classic
  VuhDoOptions, v3.107-classic
  BlizRuntimeLib_enUS v1.13.2.11302 <none>
  (ck=7b7)

**Comment by Wutname1** [comment]
Duplicate #270
