### ISSUE TITLE
(Classic) Every single target's health bar is 100/100

### ISSUE THREAD

**Issue by Mukkadun** [Wutname1/SpartanUI#272]
How can I change/fix this feature, that I'll see real enemy's hp? When I'm targeting myself, numbers are right, pet's also. It's like persentage, but in fraction. When it comes to mana (ally's and enemy's), everything is good.

**Comment by karai17** [comment]
You need to install an addon called "RealMobHealth". In Vanilla WoW, enemy health was hidden from the player.

**Comment by Wutname1** [comment]
Classic does not have exact health numbers. #nochanges
