### ISSUE TITLE
[Classic] Incompatible to Item Rack?

### ISSUE THREAD

**Issue by nickl3ss** [Wutname1/SpartanUI#273]
When ItemRack Addon and SpartanUI are active the Item Rack functions to switch gear do not work, neither from the context of the MiniMap Icon nor the Hotkey.

**Comment by poptix** [comment]
I'm having the same issue. Mousing over the icons ItemRack displays on the minimap icon doesn't highlight them, and doesn't select on click.

**Comment by poptix** [comment]
This turns out to be an issue with the FrameStrata of the ItemRack menu. I've submitted a pull request at https://github.com/Rottenbeer/ItemRack/pulls 

You can download a working itemrack from https://github.com/poptix/ItemRack until they merge it. 

Feel free to close this issue.

**Comment by nickl3ss** [comment]
Thanks @poptix
