### ISSUE TITLE
Primary and Secondary custom color

### ISSUE THREAD

**Issue by akaRaven** [Wutname1/SpartanUI#28]
Message: AceLocale-3.0: SpartanUI: Missing entry for 'Primary custom color'
Time: Wed Jul 18 20:35:16 2018
Count: 1
Stack: AceLocale-3.0: SpartanUI: Missing entry for 'Primary custom color'
...dOns\Bartender4\libs\AceLocale-3.0\AceLocale-3.0.lua:31: in function <...dOns\Bartender4\libs\AceLocale-3.0\AceLocale-3.0.lua:29>
Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:589: in function `BuildOptions'
Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:54: in function `Initalize'
...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:93: in function `SetupStatusBars'
...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:58: in function <...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:42>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1187: in function <Interface\FrameXML\UIParent.lua:1085>

Locals: <none>

Message: AceLocale-3.0: SpartanUI: Missing entry for 'Secondary custom color'
Time: Wed Jul 18 20:35:16 2018
Count: 1
Stack: AceLocale-3.0: SpartanUI: Missing entry for 'Secondary custom color'
...dOns\Bartender4\libs\AceLocale-3.0\AceLocale-3.0.lua:31: in function <...dOns\Bartender4\libs\AceLocale-3.0\AceLocale-3.0.lua:29>
Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:604: in function `BuildOptions'
Interface\AddOns\SpartanUI_Artwork\StatusBars.lua:54: in function `Initalize'
...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:93: in function `SetupStatusBars'
...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:58: in function <...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:42>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1187: in function <Interface\FrameXML\UIParent.lua:1085>

Locals: <none>

**Comment by Wutname1** [comment]
Added to localization system.  Triggered re-package as 4.6.2
