### ISSUE TITLE
[CLASSIC]Target spell release

### ISSUE THREAD

**Issue by Aosr-F** [Wutname1/SpartanUI#280]
Target spell release cannot be displayed
![image](https://user-images.githubusercontent.com/59150597/71328659-e6a14d00-2555-11ea-9f60-5af6c0dde713.png)

**Comment by Wutname1** [comment]
What?

**Comment by Aosr-F** [comment]
![Uploading image.png…]()
无法显示

**Comment by Aosr-F** [comment]
![Uploading image.png…]()

**Comment by Aosr-F** [comment]
无法显示目标施法条

**Comment by Aosr-F** [comment]
![image](https://user-images.githubusercontent.com/59150597/71331403-fc6e3c80-256c-11ea-820d-b63d60291f7b.png)

**Comment by Wutname1** [comment]
Target castbar is not built into classic.

**Comment by Aosr-F** [comment]
PVP  和 PVE 时 无法看到目标施法，

**Comment by Aosr-F** [comment]
Sorry ，I can't speak English。

**Comment by Wutname1** [comment]
Classic wow does not have target castbars at all.

**Comment by Aosr-F** [comment]
Thank you very much.I've always loved your spartanui。I can't play WOW without this

**Comment by Aosr-F** [comment]
classiccastbar      Hope to add the function of this plug-in。
