### ISSUE TITLE
can't see sanity orb interface in horrific visions

### ISSUE THREAD

**Issue by Psion77** [Wutname1/SpartanUI#284]
From talking with guildies, it seems that the interface is supposed to be over the hotbar, but the classic spartan UI seems to be hiding it.

**Comment by Wutname1** [comment]
SUI should be placing it above your minimap, You can try to reset your actionbars in /sui help or access the bartender movement system in /bt4 then uncheck Lock in the top right and see where its located. it is called the extra action button. 

In SUI 6.0 the movement & bar system is being rebuilt so the issue should not return in the next major update.

**Comment by Psion77** [comment]
Unfortunately, I blew 20,000 coalescing visions finding this bug and will have to wait a while before I can test to see if this helps.

I don't have any issues with other special buttons that are supposed to appear there. It only seems to be an issue with the sanity orb interface.

**Comment by ichEben** [comment]
i also experienced this issue.
as stated by Wutname1 it's a isse with your action bars.

I did open /bartender, unlocked the bars and repositioned the "Gebietsfähigkeitsleiste" - don't know how it's called in english. On my interface it was configured out of the screen.

It is NOT the extra action button.

![Unbenannt](https://user-images.githubusercontent.com/6838585/73302275-a730e500-4214-11ea-8612-0bcbfed44f08.PNG)

**Comment by eicenhour** [comment]
I also have ran into this as of today.  Is there still a fix due for this?

**Comment by Psion77** [comment]
I found a fix. There is something named like special action bar. There is another one as well. In my case, somehow it was under the minimap. I just moved stuff around until I found the thing that was under the minimap and that turned out to be it.

**Comment by eicenhour** [comment]
Thanks. I tried that and moved it outside the mini map but in the horrific visions it’s still not viewable. Maybe there’s another add on that’s blocking it but it sure is frustrating.

**Comment by Psion77** [comment]
It's called something like "area action bar" or something. I can't check because I'm not subbed right now and I can't quite remember the name. In the menu, it's further down towards the bottom of the list than the "special action bar".

**Comment by eicenhour** [comment]
It must be “zone ability bar.”  It was configured completely off the screen!  I’ll know next time I’m in a horrific vision and I’ll! report back. 

Thanks! 

-Erik

**Comment by eicenhour** [comment]
> 
> 
> It's called something like "area action bar" or something. I can't check because I'm not subbed right now and I can't quite remember the name. In the menu, it's further down towards the bottom of the list than the "special action bar".

That worked like a charm! Thank you!
