### ISSUE TITLE
Player castbar is disabled in recent patch. 

### ISSUE THREAD

**Issue by donnergid** [Wutname1/SpartanUI#288]
I have the castbar addon which will use the default blizzard castbar. After installing the latest patch, only the player castbar is being suppressed. I cannot find any existing settings which allow me to control this.

**Comment by Wutname1** [comment]
What add-on is it? if you're talking about "classic Castbars" that is not a blizzard thing it's 100% player made and is built into sui now. So please disable the add-on. 

if it's a different add-on please let me know the name of it so I can look into if I can support the conflict.

**Comment by donnergid** [comment]
It is not the classic addon. It is simply called "Castbars" by xbleeps.
