### ISSUE TITLE
Autosell LUA error/not working

### ISSUE THREAD

**Issue by Crystalinn** [Wutname1/SpartanUI#29]
**LUA Error in question**:
Message: Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)
Time: Wed Jul 18 10:59:43 2018
Count: 1
Stack: Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)
[C]: in function `GetItemIDs'
Interface\AddOns\SpartanUI\components\AutoSell.lua:336: in function `SellTrash'
Interface\AddOns\SpartanUI\components\AutoSell.lua:380: in function <Interface\AddOns\SpartanUI\components\AutoSell.lua:375>

Locals: (*temporary) = "Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)"

**Comment by Wutname1** [comment]
Fixed in d48845f468d7c76e1714d512735e54113081ce23 Make sure you are running SpartanUI 4.6.2

**Comment by Wutname1** [comment]
![wowscrnshot_071818_121343](https://user-images.githubusercontent.com/704321/42897303-d20ab572-8a7c-11e8-9e40-6560c8451df7.jpg)

**Comment by Wutname1** [comment]
I opened the vendor tonight and of course no error. Will dig into more this weekend when i have more time and a better setup to test stuff.

**Comment by Wutname1** [comment]
It does a bit. On the flip side my druid has 3 sets but is not getting the error. Will test this one out more tonight when i get back.

**Comment by Wutname1** [comment]
more info in #40

**Comment by Kestrana** [comment]
I'm not getting a LUA error but the auto sell feature isn't working for me either, and I do have equipment sets.
