### ISSUE TITLE
Local (error) - 5368 

### ISSUE THREAD

**Issue by KKempoo** [Wutname1/SpartanUI#290]
I keep getting this error multiple times a day. is there a fix to it have had it for a long time. want to thank for your hard work. 
1x [ADDON_ACTION_BLOCKED] AddOn 'SpartanUI' tried to call the protected function 'SUI_FramesAnchor:SetParent()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetParent'
[string "@SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua"]:65: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:63>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\SecureStateDriver.lua"]:100: in function <FrameXML\SecureStateDriver.lua:95>
[string "@FrameXML\SecureStateDriver.lua"]:127: in function <FrameXML\SecureStateDriver.lua:119>

**Comment by Wutname1** [comment]
Are you in combat when hiding and showing the UI with alt+z? or exiting/entering a vehicle?

**Comment by KKempoo** [comment]
happens when exiting/entering vehicle but mostly during the turtle quest. the ui disappears randomly and alt+z doesnt bring it back have to close game and restart to get ui back up.

**Comment by KKempoo** [comment]
I think the errors builds up and makes ui stop working over time and restarting game is only way to clear it, if i understand it correctly. but, in not coding it and and only have a ruff understanding about it
