### ISSUE TITLE
Cant disable

### ISSUE THREAD

**Issue by Webster9169** [Wutname1/SpartanUI#297]
When i disable SpartanUI, the default UI is nowhere to be found, and my 2 action bars are just going across the center of the screen, even after uninstalling and restarting game, so im currently stuck with this UI, which IMO is bulky and kinda unnecessary to begin with, i want less covering my screen, not more. Hope this doesnt come across rude because im really not trying to be.

**Comment by warcraftclassicgamer** [comment]
this sounds like a you problem tbh.

**Comment by Webster9169** [comment]
And you sound like a dumbass

**Comment by Webster9169** [comment]
> this sounds like a you problem tbh.

Yeah, and you sound like a dumbass, I didnt make this post for some random little kid to try to act like a big boy, i made it because its a issue with an addon someone made, usually when someones creation has an issue, they want to fix it, if you cant at least understand that much, i feel sorry for you.

**Comment by Wutname1** [comment]
Uninstall Barenter4 as well

**Comment by Webster9169** [comment]
> Uninstall Barenter4 as well

Thank you
