### ISSUE TITLE
Spartan UI Nameplate Lua Error spam

### ISSUE THREAD

**Issue by Kallous1** [Wutname1/SpartanUI#302]
I get this every 15 seconds or so. I even disabled the nameplate and it still triggers.
Message: Interface\AddOns\SpartanUI\components\Nameplates.lua:406: attempt to index local 'blizzPlate' (a nil value)

Any suggestions?

**Comment by Wutname1** [comment]
Classic or retail?

**Comment by Kallous1** [comment]
Retail. Once I turned nameplates off and reloaded ui it fixed.
