### ISSUE TITLE
Wow Classic Addon Compatibility Issue with ItemRack 3.37 (Minimap popout set icons)

### ISSUE THREAD

**Issue by Zeynar** [Wutname1/SpartanUI#306]
Hello,

I downloaded the latest version of Spartan UI, Bartender, and ItemRack. When using all but the "Minimal" Artwork set the minimap pop-out icons for each ItemRack set are not clickable. 

- Attempted moving ItemRack Minimpap icon around map and using it. 
- Attempted moving ItemRack Minimap to other parts of screen. (Alt + Click and Drag)
- Disabling the MiniMap Module allows the ItemRack Minimap Icon to function. (Cause the MiniMap to be presented using Blizzards default UI)
- Using a MiniMap Button Addon like Minimap Button Frame appears to decouple the MiniMap Button icons from the SpartanUI MiniMap Module allowing use of the Module.

[Video Demonstration of My Baseline UI Prior to SpartanUI Install](https://youtu.be/cp1KxYuxvSM)
[Video Demonstrationp of My Baseline UI + SpartanUI Installed](https://youtu.be/Y6uUyQ7cSTA)

Does anyone know if there is an overlay in SpartanUI around the Minmap that is possible placed in front of any other add-on menus? Perhaps a layering issue?

**Comment by Wutname1** [comment]
Will be fixed in 608 https://github.com/Wutname1/SpartanUI/commit/35f158a49078e8f5d35f1ab05623c9c842e6f03f
