### ISSUE TITLE
Causing Severe Lags and Crashes my Graphics Driver

### ISSUE THREAD

**Issue by Sorainia** [Wutname1/SpartanUI#314]
Hello,
I haven't played WoW for some time and now I have a whole lot of lags for more then 5 seconds a time. After deactivating all my addons and activating them one by one I noticed that SpartanUI is the cause. I reinstalled WoW completely, updated my graphics driver, reinstalled all my addons and just used bartender 4 and spartan, but it still ocurres. I really love this ui, so I would welcome some kind of fix. 
For information: I use Win 10 and a Nvidia GTX 670

**Comment by Wutname1** [comment]
Turn on  LUA errors with '/console scriptErrors 1'
Once errors are on you can /reload and see if any errors popup
If you get more than 1 error i would recommend installing Bugsack and Bug grabber.
BugSack - https://www.curseforge.com/wow/addons/bugsack
BugGrabber -  https://www.curseforge.com/wow/addons/bug-grabber
These will put the errors into a bag icon on your minimap and make them less annoying.
