### ISSUE TITLE
base frame style not working

### ISSUE THREAD

**Issue by sindaliza** [Wutname1/SpartanUI#315]
my HUD has always been set to base art style across the board.  when i logged in tonight and had to reset the mod it will not change back to base frames,  the artwork style changed back but the base frame style will not even if i revert customizations back to base style nor will it change to any other style other then what appears to be mininal or transparent.  i did disable all the other options in the addons seciton and it still would not go back.  i also disabled all other mods and it will not go back.

**Comment by Wutname1** [comment]
do you mean unit frames not having artwork?

**Comment by Ryzael75** [comment]
for me, unit frames have artwork. but they are stuck on transparent unit frames. i prefer the classic package, but it won't let me change unit frames. i have no other addons that have anything to do with unit frames. like the person above, i tried reverting back to base, unit frames still stuck on transparent option. the rest of the artwork changes to whatever i choose.

**Comment by Wutname1** [comment]
@Ryzael75 they are nto stuck on transparent frames. the classic artwork has not been updated for SUI6 yet. More info can be found in discord in the SUI6 Survival Guide channel

**Comment by sindaliza** [comment]
Yes the characters unit frames.
