### ISSUE TITLE
Update broke everything??

### ISSUE THREAD

**Issue by Boyo83** [Wutname1/SpartanUI#316]
I have been using Spartan UI for months now with very little issues, until today. I downloaded and installed the newest version through Twitch and when I entered the game all my settings had gone back to default, it wanted me to restart all the configuration with my characters again and when I tried and got to the end nothing on my screen changed and I continuously got error messages about it. I have very limited computer knowledge so I couldn't go into detail about what the issue was only that to stop it occurring every time I logged in I had to delete the addon and all the cached folders that were linked to it.

**Comment by syntruth** [comment]
My girlfriend is having the same issue on Classic. Everything is broke, throwing up a lot of errors. We're not sure which versions to fall back to or what lib versions are also required for that.

**Comment by Boyo83** [comment]
Yeah I should probably have said it was on Classic I was having the issues. I've tried deleting everything and reinstalling it as a fresh install of the addon on a fresh game and I'm still getting the same issue. The only thing I could make sense of was that it said it couldn't find an oUF file in spartanui/libs/ouf  or something :S as I said I have very little computer knowledge so I can't read into it very much :(

**Comment by Wutname1** [comment]
If you are using the Twitch updater it has been installing the wrong versions for addons today. Retail is getting classic builds and classic is getting retail versions installed.

**Comment by Boyo83** [comment]
really?? Damn :( how do I go about fixing that or is it a *wait and they'll sort it out* type of thing and just wait for a fresh update? sorry to sound so ignorant to it all but as a bit of a computer tech illiterate I was happy to just click the update button on twitch and let it do it all for me :(

**Comment by syntruth** [comment]
We're trying to manually install from the zip files on the release page. If it works, will let you know.

**Comment by KashiofWavecrest** [comment]
I have the same issue on retail. I tried to manually download SUI and WoW keeps telling me it is out of date and when I log in, the player unit frames are broken and the test is stuck in default with tons of error messages.

**Comment by syntruth** [comment]
Okay, it is still throwing up an error when loading into the game, below. What can we manually do to get this fixed?

```Date: 2020-10-13 21:00:10
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua line 56:
   oUF_AuraBars was unable to locate oUF install.
Debug:
   [C]: assert()
   ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua:56: in main chunk
Locals:
(temporary) = nil
(temporary) = "oUF_AuraBars was unable to locate oUF install."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Ace3, v
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  aucadvancedsearcherpawn, v1.6.2-classic
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  AuctionDB, vv1.03.01
  BagBrother, v
  Bartender4, v4.10.0
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.07
  BigWigs, vv15-classic
  BlizzMove, v2.1.6
  CharacterStatsClassic, v3.6.5
  ClassicAuraDurations, v1.13.61
  Combuctor, v8.3.2
  FishingBuddy, v0.7.3 Beta 7
  GatherMate2, v1.45.5
  Glass, v1.8.0
  LeatrixMaps, v1.13.81
  LeatrixPlus, v1.13.81
  Masque, v8.3.1
  Musician, v1.6.1.0
  NoteworthyII, v2.0
  OmniCC, v9.0.0
  Outfitter, v1.3.0
  Pawn, v2.4
  Peggle, v2.2.8
  Questie, v6.0.5
  ShadowedUnitFrames, vv4.2.3-Classic
  SharedMediaClassicalFonts, v8.3-release1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v6.0.1
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=4ca)
```

**Comment by Boyo83** [comment]
yeah that's exactly what I was getting, the oUF thing. No idea how to fix it though :( anything beyond the *Update* button and I'm lost :(

**Comment by MamaCougar** [comment]
I don't think this is anything we can fix.  I think it will have to be a programming update done.  I miss is like crazy and am afraid we will have to wait until these people catch up with the newest update to WoW.

**Comment by syntruth** [comment]
Line 46 of oUF.xml looks odd:

```xml
<!--@non-retail@-->-->
```

Should only have one closing end-arrow, yeah?

**Comment by KashiofWavecrest** [comment]
God, this is making me have to install ElvUI, which is so drab and bland and joyless. Please find a fix a someone good with code!

**Comment by Wutname1** [comment]
> Message: ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua line 56:

That would likely be due to the unit frames not appearing. 

@syntruth @KashiofWavecrest @MamaCougar @Boyo83 are you on retail or classic?

**Comment by KashiofWavecrest** [comment]
Retail for me.

**Comment by Wutname1** [comment]
Please ensure you have update to 6.0.3 and let me know what issues you are having still.

**Comment by KashiofWavecrest** [comment]
The error messages are gone, but my Unit frame style is still refusing to change. It's very odd. The core Spartan UI is now showing up to date, but none of the peripherals are. I am attaching a screenshot of what I mean [](https://imgur.com/a/0vmnSts)

**Comment by Mercian** [comment]
Hi,
I'm playing on retail, Actually the player frames are not switching the artwork when I select base frame style in Unit Frames module.

Additionally when I select the Arcane style in Art Style Section in Common it is not showing any art style at all. All other Art Styles are working fine.

**Comment by Mercian** [comment]
Additionally I just saw, that the action bars are of the grid. Resetting of Bartender4 is not helping. My scale is set to 0.88.

**Comment by Boyo83** [comment]
I am playing on classic, I haven't tried it since I posted this but will be logging on now and will update with what the situation is

**Comment by Boyo83** [comment]
Date: 2020-10-14 11:34:55
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua line 56:
   oUF_AuraBars was unable to locate oUF install.
Debug:
   [C]: ?
   [C]: assert()
   ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua:56: in main chunk
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.1
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.5
  ClassicAuraDurations, v1.13.61
  DBMCore, v1.13.61-2-gfb7404c
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.6-classic
  MissingTradeSkillsList, v1.13.51
  OmniCC, v9.0.0
  Questie, v6.0.5
  Recount, vv1.13.5c
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v6.0.3
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=4bb)


That's 1 page of 10 error pages when I logged in with the new update from Twitch a couple of minutes ago :(

**Comment by Boyo83** [comment]
Date: 2020-10-14 11:34:55
ID: 2
Error occured in: Global
Count: 1
Message: ...Ons\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua line 199:
   attempt to index local 'oUF' (a nil value)
Debug:
   [C]: ?
   ...Ons\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:199: in main chunk
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.1
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  CharacterStatsClassic, v3.6.5
  ClassicAuraDurations, v1.13.61
  DBMCore, v1.13.61-2-gfb7404c
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Dismounter, v1.2.1
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  GatherMate2, v1.45.6-classic
  MissingTradeSkillsList, v1.13.51
  OmniCC, v9.0.0
  Questie, v6.0.5
  Recount, vv1.13.5c
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v6.0.3
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=4bb)


That's the 2nd page (there are 8 more but I just wanted to show each page is different, it's not 10 pages of the same issue)

**Comment by Nemesis2354** [comment]
My problem is, that the classic player frame unit is damaged. i can´t use the classic interface player frame. i use the 6.0.3 Retail version.

**Comment by Nemesis2354** [comment]
> I have the same issue on retail. I tried to manually download SUI and WoW keeps telling me it is out of date and when I log in, the player unit frames are broken and the text is stuck in default with tons of error messages.

The Error messsages are from older other addons, when i am updated the most of the addons to version 9.0.1 and deactivate the other older addons, the error messages are gone.

**Comment by jb4479** [comment]
Version 6.0..3 retail, unit frames do not change at all. No other addons loaded.

**Comment by syntruth** [comment]
@Wutname1 We're on Classic.  I will have her test 6.0.4 after work tonight, but we might drop back to the 5.3.2 version so she can at least play with her preferred set up if that doesn't work for her.

**Comment by Boyo83** [comment]
So I uninstalled all my addons, deleted everything to do with sUI from my warcraft folders and reinstalled 6.0.4 and booted the game up, and this is what I got - 

Page 1 - 

Date: 2020-10-15 05:58:30
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua line 56:
   oUF_AuraBars was unable to locate oUF install.
Debug:
   [C]: assert()
   ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua:56: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "oUF_AuraBars was unable to locate oUF install."

Page 2 - 

Date: 2020-10-15 05:58:30
ID: 2
Error occured in: Global
Count: 1
Message: ...Ons\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua line 199:
   attempt to index local 'oUF' (a nil value)
Debug:
   ...Ons\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:199: in main chunk
Locals:
_ = "SpartanUI"
ns = <table> {
}
oUF = nil
ArtPositions = <table> {
 1 = "top"
 2 = "bg"
 3 = "bottom"
 4 = "full"
}
Update = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:28
Path = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:146
ForceUpdate = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:157
Enable = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:161
Disable = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:181
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'oUF' (a nil value)"

Page 3 - 

Date: 2020-10-15 05:58:30
ID: 3
Error occured in: Global
Count: 1
Message: ...libs\oUF_QuestMobIndicator\oUF_QuestMobIndicator.lua line 27:
   attempt to index local 'oUF' (a nil value)
Debug:
   ...libs\oUF_QuestMobIndicator\oUF_QuestMobIndicator.lua:27: in main chunk
Locals:
_ = "SpartanUI"
ns = <table> {
}
oUF = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'oUF' (a nil value)"

Page 4 - 

Date: 2020-10-15 05:58:30
ID: 4
Error occured in: Global
Count: 1
Message: ...ddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua line 137:
   attempt to index local 'oUF' (a nil value)
Debug:
   ...ddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:137: in main chunk
Locals:
_ = "SpartanUI"
ns = <table> {
}
oUF = nil
widgetMap = <table> {
 151309 = 1920
 163651 = 2342
 163593 = 2342
 154297 = 1966
 151310 = 1622
 150202 = 1613
 149803 = 1966
 149904 = 1621
 163595 = 2342
 149804 = 1613
 163541 = 2342
 151300 = 1621
 163592 = 2342
 163596 = 2342
 149805 = 1940
 149902 = 1622
 149906 = 1920
 163648 = 2342
 154304 = 1940
}
GetBaseInfo = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:25
Hide = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:44
Update = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:54
Path = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:107
ForceUpdate = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:111
Enable = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:115
Disable = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_Plugins\oUF_WidgetXPBar.lua:127
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'oUF' (a nil value)"

Page 5 - 

Date: 2020-10-15 05:58:31
ID: 5
Error occured in: Global
Count: 1
Message: ...UF_ClassicAuraDurations\oUF_ClassicAuraDurations.lua line 50:
   attempt to index local 'oUF' (a nil value)
Debug:
   ...UF_ClassicAuraDurations\oUF_ClassicAuraDurations.lua:50: in main chunk
Locals:
addonName = "SpartanUI"
ns = <table> {
}
oUF = nil
LibClassicDurations = <table> {
 Register = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:994
 dataVersions = <table> {
 }
 guidAccessTimes = <table> {
 }
 GetAuraDurationByUnit = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:968
 castLog = <table> {
 }
 Talent = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:128
 GetSpellTable = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:594
 enableEnemyBuffTracking = false
 RegisterCallback = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetAuraDurationByUnitDirect = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:950
 AddAura = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:104
 UnregisterCallback = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IsSetBonusActiveFullCheck = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1107
 TrackItemSet = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1076
 DR_TypesPVE = <table> {
 }
 indirectRefreshSpells = <table> {
 }
 GetAuraDurationByGUID = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:972
 buffCache = <table> {
 }
 purgeTicker = <table> {
 }
 setwatcher = <unnamed> {
 }
 callbacks = <table> {
 }
 spellNameToID = <table> {
 }
 IsSetBonusActive = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1096
 UnitAuraDirect = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:834
 RegisterSetBonusCallback = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1087
 DR_CategoryBySpellID = <table> {
 }
 MonitorUnit = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1044
 UnregisterFrame = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1006
 UnitAura = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:860
 guids = <table> {
 }
 GetLastRankSpellIDByName = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:979
 UnregisterAllCallbacks = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 Unregister = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1006
 DRInfo = <table> {
 }
 scanTip = LibClassicDurationsScanTip {
 }
 nameplateUnitMap = <table> {
 }
 RegisterFrame = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:994
 spells = <table> {
 }
 activeFrames = <table> {
 }
 GetDataVersion = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:100
 GetDurationForRank = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:984
 NPCSpellTableTimer = <table> {
 }
 ToggleDebug = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:1019
 SetDataVersion = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:94
 npc_spells = <table> {
 }
 frame = <unnamed> {
 }
 UnitAuraWithBuffs = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:834
 UnitAuraWrapper = <function> defined @Interface\AddOns\ClassicAuraDurations\Libs\LibClassicDurations\core.lua:856
}
LCDWrapper = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_ClassicAuraDurations\oUF_ClassicAuraDurations.lua:9
prehook_PostUpdateIcon = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_ClassicAuraDurations\oUF_ClassicAuraDurations.lua:31
hook = <fu

Page 6 - 

Date: 2020-10-15 05:58:31
ID: 6
Error occured in: Global
Count: 1
Message: ..\AddOns\SpartanUI\core\oUF.lua line 218:
   attempt to index global 'SUIUF' (a nil value)
Debug:
   SpartanUI\core\oUF.lua:218: in main chunk
Locals:
addon = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 IsRetail = false
 DBUpgrades = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:1812
 EnableModule = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Modules.lua:55
 modules = <table> {
 }
 IterateEmbeds = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 Lib = <table> {
 }
 FontRefresh = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Font.lua:136
 BuildNum = "784"
 CopyTable = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:2004
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 CreateProfileExport = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Profiles.lua:86
 defaultModuleState = true
 GetImportStringType = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Profiles.lua:98
 IsEnabled = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 UpdateDefaultSize = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Font.lua:86
 DisableModule = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Modules.lua:44
 RemoveEmptySubTables = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:2022
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:144
 GetFontFace = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Font.lua:46
 HotsListing = <function> defined @Interface\AddOns\SpartanUI\core\oUF.lua:4
 SetEnabledState = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IsModuleEnabled = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Modules.lua:21
 IterateModules = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 Version = "6.0.4"
 isPartialMatch = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:1954
 suihelp = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:2272
 OnInitialize = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:1770
 NewModule = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 print = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:1884
 GetModule = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 BT4RefreshConfig = <function> defined @Interface\AddOns\SpartanUI\modules\BarHandlers\Bartender4.lua:555
 IsClassic = true
 Bartender4Version = "4.10.1"
 GitHash = "ea4cea3"
 UnregisterChatCommand = <function> defined @Interface\AddOns\Atlas\Libs\AceConsole-3.0\AceConsole-3.0.lua:111
 opt = <table> {
 }
 SpartanUIDB = <table> {
 }
 pvpIcon = <function> defined @Interface\AddOns\SpartanUI\core\oUF.lua:84
 oUF_Buffs = <function> defined @Interface\AddOns\SpartanUI\core\oUF.lua:39
 StdUi = <table> {
 }
 GetName = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 IsModuleDisabled = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Modules.lua:32
 ExportUI = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Profiles.lua:172
 RemoveTableDuplicates = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:2043
 name = "SpartanUI"
 Enable = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 FormatFont = <function> defined @Interface\AddOns\SpartanUI\core\Handlers\Font.lua:97
 orderedModules = <table> {
 }
 Error = <function> defined @Interface\AddOns\SpartanUI\core\Framework.lua:1891
 Disable = <function> defined @Interface\AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 comma_value = <function> defin

Page 7 - 

Date: 2020-10-15 05:58:32
ID: 7
Error occured in: Global
Count: 1
Message: ..\AddOns\SpartanUI\modules\Nameplates.lua line 595:
   attempt to index global 'SUIUF' (a nil value)
Debug:
   SpartanUI\modules\Nameplates.lua:595:
      SpartanUI\modules\Nameplates.lua:594
   [C]: ?
   ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:623:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615

Page 8 - 

Date: 2020-10-15 05:58:32
ID: 8
Error occured in: Global
Count: 1
Message: ..\AddOns\SpartanUI\core\Handlers\Modules.lua line 51:
   Usage: GetModule(name, silent): 'name' - Cannot find module 'Component_chatbox'.
Debug:
   [C]: ?
   ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:212: GetModule()
   SpartanUI\core\Handlers\Modules.lua:51: DisableModule()
   SpartanUI\modules\Chatbox.lua:271:
      SpartanUI\modules\Chatbox.lua:248
   [C]: ?
   ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:70:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:498: InitializeAddon()
   ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:623:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615

Sorry for the massive post but I was trying to show as many errors as I could, there are more pages but it stops me at this page number for some reason :S

**Comment by Boyo83** [comment]
I updated to 6.0.4 and booted the game up and I'm still getting all the same errors and I can't do anything with it :'( I even became an epic Patreon to help out as I really don't want to see this addon fail, it's like a different game without it :'(

**Comment by Boyo83** [comment]
Date: 2020-10-15 06:14:41
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua line 56:
   oUF_AuraBars was unable to locate oUF install.
Debug:
   [C]: assert()
   ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua:56: in main chunk
Locals:
(*temporary) = nil
(*temporary) = "oUF_AuraBars was unable to locate oUF install."

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Bartender4, v4.10.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v6.0.4
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=a8)

Date: 2020-10-15 06:14:41
ID: 2
Error occured in: Global
Count: 1
Message: ...Ons\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua line 199:
   attempt to index local 'oUF' (a nil value)
Debug:
   ...Ons\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:199: in main chunk
Locals:
_ = "SpartanUI"
ns = <table> {
}
oUF = nil
ArtPositions = <table> {
 1 = "top"
 2 = "bg"
 3 = "bottom"
 4 = "full"
}
Update = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:28
Path = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:146
ForceUpdate = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:157
Enable = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:161
Disable = <function> defined @Interface\AddOns\SpartanUI\libs\oUF_SpartanArt\oUF_SpartanArt.lua:181
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'oUF' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Bartender4, v4.10.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v6.0.4
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=a8)

Date: 2020-10-15 06:14:41
ID: 3
Error occured in: Global
Count: 1
Message: ...libs\oUF_QuestMobIndicator\oUF_QuestMobIndicator.lua line 27:
   attempt to index local 'oUF' (a nil value)
Debug:
   ...libs\oUF_QuestMobIndicator\oUF_QuestMobIndicator.lua:27: in main chunk
Locals:
_ = "SpartanUI"
ns = <table> {
}
oUF = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'oUF' (a nil value)"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  Bartender4, v4.10.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  SpartanUI, v6.0.4
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=a8)

there are a load more pages, more than last attempt at installing it :( these are the first 3 that show up

**Comment by Wutname1** [comment]
> Message: ...\AddOns\SpartanUI\libs\oUF_AuraBars\oUF_AuraBars.lua line 56:

There is likely an error before this one. download these 2 addons

BugSack - https://www.curseforge.com/wow/addons/bugsack
BugGrabber -  https://www.curseforge.com/wow/addons/bug-grabber

once you do there will be a bag icon on your minimap this will contain all the error messages. open it up by clicking on the bag, go back to the first error by clicking previous send me the first 2 errors

**Comment by Boyo83** [comment]
they aren't available on classic :(

**Comment by Wutname1** [comment]
The retail version works in classic it will just say its 'out of date'

**Comment by Boyo83** [comment]
no I mean it won't show up at all on the search bar when you look on the *Classic* page on twitch, only on the *retail* page :( Unless I'm doing it wrong, which is a possibility

**Comment by Wutname1** [comment]
Curse is being slow but install the 6.0.6-classic and let me know if it fixes it for you.

**Comment by Wutname1** [comment]
https://github.com/Wutname1/SpartanUI/releases/tag/6.0.6 seems to have fixed classic for most people.
