### ISSUE TITLE
Bartender 4 movement system overridden by SpartanUI

### ISSUE THREAD

**Issue by Romeus83** [Wutname1/SpartanUI#317]
Can some one advise is there a way to disable this? This is so i can move the buttons within the grid. Much appreciated. Thanks

**Comment by Wutname1** [comment]
sounds like you are looking for the button lock option in bartender4

![image](https://user-images.githubusercontent.com/704321/96006918-9b696b00-0e03-11eb-84ce-25d1f0bf2ceb.png)

**Comment by Romeus83** [comment]
> sounds like you are looking for the button lock option in bartender4
> 
> ![image](https://user-images.githubusercontent.com/704321/96006918-9b696b00-0e03-11eb-84ce-25d1f0bf2ceb.png)

![Untitled](https://user-images.githubusercontent.com/72858874/96013854-4e73ac00-0e78-11eb-9f14-c76ade68bc8a.png)

No i am not. Refer to image attached. When i want unlock my bars...the error keep popping up
