### ISSUE TITLE
Retail - Classic style skin missing player/target frame setup

### ISSUE THREAD

**Issue by qualitaz** [Wutname1/SpartanUI#318]
Relevant info:
Deleted WTF folder and all old folders with any SUI related info including BT4.
Retail - 9.0.1 (36230)
Addons installed - Bartender4, BugGrabber, SpartanUI 6.0.3

Issue:
When choosing classic skin, the player/target/-of-target frames looks the same as the minimal/digital/transparent and keep the same placement as well, instead of going down to each side of the minimap as expected.

When choosing any other layout then classic (arcane might have some issues as well, but have never looked at it before, so wouldnt know for sure) the player/target/-of-target frames change as they should from the looks of it.

**Comment by qualitaz** [comment]
Check picture in https://github.com/Wutname1/SpartanUI/issues/319 for visual info about how the frames look even when choosing classic skin.

**Comment by Wutname1** [comment]
Expected. 

From the SUI6 Survival Guide in discord:
With unit frames being re-wrote from scratch the artwork takes a lower priority than making sure all the new customization and options are functioning. As such not all unitframe art is finished for SUI 6.0 but will be by 6.1
