### ISSUE TITLE
Retail 9.0.1 - Floating nameplates.

### ISSUE THREAD

**Issue by theejynx** [Wutname1/SpartanUI#319]
I've tried different options within the SpartanUI interface, disabled all other addons save for Bartender and SpartanUI, and it happens on both the PCs I play on. Not sure if it's an issue with Bartender or SpartanUI, so I've placed this issue in both. Thank you for your help, love your addon. :)

![image](https://user-images.githubusercontent.com/72872218/95996433-45db9100-0df8-11eb-98d1-a6e5c8020190.png)

**Comment by Wutname1** [comment]
Looks like the personal resource display. nothing new here is how to disable: 
![image](https://user-images.githubusercontent.com/704321/96007273-f0a57c80-0e03-11eb-9d26-3b0e0bb30e9e.png)
