### ISSUE TITLE
Retail 9.0.1 - Floating unitframes. #319

### ISSUE THREAD

**Issue by mascotkid** [Wutname1/SpartanUI#321]
The comments about personal resource don't seem to be the issue.  I have the same problem, when using classic mode, the Player Frame floats above the mini map, along with target, and target of target.  I too cannot find a way to re-anchor to the classic view bar, next to the mini map.

**Comment by Wutname1** [comment]
Expected.
From the SUI6 Survival Guide in discord:
With unit frames being re-wrote from scratch the artwork takes a lower priority than making sure all the new customization and options are functioning. As such not all unitframe art is finished for SUI 6.0 but will be by 6.1
