### ISSUE TITLE
Chat module issue

### ISSUE THREAD

**Issue by Kholdbier** [Wutname1/SpartanUI#325]
The chat module will not hold the font size settings.  Chat font size always reverts to 12 after reloading or logout/login.

**Comment by Wutname1** [comment]
![image](https://user-images.githubusercontent.com/704321/96048083-bbb51c00-0e3b-11eb-8124-b5aec0f93f9b.png)
change it in SUI not blizzard ui

**Comment by Kholdbier** [comment]
Rog that.  Also, you mis-spelled EXPERIENCE

Sent from Mail for Windows 10

**Comment by Kholdbier** [comment]
I was looking for it in the Chat Module…

Sent from Mail for Windows 10
