### ISSUE TITLE
SUI Classic lua errors

### ISSUE THREAD

**Issue by Timber-Hawk** [Wutname1/SpartanUI#327]
1x SpartanUI\modules\UnitFrames\SpawnFrames.lua:1214: attempt to index global 'SUIUF' (a nil value)
SpartanUI\modules\UnitFrames\SpawnFrames.lua:1214: in function `SpawnFrames'
...ceSpartanUI\modules\UnitFrames\Framework.lua:213: in function <...ceSpartanUI\modules\UnitFrames\Framework.lua:173>
[C]: ?
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:527: in function `EnableAddon'
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:540: in function `EnableAddon'
Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:630: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Wutname1** [comment]
What have you disabled?

**Comment by Timber-Hawk** [comment]
Not yet

Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Wutname1** [comment]
Have you updated to 604? thats error does not reference a line that exists in the latest version

**Comment by Timber-Hawk** [comment]
Got the newest update from curseforge today

Sent via the Samsung Galaxy S10, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Kholdbier** [comment]
I had the same error.  I switched over to Digital and the error stopped.

**Comment by Timber-Hawk** [comment]
looks like i had 6.03 just 6.04


________________________________

**Comment by Wutname1** [comment]
606 should fix it

**Comment by Kholdbier** [comment]
It hasn’t.  Still kicking back LUA errors.  Let me see if I can get you a good copy and paste.

Sent from Mail for Windows 10

**Comment by Kholdbier** [comment]
Sent from Mail for Windows 10

**Comment by Kholdbier** [comment]
LUA Error From 6.0.7



Sent from Mail for Windows 10

**Comment by Kholdbier** [comment]
This may or may not be helpful…


Sent from Mail for Windows 10

**Comment by Kholdbier** [comment]
Your notes on the additional legacy folders state that they can be deleted.  Why are you still including them in 6.0.7?  I just did a complete wipe of SUI and deleted the folders.  I reinstalled, and lo and behold, those Legacy Folders reappeared.

Sent from Mail for Windows 10

**Comment by Wutname1** [comment]
It states they can be removed in 6.1 Not everyone that uses sui has updated so therefore I need to still include them

**Comment by Kholdbier** [comment]
Logical

Sent from Mail for Windows 10
