### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by Dahlaine** [Wutname1/SpartanUI#329]
I have updated to version 6.0.6 and am having the below error. I am also having the same problems with frames as everyone else.

14x SpartanUI\core\Handlers\Modules.lua:51: Usage: GetModule(name, silent): 'name' - Cannot find module 'Component_chatbox'.
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:212: in function `GetModule'
[string "@SpartanUI\core\Handlers\Modules.lua"]:51: in function `DisableModule'
[string "@SpartanUI\modules\Chatbox.lua"]:271: in function <SpartanUI\modules\Chatbox.lua:248>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Dahlaine** [comment]
Just did a little testing and this error goes away if I disable the Prat addon.

**Comment by Wutname1** [comment]
If you disable the SUI Chatbox module manually the error will go away. SUI is trying to auto-disable its chat mod when it sees prat and I did not capitalize a letter. will be fixed in 607

`/script SUI:DisableModule('Chatbox')`
