### ISSUE TITLE
Issue with Player and Party Frames, Icons not "always" showing despite selection

### ISSUE THREAD

**Issue by MzMadCat** [Wutname1/SpartanUI#330]
I've always used the classic frame style for both my player and party frames but with the newest update, I am not able to do so.  Clicking on it does not result in any change, same with other frame styles - I am currently only able to use one frame style type.

The other issue I'm having is to do with the minimap.  Under Modules>Minimap, I select the "Always Show" in the drop-down and this usually results in the icons on the minimap always showing but currently, if I perform a reload or exit the game and sign back in, the icons are again not showing until I mouse over the minimap.

Thank you for all your hard work with this addon, it's amazing and I seriously would not be able to play wow without it.

**Comment by Wutname1** [comment]
> I've always used the classic frame style for both my player and party frames but with the newest update, I am not able to do so. Clicking on it does not result in any change, same with other frame styles - I am currently only able to use one frame style type.

https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814

**Comment by Wutname1** [comment]
> The other issue I'm having is to do with the minimap. Under Modules>Minimap, I select the "Always Show" in the drop-down and this usually results in the icons on the minimap always showing but currently, if I perform a reload or exit the game and sign back in, the icons are again not showing until I mouse over the minimap.

This was a bug in a old build ensure you are up to date SUI is up to 6.0.6 at this moment and will likely see a 6.0.7 tonight. check for updates daily.
