### ISSUE TITLE
Classic player and tartget frames are in the way and cannot find any option to move them

### ISSUE THREAD

**Issue by ChitfoBrainz** [Wutname1/SpartanUI#334]
The player and target frames , I used to have them on either side of my mini map on the fire and ice , now they're right underneath my character kind of in the way and I have tried every option I could find and see no option to move them where I want other than turning off the frames and they go back to the basic frame which you can right click on and select lock and unlock. Wondering if there is a way to move them or maybe in the works later on ?

**Comment by Deakkin** [comment]
I used "/sui move" and that allowed me to drag my player and target frames where I want. Drag player first and then drag target so you can unlink them and split them as you like.

**Comment by ChitfoBrainz** [comment]
TYVM !!!   that was exactly what I needed !

Sent from Outlook<http://aka.ms/weboutlook>
________________________________
