### ISSUE TITLE
Dead Zone

### ISSUE THREAD

**Issue by Iceman5223** [Wutname1/SpartanUI#335]
There seems to be a dead zone, I've noticed that by turning on and off spartan and bartender, alternating, the dead zone seems to move, but not disappear completely.  Unsure what may be causing this, but it did disappear when I turned both off and was on the native WoW UI.

**Comment by Wutname1** [comment]
If you type /sui move is there something where the dead spot is? Also please make sure you are fully updated.

**Comment by Iceman5223** [comment]
I do have the latest update and there is no ui window/space in that area
when I toggle movers on. I've realized I can somewhat move this invisible
dead zone, without movers toggled, but not completely off screen, but
merely trying to maneuver to an area I hardly use for mouse interaction. I
changed art styles just to make sure and it didn't matter. The dead zone
was still present. It only disappeared when I turned off both bartender and
spartan. Otherwise it was there when either one was turned off
alternatively.

**Comment by Ryzael75** [comment]
I know you have only mentioned SUI and BT4. But do you have any other addons active? It is possible that another addon has a custom frame that SUI's frame manager doesn't recognize and therefore doesn't show. Modified frames should show using the frame manager since they are just altered WoW frames...but new custom frames may not, and will likely only be moveable by that addon's options.

**Comment by Wutname1** [comment]
Type `/fstack` in your chat this will enter a special mode that says what is under the mouse. mouse over the deadzone and hit alt this will toggle between items under the mouse, take a screenshot when you find the item that is causing the deadzone and post that screenshot.

**Comment by Iceman5223** [comment]
I did the command you suggested and I fixed my issue. Somehow AtlasLoot was
constantly open, but not visible and that would explain why I was able to
move the dead zone somewhat, because it was an active window. Odd that it
disappeared when I turned off bartender and spartan together before. Now
that I have AtlasLoot turned off, I no longer have the dead zone. Glad you
were able to help.
