### ISSUE TITLE
Player/Target-targettarget frame

### ISSUE THREAD

**Issue by xGeneralMetalx** [Wutname1/SpartanUI#338]
Updated the addon. Then update applied the changes. Player frame went to this weird artwork ive never seen. So I went to change it to the classic spartinui one and it wont change. Tried using all the availible artwork to see if its bugged. So far seems to be.
![WoWScrnShot_101620_074918](https://user-images.githubusercontent.com/41525512/96273429-31c49a80-0f84-11eb-97b6-b541c10c82d1.jpg)

**Comment by Ryzael75** [comment]
Not bugged..just not yet updated. He has been working on fixing actual bugs as his main priority last few days. He will get to the unitframes and artwork soon.

**Comment by Scuffedaf** [comment]
Not yet updated? Then why u bring it out? You call this an update? Fix asap pls, whole ui is screwed.

**Comment by Scuffedaf** [comment]
![image](https://user-images.githubusercontent.com/72989740/96284669-328a1a80-0fde-11eb-9cc9-0da15c4b29fb.png)

**Comment by Scuffedaf** [comment]
If it's not fixed by tomorrow I'm yeeting this addon in the garbage bin...

**Comment by Ryzael75** [comment]
SUI does not have a bag module..never has. Install Bagnon or one of the others. Disabling Party/Raid frames was fixed in yesterday's release...6.0.7, make sure you have latest release. And in your chatbox, type in /SUI move. He has a built in frame mover, it should allow postioning of tooltips...and maybe even your bags. Other than that, take your foul attitude and leave..you and others like you are not welcome.

**Comment by Kehlban** [comment]
**Appreciate** all the work you do to keep SUI up and running.  Same issue, will wait for when you have a chance to get to that part up the updates.  Wanted to let you know that there are those whose appreciate the work!

**Comment by Scuffedaf** [comment]
Went back to 9.0.1. Gives annoying popup though. Don't know what you done with new version but screwed my raid this evening.

**Comment by xGeneralMetalx** [comment]
> 
> 
> Not bugged..just not yet updated. He has been working on fixing actual bugs as his main priority last few days. He will get to the unitframes and artwork soon.

How is it not a bug if you aren't able to change something within its own settings? I get some people are having bigger issues. And thats due to them having one to many addons that haven't been updated or conflcting.

**Comment by Wutname1** [comment]
Duplicate https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814

**Comment by xGeneralMetalx** [comment]
> 
> 
> Duplicate [#323 (comment)](https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814)

Thank you for taking your time to look into these issues. My fault for making duplicate threats.
