### ISSUE TITLE
Issues with the player and target frames.

### ISSUE THREAD

**Issue by Metalmatt2891** [Wutname1/SpartanUI#340]
Love the addon and have been using it for the longest time. I am having problems with the player and target frames where the art style cannot be edited. I prefer the Classic art look but the art style is not currently changeable no matter what I have tried.

I'm not sure what could be causing this but in the unit frames the Base frame style won't effect the frames at all.
If anybody knows a work around I would appreciate it.

**Comment by Wutname1** [comment]
DUplicate https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814
