### ISSUE TITLE
Large number of errors + bar misalignment

### ISSUE THREAD

**Issue by Melko22** [Wutname1/SpartanUI#341]
![image](https://user-images.githubusercontent.com/73024436/96337205-16898600-107d-11eb-9a50-655b6daacd99.png)

each error reports (null) when clicked, re-running the setup ends up with the same thing, with several more similar errors during the process. During setup when it gets to interrupt announcer I can only skip, not continue, as pressing continue gives an error and does nothing.

Game version is retail 9.0.1 (36272) (Release x64)
Addon version is 6.0.8 however this exact same thing has been happening since 6.0.1

**Comment by Wutname1** [comment]
What is your bartender version?

try and reset your actions bars from /suihelp

**Comment by Melko22** [comment]
Bartender version is 4.10.3 stable release. Pressing the reset action bars from /suihelp does nothing, not even an error. I have tried disabling all addons except spartanui and bartender but results are the same.

**Comment by Ryzael75** [comment]
Simply disabling addons may not help. If you have any other addons that affect frame placement or bar control then even if you disable them, the cache files in your WTF folder will still be active and MAY cause conflicts. If it were me, I would cut/paste the Interface Folder and the WTF Folder to your desktop. Then login to game just to character select screen..then log back out. That will create brand new Interface/WTF Folders. Then install just SUI 6.0.8 and the current stable version of BT4. Then login and see if you still have same issues. If it seems fine then complete setup and start installing other addons 1 at a time and logging in after each install to see if there are any issues.

**Comment by Melko22** [comment]
Deleting the LUA files for SUI from the WTF folder seems to have solved the misalignment issue. During setup it's still impossible to move past certain modules by pressing continue but I'm starting to suspect there is some weird interaction with Prat 3 which is causing that. I still get a ton of errors when I log in, most of them returning (null) but the ones that aren't are related to Prat 3, which has not been updated to 9.0 and looking at the issues page shows similar errors from other people.

Why SUI seems to interact with a chat addon I'm not sure, but if I disable SUI then I don't get those erros from Prat 3.

**Comment by Ryzael75** [comment]
Because SUI has it's own chat module. It will conflict with Prat or any other chat addon unless you go into the module and disable the SUI one. Honestly I would just get rid of Prat since it's not been updated yet and just use the SUI one. It doesn't have all the customization options that Prat has...but to me Prat has way too many unnecessary options. SUI Chat has all the major options so is good enough for me.

**Comment by Wutname1** [comment]
> Because SUI has it's own chat module. It will conflict with Prat or any other chat addon unless you go into the module and disable the SUI one. Honestly I would just get rid of Prat since it's not been updated yet and just use the SUI one. It doesn't have all the customization options that Prat has...but to me Prat has way too many unnecessary options. SUI Chat has all the major options so is good enough for me. As for getting a bunch of null errors, you aren't the 1st to report that. I'm sure wutname1 is looking into that.

While I am not looking to replace prat, that is my goal to have the major options. So if there are any that I do not have please let me know. The only additional feature I am planning on adding right now is the sent message history

**Comment by Wutname1** [comment]
Going to close since you got your alignment issue figured out.
