### ISSUE TITLE
player and target classic

### ISSUE THREAD

**Issue by grump89** [Wutname1/SpartanUI#342]
now i have to move player and target together. was way better when i could keep them seperate. getting worse and worse i dont get it.

**Comment by Wutname1** [comment]
target is attached to the player frame, when you move the target it should detach from the player frame. same as it was before.

**Comment by hortlak007** [comment]
So Classic Artwork now working? Cuz I couldn't work it properly. Player frame is different and some error with it

https://gofile.io/d/1LwNAI

**Comment by hortlak007** [comment]
> target is attached to the player frame, when you move the target it should detach from the player frame. same as it was before.

So Classic Artwork now working? Cuz I couldn't work it properly. Player frame is different and some error with it

https://gofile.io/d/1LwNAI

**Comment by msisaransk** [comment]
Same problem

**Comment by Ryzael75** [comment]
unitframes are still being worked on. no eta on their completion yet.

**Comment by Wutname1** [comment]
https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814
