### ISSUE TITLE
sui move bug

### ISSUE THREAD

**Issue by randomcrazylady** [Wutname1/SpartanUI#343]
I can enter the /sui move without issue and move the frames around as needed, but once I've gotten everything positioned it doesn't let me out of sui move with the command. If I attempt to exit with the command I get an error, and I have to reload to get the move it frames to disappear again. The error is as follows:

15x SpartanUI\modules\MoveIt.lua:315: attempt to call upvalue 'print' (a nil value)
[string "@SpartanUI\modules\MoveIt.lua"]:315: in function `MoveIt'
[string "@SpartanUI\modules\MoveIt.lua"]:681: in function `?'
[string "@SpartanUI\core\Handlers\ChatCommands.lua"]:42: in function `?'
[string "@DataStore\libs\AceConsole-3.0\AceConsole-3.0-7.lua"]:94: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5073: in function <FrameXML\ChatFrame.lua:5019>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4737: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4773: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 description = "CORE: Is the movement system for SpartanUI"
 Enable = <function> defined @SpartanUI\modules\MoveIt.lua:673
 NewModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 SecureHook = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:336
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:395
 SetDefaultModulePrototype = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 baseName = "SpartanUI"
 name = "SpartanUI_Component_MoveIt"
 Options = <function> defined @SpartanUI\modules\MoveIt.lua:727
 IsEnabled = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 OnEnable = <function> defined @SpartanUI\modules\MoveIt.lua:720
 DisableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 OnInitialize = <function> defined @SpartanUI\modules\MoveIt.lua:661
 CreateMover = <function> defined @SpartanUI\modules\MoveIt.lua:337
 MoveIt = <function> defined @SpartanUI\modules\MoveIt.lua:290
 UpdateMover = <function> defined @SpartanUI\modules\MoveIt.lua:271
 RegisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 GetMover = <function> defined @SpartanUI\modules\MoveIt.lua:267
 Disable = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 IsHooked = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:493
 IsMoved = <function> defined @SpartanUI\modules\MoveIt.lua:221
 CalculateMoverPoints = <function> defined @SpartanUI\modules\MoveIt.lua:183
 IsModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 hooks = <table> {
 }
 SetDefaultModuleState = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 SendMessage = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 UnhookAll = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:477
 SetEnabledState = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 Unhook = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:418
 RegisterEvent = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SecureHookScript = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:410
 HookScript = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.lua:366
 UnregisterAllEvents = <function> defined @DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 IterateModules = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 defaultModuleState = true
 RawHook = <function> defined @Bartender4\libs\AceHook-3.0\AceHook-3.0.l

**Comment by Wutname1** [comment]
Are you able to hit escape and exit move it

**Comment by randomcrazylady** [comment]
Nope! when I hit escape it just opens my menu.

**Comment by Ryzael75** [comment]
I do recall 1 other person bringing this up couple days ago...not sure if here or on discord. It must be something pretty specific to the user since only 2 people have mentioned it.

**Comment by Wutname1** [comment]
So far I was only able to replicate by entering the movement system and then going into combat. If it happens after 6.0.9 let me know. 

> I do recall 1 other person bringing this up couple days ago...not sure if here or on discord. It must be something pretty specific to the user since only 2 people have mentioned it.

Correct, someone had the issue on discord a day or 2 ago. (feels like weeks ago)
