### ISSUE TITLE
Classic artstyle not showing.

### ISSUE THREAD

**Issue by Trollsngoblins** [Wutname1/SpartanUI#344]
Whenever I log in, I get a ton of options. However, I prefer the classic Spartan UI style.
But whenever I choose that, only the basic barframe shows. The playerframes, the targetframes etc all show up blank, being nothing more than healthbars, power/energy/rage bars and a floating 3D portrait.

![Problem1](https://user-images.githubusercontent.com/28574464/96351096-84ec3980-10b9-11eb-9b77-ee9841e83d9b.PNG)

**Comment by Wutname1** [comment]
Duplicate https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814
