### ISSUE TITLE
Health percentages

### ISSUE THREAD

**Issue by Eigerbahn** [Wutname1/SpartanUI#348]
How can i add health percentages to the health bars? I tried [percentagehealth] and [healthpercentage] and [healthpercent] and it does not work. Thanks in advance

**Comment by Ryzael75** [comment]
[perhp] for health and [perpp] for mana, focus, fury, combo, ect.

**Comment by Eigerbahn** [comment]
Thanks that worked. Seems petty but is there a way to add the % symbol?

**Comment by qualitaz** [comment]
Any static symbols like % can be added before/after the brackets and they will stay there in relative position to the brackets
[perhp]% - 100%
[perhp] % - 100 %
HP [perhp] % - HP 100 %
Or any other combinations of text/sign you might want.
