### ISSUE TITLE
Chat boxes [Improvement]

### ISSUE THREAD

**Issue by gustavolrcoelho** [Wutname1/SpartanUI#35]
Hey, I think that you could use the space on the sides to nest the chat boxes, pretty much like the ElvUI does.
It is a pain to set it all manually, especially if you have 12+ toons like I do. Also, it would make the ui look better, but unlike the ElvUI, please make the default chat buttons visible.

**Comment by Whatsatotem** [comment]
As long as its moveable - past 3 expantions i been using this addon, i gotten used to my chat box being at the top of my screen. and i have Details (Damage on the left, Healing on the right) in the spaces outside the UI frames
![wowscrnshot_060518_013812](https://user-images.githubusercontent.com/41389109/42913794-8419340c-8abc-11e8-8aab-d56e98ffb42c.jpg)

**Comment by gustavolrcoelho** [comment]
I understand, but having this feature would be nice, please consider it :)

**Comment by Wutname1** [comment]
Chatbox handling has been on my bucket list for awhile. If anyone has more comments or ideas for options please post them here.

**Comment by Whatsatotem** [comment]
as long as it has the customization Prat has, ill be fine xD

**Comment by gustavolrcoelho** [comment]
Well, I think that instead a 4x3 on the left and right sides, the bar could be 3x4 and a similar box art could embed the chat box. I made a little mistake in the paint edit and the yellow line is a bit above the top border of the portrait. I intended for it be at the same height.
![42913794-8419340c-8abc-11e8-8aab-d56e98ffb42c](https://user-images.githubusercontent.com/40846053/42945839-cd42f48c-8b3f-11e8-943a-d61587521a25.jpg)

**Comment by Whatsatotem** [comment]
since chatbox customization is a thing your working on anyway, is there a way to add a feature that adds a type of notification beep when you get a message (i ask since its been nearly 5 days now, and [I Hear You All] hasnt been updated :P

**Comment by Caerdon** [comment]
I'd mostly like to see the chat box be collapsible.  Perhaps with an indicator of message activity that you care about.
