### ISSUE TITLE
Classic UnitFrames not visible upon game load

### ISSUE THREAD

**Issue by Girbilcannon** [Wutname1/SpartanUI#351]
Whenever I launch the game (in classic not retail), the SpartanUI UnitFrames do not load, and I am met with 3 errors. Disabling the UnitFrames module in SpartanUI takes away 2 of the 3 errors and brings back the original game UnitFrames. I will post the errors as comments here to keep them separated. As stated, these errors are specifically for WoW Classic and not Retail.

**Comment by whitecrow1** [comment]
[Error 00000244137FE4F0] captured, click the link for more information.
[Error 00000244130BFA00] captured, click the link for more information.
[Error 00000244130BFA00] captured, click the link for more information.
[Error 00000244130BFE60] captured, click the link for more information.
===============================================

Interface\AddOns\SpartanUI\libs\oUF\events.lua:146: Attempt to register unknown event "UNIT_POWER_POINT_CHARGE"
[C]: ?
Interface\AddOns\SpartanUI\libs\oUF\events.lua:146: in function `RegisterEvent'
...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:284: in function <...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:279>
...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:241: in function <...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:192>
(tail call): ?
Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:226: in function `UpdateAllElements'
...\AddOns\SpartanUI\modules\UnitFrames\SpawnFrames.lua:523: in function `UpdateAuras'
...\AddOns\SpartanUI\modules\UnitFrames\SpawnFrames.lua:318: in function `UpdateAll'
...\AddOns\SpartanUI\modules\UnitFrames\SpawnFrames.lua:1228: in function `SpawnFrames'
...ce\AddOns\SpartanUI\modules\UnitFrames\Framework.lua:222: in function <...ce\AddOns\SpartanUI\modules\UnitFrames\Framework.lua:182>
[C]: ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:70: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:527: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:540: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua:630: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by whitecrow1** [comment]
Interface\FrameXML\MultiActionBars.lua:62: attempt to compare number with nil
Interface\FrameXML\MultiActionBars.lua:62: in function `MultiActionBar_Update'
Interface\FrameXML\InterfaceOptionsPanels.lua:1175: in function `InterfaceOptions_UpdateMultiActionBars'
[string "*:OnLoad"]:4: in function `setFunc'
Interface\FrameXML\InterfaceOptionsPanels.lua:1145: in function <Interface\FrameXML\InterfaceOptionsPanels.lua:1138>
showLeft = "1"
showRight = "1"
maxWidth = 84
topLimit = 852
bottomLimit = 8
(*temporary) = nil
(*temporary) = 2327.259521
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = 2427.259521
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
UpdateMultiActionBar = <function> defined @Interface\FrameXML\MultiActionBars.lua:34

**Comment by whitecrow1** [comment]
...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:137: attempt to call global 'GetUnitChargedPowerPoints' (a nil value)
...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:137: in function <...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:97>
(tail call): ?
...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:292: in function <...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:279>
...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:241: in function <...ce\AddOns\SpartanUI\libs\oUF\elements\classpower.lua:192>
(tail call): ?
Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:226: in function <Interface\AddOns\SpartanUI\libs\oUF\ouf.lua:207>
(tail call): ?

**Comment by whitecrow1** [comment]
The second error posted above is the only error that remains if I turn off the unit frames module, and it looks like it has something to do with action bars, but it only pops up when the game loads, so I'm not sure about that one.

**Comment by Percula5470** [comment]
I have the same Problem in WoW RETAIL !!!   23.Okt.2020
There are NO Unit-Frames shown. Not in single action. Not in group or else.
I tried out other skins but the same Problem.
