### ISSUE TITLE
UI won't auto adjust for Titan panel

### ISSUE THREAD

**Issue by jb4479** [Wutname1/SpartanUI#352]
I'm not sure if this an error with SpartanUI or Titan Penel. When ever the screen refreshes Spartan places the UI back on the bottom instead on top of Titan Panel (I use the bottom bars)

![WoWScrnShot_101920_201133](https://user-images.githubusercontent.com/16572065/96531706-7895e700-1247-11eb-86a7-8f416fc59602.jpg)

If I go into SpartanUI options and reselect the artwork the screen adjusts as it should (until the next refresh)

![WoWScrnShot_101920_201325](https://user-images.githubusercontent.com/16572065/96531838-c3affa00-1247-11eb-86ac-354f72fab83b.jpg)

**Comment by hortlak007** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/37478236/96534426-5e382980-1298-11eb-9b7a-b0d988beecfd.png)
same here with lua error

**Comment by Wutname1** [comment]
> ![Screenshot_1](https://user-images.githubusercontent.com/37478236/96534730-fc2bf400-1298-11eb-9b8c-5a37da0f3e91.png)
> 
> Same here. Classic Artwork not fixed yet.

Thats prat. it is not updated for shadowlands.

**Comment by siberia60** [comment]
Hey.

I am also getting the same issue. (Not using PRAT - Chat addon)

**Comment by siberia60** [comment]
Returning here with some more info.

After logging in, if I do /sui and go into General -> Artwork and click on the artwork I have selected (In my case Arcane) it realigns propperly.

**Comment by Wutname1** [comment]
> After logging in, if I do /sui and go into General -> Artwork and click on the artwork I have selected (In my case Arcane) it realigns propperly.

Perfect thanks for this that means it is not detecting titan panel on load but the code to detect it on skin change works. should be able to get a fix in for it latter today

**Comment by siberia60** [comment]
Don't want to butt in, but.

Dosn't that means that SUI loads before TP?

So the UI loads, then TP loads, and due to the order the code to detect it runs it's cycle, dosn't find the panel bars, and then the panel bars load, hence the UI dosn't adjust for them, but if you change the skin then the code finds the bars and adjusts?
