### ISSUE TITLE
Unitframes doesn't change when selecting Classic Art Style

### ISSUE THREAD

**Issue by Maaggel** [Wutname1/SpartanUI#353]
When selecting the Classic Art Style, the unit frames doesn't change.
This has only started happening after the 9.0.1 WoW release - and the addon is up to date.
I've tested this with every other addon removed, to isolate this to SUI.

If I change Art Style the character frame "flashes", so something happens - but the artstyle is always stuck on the default one.
There doesn't seem to be any LUA errors when changing artstyle.
I've tried changing the artwork in "Overall Style", "Artwork Style", "Unitframe Style" in the General->Art Style section, aswell as trying in the Modules -> Unit frames section.

![image](https://user-images.githubusercontent.com/8314626/96553956-32c43780-12b6-11eb-8837-847d53fc2b7e.png)
![image](https://user-images.githubusercontent.com/8314626/96556285-15dd3380-12b9-11eb-8cfb-8b506e2f6481.png)

**Comment by Maaggel** [comment]
Closed - The bug was already created:
https://github.com/Wutname1/SpartanUI/issues/323

**Comment by Wutname1** [comment]
https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814
