### ISSUE TITLE
Lua errors

### ISSUE THREAD

**Issue by spiderman82** [Wutname1/SpartanUI#354]
1x SpartanUI\modules\UnitFrames\SpawnFrames.lua:1420: attempt to index field '?' (a nil value)
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:1420: in function `UpdateAll'
[string "@SpartanUI\modules\UnitFrames\Framework.lua"]:256: in function `SetActiveStyle'
[string "@SpartanUI\core\Options-Параметры.lua"]:60: in function <SpartanUI\core\Options.lua:58>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-Icon.lua"]:26: in function <...ender4\libs\AceGUI-3.0\widgets\AceGUIWidget-Icon.lua:25>

**Comment by spiderman82** [comment]
2x SpartanUI\Themes\Classic\Global-Framework.lua:24: attempt to index field '?' (a nil value)
[string "@SpartanUI\Themes\Classic\Global-Framework.lua"]:24: in function `SetColor'
[string "@SpartanUI\Themes\Classic\Style.lua"]:603: in function <SpartanUI\Themes\Classic\Style.lua:601>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-ColorPicker.lua"]:28: in function <...libs\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:21>
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-ColorPicker.lua"]:67: in function `opacityFunc'
[string "*:OnValueChanged"]:2: in function <[string "*:OnValueChanged"]:1>
[string "=[C]"]: in function `SetValue'
[string "*:OnShow"]:3: in function <[string "*:OnShow"]:1>
[string "=[C]"]: in function `Show'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-ColorPicker.lua"]:80: in function <...libs\AceGUI-3.0\widgets\AceGUIWidget-ColorPicker.lua:49>

**Comment by spiderman82** [comment]
1x SpartanUI\libs\oUF\blizzard.lua:81: Frame PlayerFrame is not movable or resizable
[string "=[C]"]: in function `SetUserPlaced'
[string "@SpartanUI\libs\oUF\blizzard.lua"]:81: in function `DisableBlizzard'
[string "@SpartanUI\libs\oUF\ouf.lua"]:780: in function `Spawn'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:1225: in function `SpawnFrames'
[string "@SpartanUI\modules\UnitFrames\Framework.lua"]:222: in function <...ceSpartanUI\modules\UnitFrames\Framework.lua:182>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by spiderman82** [comment]
1x SpartanUI\modules\UnitFrames\SpawnFrames.lua:1420: attempt to index field '?' (a nil value)
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:1420: in function `UpdateAll'
[string "@SpartanUI\modules\UnitFrames\Framework.lua"]:256: in function `SetActiveStyle'
[string "@SpartanUI\modules\Artwork\Framework.lua"]:38: in function <...rfaceSpartanUI\modules\Artwork\Framework.lua:31>
[string "=[C]"]: ?
[string "=[C]"]: in function `Click'
[string "@SpartanUI\modules\Artwork\Framework.lua"]:29: in function <...rfaceSpartanUI\modules\Artwork\Framework.lua:28>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EnableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 CancelTimer = <function> defined @SpartanUI\libs\AceTimer-3.0\AceTimer-3.0.lua:147
 IterateEmbeds = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 defaultModuleLibraries = <table> {
 }
 TimeLeft = <function> defined @SpartanUI\libs\AceTimer-3.0\AceTimer-3.0.lua:172
 LoadDB = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:161
 ScheduleRepeatingTimer = <function> defined @SpartanUI\libs\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @SpartanUI\libs\AceTimer-3.0\AceTimer-3.0.lua:160
 SetDefaultModulePrototype = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:409
 DisplayName = "Рамки юнитов"
 baseName = "SpartanUI"
 name = "SpartanUI_Component_UnitFrames"
 SendMessage = <function> defined @Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 IsEnabled = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 ScheduleTimer = <function> defined @SpartanUI\libs\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:350
 GetName = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 UpdateGroupFrames = <function> defined @SpartanUI\modules\UnitFrames\SpawnFrames.lua:1430
 UpdateAll = <function> defined @SpartanUI\modules\UnitFrames\SpawnFrames.lua:1418
 SpawnFrames = <function> defined @SpartanUI\modules\UnitFrames\SpawnFrames.lua:1219
 RegisterMessage = <function> defined @Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 frames = <table> {
 }
 FramePos = <table> {
 }
 IsFriendlyFrame = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:55
 CurrentSettings = <table> {
 }
 SetActiveStyle = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:249
 IsModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 OnEnable = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:182
 SetDefaultModuleState = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:387
 OnInitialize = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:173
 PositionFrame = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:114
 SetEnabledState = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 TextFormat = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:71
 enabledState = true
 GetModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 RegisterEvent = <function> defined @Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 LoadFunction = <function> defined @SpartanUI\modules\UnitFrames\Framework.lua:317
 UnregisterAllEvents = <function> defined @Bartender4\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 UpdateText = <function> defined @SpartanUI\modules\UnitFrames

**Comment by spiderman82** [comment]
1x SpartanUI\libs\oUF\blizzard.lua:81: Frame PlayerFrame is not movable or resizable
[string "=[C]"]: in function `SetUserPlaced'
[string "@SpartanUI\libs\oUF\blizzard.lua"]:81: in function `DisableBlizzard'
[string "@SpartanUI\libs\oUF\ouf.lua"]:780: in function `Spawn'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:1225: in function `SpawnFrames'
[string "@SpartanUI\modules\UnitFrames\Framework.lua"]:222: in function <...ceSpartanUI\modules\UnitFrames\Framework.lua:182>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:520>
[string "=(tail call)"]: ?
[string "@SpartanUI\core\Handlers\Modules.lua"]:107: in function <SpartanUI\core\Handlers\Modules.lua:100>
[string "=[C]"]: ?

**Comment by spiderman82** [comment]
1x SpartanUI\modules\CombatLog.lua:435: attempt to index local 'cLog' (a nil value)
[string "@SpartanUI\modules\CombatLog.lua"]:435: in function `Next'
[string "@SpartanUI\core\Handlers\SetupWizard.lua"]:300: in function <...rfaceSpartanUI\core\Handlers\SetupWizard.lua:297>

Locals:
window = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 GetChildrenWidgets = <function> defined @SpartanUI\libs\StdUi\StdUi.lua:49
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 Desc1 = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 Skip = <unnamed> {
 }
 SetWindowTitle = <function> defined @SpartanUI\libs\StdUi\widgets\Window.lua:29
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 Desc2 = <unnamed> {
 }
 content = SUI_Window_Content {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 closeBtn = <unnamed> {
 }
 ProgressBar = <unnamed> {
 }
 SubTitle = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 TopRightCorner = <unnamed> {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 Status = <unnamed> {
 }
 Title = <unnamed> {
 }
 StdUi = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 0 = <userdata>
 Next = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 titlePanel = <unnamed> {
 }
 Center = <unnamed> {
 }
 isWidget = true
 backdropInfo = <table> {
 }
 MakeResizable = <function> defined @SpartanUI\libs\StdUi\widgets\Window.lua:34
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
}
cLog = nil
(*temporary) = "SetupWizard"
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 window = <unnamed> {
 }
 baseName = "SpartanUI"
 Enable = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 OnInitialize = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:426
 EnableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 IsModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 OnEnable = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:324
 defaultModuleLibraries = <table> {
 }
 SetupWizard = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:215
 FindNextPage = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:76
 SetEnabledState = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 DisplayPage = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:185
 enabledState = true
 AddPage = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:47
 moduleName = "SetupWizard"
 GetName = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 Disable = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 IterateModules = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:437
 name = "Sp

**Comment by spiderman82** [comment]
1x SpartanUI\modules\TauntWatcher.lua:426: attempt to index local 'TauntWatch' (a nil value)
[string "@SpartanUI\modules\TauntWatcher.lua"]:426: in function `Next'
[string "@SpartanUI\core\Handlers\SetupWizard.lua"]:300: in function <...rfaceSpartanUI\core\Handlers\SetupWizard.lua:297>

Locals:
window = <unnamed> {
 BottomLeftCorner = <unnamed> {
 }
 GetChildrenWidgets = <function> defined @SpartanUI\libs\StdUi\StdUi.lua:49
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 Desc1 = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 RightEdge = <unnamed> {
 }
 Skip = <unnamed> {
 }
 SetWindowTitle = <function> defined @SpartanUI\libs\StdUi\widgets\Window.lua:29
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 Desc2 = <unnamed> {
 }
 content = SUI_Window_Content {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 closeBtn = <unnamed> {
 }
 ProgressBar = <unnamed> {
 }
 SubTitle = <unnamed> {
 }
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 TopRightCorner = <unnamed> {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 Status = <unnamed> {
 }
 Title = <unnamed> {
 }
 StdUi = <table> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 0 = <userdata>
 Next = <unnamed> {
 }
 TopEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
 titlePanel = <unnamed> {
 }
 Center = <unnamed> {
 }
 isWidget = true
 backdropInfo = <table> {
 }
 MakeResizable = <function> defined @SpartanUI\libs\StdUi\widgets\Window.lua:34
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
}
TauntWatch = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = <table> {
 SetDefaultModuleLibraries = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:367
 window = <unnamed> {
 }
 baseName = "SpartanUI"
 Enable = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:294
 NewModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:235
 OnInitialize = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:426
 EnableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:442
 IsModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:217
 OnEnable = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:324
 defaultModuleLibraries = <table> {
 }
 SetupWizard = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:215
 FindNextPage = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:76
 SetEnabledState = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:424
 DisplayPage = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:185
 enabledState = true
 AddPage = <function> defined @SpartanUI\core\Handlers\SetupWizard.lua:47
 moduleName = "SetupWizard"
 GetName = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:279
 defaultModuleState = true
 Disable = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:314
 IterateModules = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.

**Comment by spiderman82** [comment]
1x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua:1863: AceConfigRegistry-3.0-20:ValidateOptionsTable(): SpartanUI.args.ModSetting.args.Nameplates.enabled: unknown parameter
[string "=[C]"]: ?
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:50: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:45>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:238: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:254: in function <...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:219>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:282: in function ValidateOptionsTable' [string "@Bartender4\libs\AceConfig-3.0-3\AceConfigRegistry-3.0\AceConfigRegistry-3.0-20.lua"]:324: in function app'
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:1863: in function Open' [string "@SpartanUI\core\Framework.lua"]:2363: in function <SpartanUI\core\Framework.lua:2359> [string "=[C]"]: ? [string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49> [string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664> [string "=[C]"]: ? [string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:70> [string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function Fire'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-Button.lua"]:22: in function <...der4\libs\AceGUI-3.0\widgets\AceGUIWidget-Button.lua:19>

**Comment by Ryzael75** [comment]
The first 5 of those seem to be related to unitframes and the classic artwork...artwork and unitframes are still being worked on with no current completion time. The other 4...combat log, interrupt announcer, taunt watcher, and nameplates...seems it has something to do with the setup wizard. If you haven't yet, update to yesterday's release SUI 6.0.9. That newest version was supposed to take care of setup wizard related errors.

**Comment by Wutname1** [comment]
update spartanui and open a new issue for any errors. please try to keep a issue to 1 error.
