### ISSUE TITLE
Got this one Error left

### ISSUE THREAD

**Issue by Shiroh27** [Wutname1/SpartanUI#355]
After all the prepatch updates this is the last error message i´m still receiving everytime i log in.

1x SpartanUI\libs\oUF\blizzard.lua:81: Frame PlayerFrame is not movable or resizable
[string "=[C]"]: in function `SetUserPlaced'
[string "@SpartanUI\libs\oUF\blizzard.lua"]:81: in function `DisableBlizzard'
[string "@SpartanUI\libs\oUF\ouf.lua"]:780: in function `Spawn'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:1225: in function `SpawnFrames'
[string "@SpartanUI\modules\UnitFrames\Framework.lua"]:222: in function <...ceSpartanUI\modules\UnitFrames\Framework.lua:182>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:495: in function `UIParentLoadAddOn'
[string "@Rarity\Core\Collections-Sammlungen.lua"]:63: in function `ScanToys'
[string "@Rarity\Core\Collections-Sammlungen.lua"]:307: in function `ScanExistingItems'
[string "@Rarity\Core.lua"]:196: in function `DoEnable'
[string "@Rarity\Core.lua"]:165: in function <Rarity\Core.lua:164>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Wutname1** [comment]
Classic or retail?

**Comment by Shiroh27** [comment]
retail WoW
