### ISSUE TITLE
What I find not working.

### ISSUE THREAD

**Issue by Ridgid1** [Wutname1/SpartanUI#357]
Spartan has been the best UI to play wow, for years now.   But here is what I find is not working correctly.

First,  if I change my font size in chat to say 16pt, it changes, but when I log off and on or do a /console reloadui, it doesn't save it.  

Second,  I put several different bars up....  which should be independent of  Spartanui, however, your locking bartender to Spartanui, there needs to be some type of separation to them.  That move me option just screws with everything.

Third,  Player frames will not let me choose the  frame I would like, in this case Classic, can't get it there no matter what I do.

And last, when I go into my add-on and UN-check "load out of date" add-ons, I find all the add-ons except for the actual "Spartanui" in red, meaning out of date...   Such as SpartanUI_Artwork, FilmEffects, PartyFrames and so on...   I currently have them de-selected...  doesn't seem to make a difference if I have them selected or not to use Spartanui in its current form.

Spartanui is still the cleanest out there, I  for one hope you keep up the great work.   

Thanks for looking at this... have a great day...

**Comment by Wutname1** [comment]
> First, if I change my font size in chat to say 16pt, it changes, but when I log off and on or do a /console reloadui, it doesn't save it.

Change it via the SUI settings not the blizzard ui

> Second, I put several different bars up.... which should be independent of Spartanui, however, your locking bartender to Spartanui, there needs to be some type of separation to them. That move me option just screws with everything.

BT4 has always been tied to SUI. Overriding it's movement system fixes way more issues than it creates. 

> Third, Player frames will not let me choose the frame I would like, in this case Classic, can't get it there no matter what I do.

See reason why here: https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814

> And last, when I go into my add-on and UN-check "load out of date" add-ons, I find all the add-ons except for the actual "Spartanui" in red, meaning out of date... Such as SpartanUI_Artwork, FilmEffects, PartyFrames and so on... I currently have them de-selected... doesn't seem to make a difference if I have them selected or not to use Spartanui in its current form.

Mouse over one it tells you they are legacy and not used. Blame twitch for not letting me delete old folders via their updater.
