### ISSUE TITLE
Class 

### ISSUE THREAD

**Issue by puddiinn** [Wutname1/SpartanUI#359]
When Psartan did its last update it totally screwed everything up.  I had to unload everything and reload it than restart my computer.  After all of that my player bars are still all wacked and I can not get a different design for them.  Plus I can no longer tell what class each players are now.  Is there a way to fix this?  I really really like Spartan UI but am about ready to get rid of it and go back to the old one I was using.

Please help.
![20201024_211422](https://user-images.githubusercontent.com/73414928/97098833-deff7880-163e-11eb-9277-d42456caa10d.jpg)
![Uploading 20201024_211432.jpg…]()

**Comment by puddiinn** [comment]
![Uploading 20201024_211432.jpg…]()

**Comment by Wutname1** [comment]
https://github.com/Wutname1/SpartanUI/issues/323#issuecomment-708524814

As for class.. 
![image](https://user-images.githubusercontent.com/704321/97099066-5559a600-1652-11eb-86b0-fbaba6410da9.png)
