### ISSUE TITLE
Buffs/Debuffs - BFA

### ISSUE THREAD

**Issue by Sorgblad** [Wutname1/SpartanUI#360]
Is there a way to set buffs/debuffs as a line bar instead of a square like before in BFA? Couldn't find it anywhere anymore.  
![image](https://user-images.githubusercontent.com/73495267/97216690-7f33d980-17c6-11eb-95ea-5c79a99e1f96.png)

**Comment by Wutname1** [comment]
not at the moment but it will be returning
