### ISSUE TITLE
Mana bar 

### ISSUE THREAD

**Issue by ChitfoBrainz** [Wutname1/SpartanUI#361]
Just updated off twitch today and logged in and found on my character window the mana bar is grey/white and there is no numbers to show amount of mana left , and the bar is a bit longer and is overlapping into the 3d picture of my toon , but if i click myself the bar is right on my target window, any ideas what is wrong or how to make it right ?

**Comment by Wutname1** [comment]
Classic or retail?

**Comment by ChitfoBrainz** [comment]
classic

**Comment by ChitfoBrainz** [comment]
and if you try to resize the player unit frame you can see the blue bar a little bit when you move it all the way one way and see the number amount of mana when you move it the other

**Comment by Wutname1** [comment]
Fixed: 24ebd6af83888fc3d103de05413577661775dec0
