### ISSUE TITLE
enhancement buff/debuff bars instead of icons.

### ISSUE THREAD

**Issue by raineday** [Wutname1/SpartanUI#363]
Older versions of SUI had buff/debuff options for bars is that going to be an option in the future. I moved an element of CTMod to demonstrate the bars
![image](https://user-images.githubusercontent.com/5045511/97661004-c923f600-1a38-11eb-8a74-8a5e23ec59e9.png)

**Comment by Wutname1** [comment]
Yes they will be returning.
