### ISSUE TITLE
LUA errors in Wow Classic

### ISSUE THREAD

**Issue by davidmarshall15** [Wutname1/SpartanUI#365]
version 6.0.12-11-g8100419

38x SpartanUI\modules\UnitFrames\SpawnFrames.lua:1434: attempt to call method 'Hide' (a nil value)
SpartanUI\modules\UnitFrames\SpawnFrames.lua:1434: in function `UpdateAll'
SpartanUI\modules\UnitFrames\SpawnFrames.lua:1489: in function `UpdateGroupFrames'
SpartanUI\modules\UnitFrames\SpawnFrames.lua:1463: in function <SpartanUI\modules\UnitFrames\SpawnFrames.lua:1453>
[C]: ?
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...nts\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...\common\Wildpants\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by Wutname1** [comment]
Fixed https://github.com/Wutname1/SpartanUI/commit/38a98b5229b0bc0dd12dbff77644b1fafea65830
