### ISSUE TITLE
UnitFrame Hunter Pet not visible

### ISSUE THREAD

**Issue by Percula5470** [Wutname1/SpartanUI#371]
The "Classic".UnitFrame in RETAIL is not visible.

**Comment by Shaanea** [comment]
yes.. the rest is working again.. thank god

**Comment by Percula5470** [comment]
![hunterpetframe](https://user-images.githubusercontent.com/73362358/99740861-1ba08180-2ad0-11eb-9ccc-1f13e84745e7.jpg)

Hunter Pet Unit frame is still missing in retail !
