### ISSUE TITLE
Chat errors with my spartanUI (ruined general chat for me)

### ISSUE THREAD

**Issue by CrackerJackz** [Wutname1/SpartanUI#372]
Hey i just downloaded spartanui today and finally got everything set up but after i did that started looking at the chat and noticed that there were nothing but error messages. The messages flood my chat anytime i target anything or switch targets, also there are multiple error codes that are occuring and im really not sure what is wrong with it but anyways here is a link to what my chat looks like with all the errors. https://gyazo.com/d201eae53986620c3bc86544be200bc3

**Comment by martinelli9** [comment]
I have this same problem, can someone help me? please

**Comment by Wutname1** [comment]
BugSack - https://www.curseforge.com/wow/addons/bugsack
BugGrabber -  https://www.curseforge.com/wow/addons/bug-grabber
These will put the errors into a bag icon on your minimap and make them less annoying.

The screenshot does not tell me anything it could be any addon causing those.
