### ISSUE TITLE
Unable to move "runes""combat points""pally power" 

### ISSUE THREAD

**Issue by raineday** [Wutname1/SpartanUI#375]
12x ...faceSpartanUI\modules\UnitFrames\Options-Options.lua:1038: attempt to index field 'position' (a nil value)
[string "@SpartanUI\modules\UnitFrames\Options-Options.lua"]:1038: in function <...faceSpartanUI\modules\UnitFrames\Options.lua:1034>
[string "=[C]"]: ?
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:843: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:664>
[string "@Ace3\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-79.lua"]:895: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:883>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Slider.lua"]:69: in function <...dOns\Ace3\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:60>

**Comment by Wutname1** [comment]
Fixed in: [8f5fc30d5ff0686977ce88a80aafad2ac2189ba2](https://github.com/Wutname1/SpartanUI/commit/8f5fc30d5ff0686977ce88a80aafad2ac2189ba2)
