### ISSUE TITLE
Some Classic Unitframes are skewed.

### ISSUE THREAD

**Issue by Magikaman** [Wutname1/SpartanUI#380]
I was setting up the UI and when I was finished setting up on my warlock I noticed that both the Pet Unitframe classic skin wasn't even showing up. 
I also hit F1 to target self and the classic skin for the TargetTarget frame is warped. when I enabled the classic skin it didn't show up normally but it was more stretched vertically.

I will test for other frames too.

**Comment by loriwood01** [comment]
I seem to be having a similar issue - just updated to the newest version and TargetTarget and the frames in the top left don't have the classic skin

**Comment by Mike160770** [comment]
the classic skin is still under development - will not be final till version 6.1
