### ISSUE TITLE
Mass error messages.... 

### ISSUE THREAD

**Issue by Ziggy1982** [Wutname1/SpartanUI#381]
Message: [string "TRZ_WorldMap_Frame:OnUpdate"]:1: attempt to call global 'TRZ_WorldMapButton_OnUpdate' (a nil value)
Time: Sun Nov 15 14:06:44 2020
Count: 3887
Stack: [string "TRZ_WorldMap_Frame:OnUpdate"]:1: attempt to call global 'TRZ_WorldMapButton_OnUpdate' (a nil value)
[string "*:OnUpdate"]:1: in function <[string "*:OnUpdate"]:1>

Locals: self = TRZ_WorldMap_Frame {
 0 = <userdata>
}
elapsed = 0.010000
(*temporary) = nil
(*temporary) = 12024
(*temporary) = "attempt to call global 'TRZ_WorldMapButton_OnUpdate' (a nil value)"

**Comment by Wutname1** [comment]
TRZ_WorldMapButton is causing the errors
