### ISSUE TITLE
Bar Sizing

### ISSUE THREAD

**Issue by rcollins0031** [Wutname1/SpartanUI#386]
Everytime I update the size of my bars, it resets after I log out.

**Comment by BvrnBrbrn** [comment]
Same here, everytime i leload the Stancebar resets his scale

**Comment by NoraHub** [comment]
I had the same issue, but for now it works if you use the bt4 settings to rescale bars. After a reload the position will be out of whack, but if you then reposition the bar again with the SUI positioning system the scale AND position stick.
