### ISSUE TITLE
Nameplate Errors

### ISSUE THREAD

**Issue by randomcrazylady** [Wutname1/SpartanUI#39]
Here's the full error report:

5x SpartanUI\components\Nameplates.lua:71: attempt to index field 'NamePlates' (a nil value)
SpartanUI\components\Nameplates.lua:71: in function `styleFunc'
SpartanUI\libs\oUF\ouf.lua:321: in function <SpartanUI\libs\oUF\ouf.lua:245>
(tail call): ?
SpartanUI\libs\oUF\ouf.lua:759: in function <SpartanUI\libs\oUF\ouf.lua:730>

Locals:
frame = oUF_Spartan_NamePlatesNamePlate1 {
 0 = <userdata>
 isNamePlate = true
 id = "1"
 PLAYER_ENTERING_WORLD = <function> defined @SpartanUI\libs\oUF\ouf.lua:200
 unit = "nameplate1"
 bgHealth = <unnamed> {
 }
 Health = <unnamed> {
 }
 style = "Spartan_NamePlates"
 UNIT_PET = <function> defined @SpartanUI\libs\oUF\ouf.lua:228
 UNIT_EXITING_VEHICLE = <function> defined @SpartanUI\libs\oUF\ouf.lua:46
 UNIT_EXITED_VEHICLE = <function> defined @SpartanUI\libs\oUF\ouf.lua:46
 __elements = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @SpartanUI\libs\oUF\ouf.lua:46
}
unit = "nameplate1"
health = <unnamed> {
 0 = <userdata>
 colorTapping = true
 colorReaction = true
}
nameString = ""
(*temporary) = nil
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0.5
(*temporary) = <userdata>
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = "attempt to index field 'NamePlates' (a nil value)"
BarTexture = "SpartanUI\media\Smoothv2.tga"
SUI = <table> {
 SetDefaultModuleLibraries = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 DBUpgrades = <function> defined @SpartanUI\core\Framework.lua:1042
 oUF = <table> {
 }
 EnableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "SpartanUI"
 IterateEmbeds = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 RaidFrames = SUI_RaidFrameHeader {
 }
 FirstTimeSetup = <function> defined @SpartanUI\core\Framework.lua:690
 FontRefresh = <function> defined @SpartanUI\core\Framework.lua:1460
 BuildNum = "85"
 SetDefaultModulePrototype = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 PartyFrames = SUI_PartyFrameHeader {
 }
 defaultModuleState = true
 IsEnabled = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 DisableModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 RegisterMessage = <function> defined @AtlasLoot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 GetArgs = <function> defined @Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:144
 GetFontFace = <function> defined @SpartanUI\core\Framework.lua:1394
 BT4ProfileAttach = <function> defined @SpartanUI\core\Framework.lua:1060
 SetEnabledState = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 enabledState = true
 RegisterEvent = <function> defined @AtlasLoot\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 IterateModules = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 Version = "4.6.0"
 Err = <function> defined @SpartanUI\core\Framework.lua:1299
 suihelp = <function> defined @SpartanUI\core\Framework.lua:1260
 OnInitialize = <function> defined @SpartanUI\core\Framework.lua:975
 RegisterChatCommand = <function> defined @Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:85
 reloadui = <function> defined @SpartanUI\core\Framework.lua:1162
 GetModule = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:241
 BT4RefreshConfig = <function> defined @SpartanUI\core\Framework.lua:1102
 round = <function> defined @SpartanUI\core\Framework.lua:1363
 UnregisterChatCommand = <function> defined @Bartender4\libs\AceConsole-3.0\AceConsole-3.0.lua:111
 opt = <table> {
 }
 SpartanUIDB = <table> {
 }
 WhatsNew = <function> defined @SpartanUI\core\WhatsNew.lua:5
 GetName = <function> defined @Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 RegisterCallback = <function> defined @AtlasLoot\Libs\CallbackHandler-1.0\C

**Comment by Wutname1** [comment]
can you open /suihelp? (and it not be blank) That sounds like a error on one of the alpha builds and is fixed in 4.6.3
