### ISSUE TITLE
/spin does not work at all

### ISSUE THREAD

**Issue by yaddanadda** [Wutname1/SpartanUI#392]
I still get afk spin either when I've been idle long or when I type /afk but typing /spin returns an error message.  When I looked into SUI under the Modules AFK Effects, I can click toggle effects to start and stop spin manually.  When I used it, the chat box displayed "SpinCam: Spinning, to stop type /spin again"

Yet typing /spin gets me "Type '/help' for a listing of a few commands"

https://i.imgur.com/2R6TvmW.png

I think somehow /spin command got removed or blocked somewhere.

**Comment by Wutname1** [comment]
command was changed to `/sui spin` in SUI 6
