### ISSUE TITLE
Hunter Pet and Goal of Goal UnitFrame not working!!!

### ISSUE THREAD

**Issue by Percula5470** [Wutname1/SpartanUI#393]
The Hunter Pet and Goal of Goal UnitFrame not working!!!
And the Party and Raid Frames are also not working!

![WoWScrnShot_121020_105049](https://user-images.githubusercontent.com/73362358/101756421-4a5db680-3ad6-11eb-8e89-bf08552cd998.jpg)

**Comment by KalQulate** [comment]
Have same issue. No answers? :(

**Comment by Wutname1** [comment]
Not a bug. Not Broken.

https://github.com/Wutname1/SpartanUI/issues/323

**Comment by KalQulate** [comment]
Not a bug.
Not broken.

That made no sense to me :=)

Working as intended then? hehe

**Comment by Wutname1** [comment]
Correct, see #323
