### ISSUE TITLE
Cast bar fix ETA/workaround?

### ISSUE THREAD

**Issue by JamieB72** [Wutname1/SpartanUI#394]
I was just wondering if there's an ETA on having the cast bar freezing bug fixed? (assuming this remains a problem with the current version overall, and not just specific to me)

I'm a Rogue trying to progress in Naxx at the moment, and not being able to see the cast bar is starting to get unmanageable. I keep telling myself that the fix will come out any day now, but I haven't been able to interrupt casts properly for well over a month now. 

Is there an ETA on when this might get fixed, or should I just bite the bullet and go with another UI till this gets fixed? I absolutely love Spartan UI, but the fact it overrides the Blizzard Cast Bar, so I can't have any form of notification is getting too much to handle. I don't want to be responsible for my raid members dying because of the AddOns I choose to use.

**Comment by Wutname1** [comment]
> overrides the Blizzard Cast Bar

Classic has no castbar for anyone other than yourself.
