### ISSUE TITLE
Cannot disable party/raid frames.

### ISSUE THREAD

**Issue by taiiro** [Wutname1/SpartanUI#395]
I'm having problems disabling the party/raid frames from the UI. On my healers, I use Vuhdo, and therefore don't really need the party/raid frames. When I try to disable them, they disappear for a brief moment, and then come back within seconds. Something interesting I've noticed, though I'm not sure how relevant it is, is that when they are enabled, there isn't a 3D character next to the names. When they are disabled and come back, suddenly the 3D characters are there. I'm unsure what the problem is, and greatly appreciate any help or advice! Thank you for taking the time to read this and for your help!

**Comment by Wutname1** [comment]
Resolved in todays update
