### ISSUE TITLE
LARGE NUMBER SEPERATOR

### ISSUE THREAD

**Issue by Hubbotu** [Wutname1/SpartanUI#398]
Hey. Can I have spaces or commas between large numbers in the player's / enemy's health?

That is, [health: current-formatted] / [health: max-formatted] there is no way to add a comma after the thousands.

**Comment by Wutname1** [comment]
![image](https://user-images.githubusercontent.com/704321/103739563-69f3dc00-4fbb-11eb-872b-a7db2fa9033f.png)
