### ISSUE TITLE
Pool of Mixed Monstrosities window

### ISSUE THREAD

**Issue by Corrail** [Wutname1/SpartanUI#399]
When using the spartan ui and I approach the pool of mixed monstrosities in Maldraxxus, the colored ooze window doesn't pop up. If I disable the addon it pops up.

**Comment by Shiroh27** [comment]
Hey,
if you mean you can´t see the color count for the rares on the nameplate of the pool of monstrosities, than you just need to go to 
Modules > Nameplates > Indicators > Auras 
there you will find "Show only Auras created by player"
turn this OFF. (untick it)
Now do a /reload and you should be able to see the color count on the pools nameplate.
![SpartanUi Setting](https://user-images.githubusercontent.com/73191008/118015694-db221200-b354-11eb-9811-5199cb3be951.png)
