### ISSUE TITLE
4.4.7 broken?

### ISSUE THREAD

**Issue by anythingss** [Wutname1/SpartanUI#4]
Twitch updated my SpartanUI today to 4.4.7, but in game it wasn't working at all.
My bars were in the middle left and middle right of the screen, Minimap was way off the top, and buttons and bags were 10 pixels from the top of the screen.

I manually installed 4.4.5 and everything was fine again.

**Comment by Gorggy** [comment]
Having the same issue. Where did you find the old version?? Thanks

**Comment by Wutname1** [comment]
I just disabled the download for now. It should switch you back to 4.4.5.

**Comment by Wutname1** [comment]
What skin is everyone using? would anyone be able to post a screenshot?

**Comment by Aowen1337** [comment]
I use the classic style. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by Wutname1** [comment]
Ok i found the issue. If you are on 4.4.7 and come across this the quick fix is to open the settings /sui and click on classic style.

Issue notes:
The Setup wizard fixes here: a3f9e2a3b9080e035269cb84633c81b81f0bfa82 involved the modifying of the default db values and caused this issue.

**Comment by Aowen1337** [comment]
Thank you


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
