### ISSUE TITLE
SpartanUI doesn't play well with Skinner Addon alpha 6.0.14-35-g7225317

### ISSUE THREAD

**Issue by raineday** [Wutname1/SpartanUI#400]
Not sure if it's a skinner issue or an SUI issue will post in both

5x SpartanUI\core\Skin-Options.lua:153: attempt to index local 'frame' (a nil value)
[string "@SpartanUI\core\Skin-Options.lua"]:153: in function <SpartanUI\core\Skin-Options.lua:151>
[string "=[C]"]: in function `Open'
[string "@SilverDragon\lib\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-80.lua"]:1959: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1957>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIContainer-BlizOptionsGroup.lua"]:20: in function <...GUI-3.0\widgets\AceGUIContainer-BlizOptionsGroup.lua:19>
[string "=[C]"]: in function `Show'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:29: in function <FrameXML\InterfaceOptionsFrame.lua:18>
[string "=[C]"]: ?
[string "=[C]"]: in function `InterfaceOptionsList_DisplayPanel'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:47: in function `InterfaceOptionsListButton_OnClick'
[string "@FrameXML\InterfaceOptionsFrame.lua"]:470: in function `InterfaceOptionsFrame_OpenToCategory'
[string "@Skinner\Core\Options-Options.lua"]:2075: in function `?'
[string "@FrameXML\ChatFrame.lua"]:5093: in function `ChatEdit_ParseText'
[string "@FrameXML\ChatFrame.lua"]:4757: in function `ChatEdit_SendText'
[string "@FrameXML\ChatFrame.lua"]:4793: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
self = <table> {
 ConfigTableChanged = <function> defined @SilverDragon\lib\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1828
 CloseAll = <function> defined @SilverDragon\lib\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1809
 OpenHookedSUISkin = true
 Close = <function> defined @SilverDragon\lib\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1819
 SetDefaultSize = <function> defined @SilverDragon\lib\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1839
 tooltip = AceConfigDialogTooltip {
 }
 Open = <function> defined =[C]:-1
 AddToBlizOptions = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:100
 BlizOptions = <table> {
 }
 popup = <unnamed> {
 }
 GetStatusTable = <function> defined @SilverDragon\lib\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:407
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = <unnamed> {
 }
 FeedGroup = <function> defined @SilverDragon\lib\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1599
 SelectGroup = <function> defined @SilverDragon\lib\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:437
}
name = "Skinner"
frame = nil
(*temporary) = "Skinner"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"
GetAce3ConfigWindow = <function> defined @SpartanUI\core\Skin-Options.lua:58
StdUi = <table> {
 HookDisabledBackdrop = <function> defined @SpartanUI\libs\StdUi\StdUi.lua:194
 SimpleEditBox = <function> defined @SpartanUI\libs\StdUi\widgets\EditBox.lua:30
 FauxScrollFrameEvents = <table> {
 }
 GlueAcross = <function> defined @SpartanUI\libs\StdUi\StdUiPosition.lua:114
 BuildElement = <function> defined @SpartanUI\libs\StdUi\StdUiBuilder.lua:55
 GlueTop = <function> defined @SpartanUI\libs\StdUi\StdUiPosition.lua:59
 RadioGroup = <function> defined @SpartanUI\libs\StdUi\widgets\CheckBox.lua:194
 moduleVersions = <table> {
 }
 HybridScrollFrame = <function> defined @SpartanUI\libs\StdUi\widgets\Scroll.lua:578
 HighlightButtonTexture = <function> defined @SpartanUI\libs\StdUi\widgets\Button.lua:73
 ScrollBarEvents = <table> {
 }
 FrameTooltip = <function> defined @SpartanUI\libs\StdUi\widgets\Tooltip.lua:129
 ClearBackdrop = <function> defined @SpartanUI\libs\StdUi\StdUi.lua:157
 PanelWithTitle = <function> defined @SpartanUI\libs\StdUi\widgets\Basic.lua:35
 SliderWithBox = <function> defined @SpartanUI\libs\StdUi\widgets\Slider.lua:218
 ScrollBar = <function> defined @SpartanUI\libs\StdUi\widgets\Slider.lua:256
 Frame = <function> defined @SpartanUI\libs\StdUi\widgets\Basic.lua:10
 GlueRight = <function> defined @SpartanUI\libs\StdUi\StdUiPosition.lua:79
 RegisterModule = <function> defined @SpartanUI\libs\StdUi\StdUi.lua:25
 dialogs = <table> {
 }
 SetRadioGroupValue = <function> defined @SpartanUI\libs\StdUi\widgets\CheckBox.lua:219
 Dialog = <function> defined @SpartanUI\libs\StdUi\widgets\Window.lua:45
 Util = <table> {
 }
 BuildWindow = <function> defined @SpartanUI\libs\StdUi\StdUiBuilder.lua:252
 GlueOpposite = <function> defined @SpartanUI\libs\StdUi\StdUiPosition.lua:120
 AddLabel = <function> defined @SpartanUI\libs\StdUi\widgets\Label.lua:70
 Autocomplete = <function> defined @SpartanUI\libs\StdUi\widgets\Autocomplete.lua:250
 Button = <function> defined @SpartanUI\libs\StdUi\widgets\Button.lua:108
 SetTextColor = <function> defined @SpartanUI\libs\StdUi\StdUi.lua:73
 ColorPi

**Comment by raineday** [comment]
I've noticed with SpartanUI disabled it skins AceGUI-3.0 (libs)
but when I enable SpartanUI skinner disables AceGUI-3.0 (libs) in the disabled skins category and I'm unable to "enable" the disabled skin.

**Comment by Wutname1** [comment]
> 35-g7225317
Is yesterdays alpha, looks like the packager or Curse is having issues only the classic version was created today. Please check for updates in a bit i am going to try and trigger another update. 

>I've noticed with SpartanUI disabled it skins AceGUI-3.0 (libs)
Expected, SUI uses Ace and is taking over skinning of it from skinner

**Comment by raineday** [comment]
Is it possible to have an option to keep pick between skinner and SUI as the skinner?
