### ISSUE TITLE
For full localization

### ISSUE THREAD

**Issue by Crapolion** [Wutname1/SpartanUI#404]
Hello, I'm helping to translate the addon, but on Cursegaming there is no access to all these variables:

- On Artwork :

Use blizzard vehicle UI
Viewort
Enable
offset
Top 
Bottom 
Left
Right
Offset
Top offset
Bottom offset
Horizontal

ActionBar Settings
Bar 1
Bar 2
Bar 3
Bar 4
Bar 5
Bar 6

Bar backgrounds
Bar 1
Bar 2
Bar 3
Bar 4
Bar 5
Bar 6
Bar 9
Bar MenuBar
Bar Stance

- On Modules :

Components
Toggle Effects
AFK Effects
Display Location Rule1
All the time
Disabled
In a Group
In a instance
In a Raid Group
Only if in combat
Move...
Reset...
Display Location Rule2
Display Location Rule3

Chatbox
Timestamp format (+all format)
Display level
clickable web link
Hoveable game linls
Edit box on top
Shorten Channel names

Show North Indicator
Button display mode
Always hide
Show on Mouse over
Always Show

Scale
General Apperance
background
Enable
color mode
interrupt flash speed
indicators
Name
Horizontal alignement
Center
Left
Right
Class Icon
Enabled
Show on player controlled
All
Friendly
Hostile
Size
X axis
y axis
Anchor point (+ all choice)
Quest icon
rare/élite background
target indicator
XP bar

Height
Rule1
When to hide
Rule2
Rule3

Open all mail
Silently open mail
Bag free space to maintain

Stop talking
Keep track of voice lines forever
Display heard voice line in the chat.

Taunt Watcher
Active
Arena
Battleground
Outdoor
Party
Raid
Annnounce failed taunts
Announce location
Instance chat
Party
Raid
Say
No Chat
SMART

Tooltips
Font
Display Location Rule1
(all condition)
only if in combat
Display on mouse?
Move...
Reset...
Display Location Rule2
Display Location Rule3

-on Unit Frames
all

-on Movers
all

-On Help
Help
Chat commands + all
Texte tags + all

**Comment by Wutname1** [comment]
This is not completely finished by the commit above. However it does make huge strides in doing so. I will be adding more localization where I find it as I update different modules.  Notably the setup wizard will still need to be localized. Through developing the large update today I have been able to automate new localizations so expect to see many more coming over the next few weeks.
