### ISSUE TITLE
SpartanUI Not displaying percentage health. Help?

### ISSUE THREAD

**Issue by LadyJynx89** [Wutname1/SpartanUI#405]

**Comment by raineday** [comment]
you can do both for health and power for health/power you'll need to go to each unit frame (player, target, pet, ect.) and set the health/power second text element to enabled and in the text box you'll put [perhp]% or  [perhp<$%] and you'll do the same with the power/mana using [perpp]% or [perpp<$%]  you can find the text inputs for the text boxes in the help>text tags.

![unknown 1](https://user-images.githubusercontent.com/5045511/106098043-964fd380-60f5-11eb-81da-bda7e1c10f0b.png)
