### ISSUE TITLE
Problem with Vuhdo and import Profiles

### ISSUE THREAD

**Issue by wolkenfrei** [Wutname1/SpartanUI#406]
Problem:
https://cdn.discordapp.com/attachments/456526639736815627/804644592363241512/unknown.png

Solution and information from Vuhdo:
https://cdn.discordapp.com/attachments/456526639736815627/805307162246774794/image0.png

Best regards

Wolkenfrei

**Comment by Wutname1** [comment]
Fixed in: a3e97f6769a04589a4907736da0c3b4be81bb23e
