### ISSUE TITLE
Bug in Objektive Quest tracker Module

### ISSUE THREAD

**Issue by Nemesis2354** [Wutname1/SpartanUI#407]
There is an Bug in the Objektive Module. When i am Use the objektive Module, i am not able to use the group finding button for World Quests. The Button is not working after 10-15 seconds, when i am accepted an World Quest. Disable the Objektive Module fixed this Problem, but then i can´t use the movers Module.

**Comment by Wutname1** [comment]
Fixed 7234a51c62ff74949599b1fea503e4cfdb7cfbc1
