### ISSUE TITLE
Setup Wixard keeps popping up

### ISSUE THREAD

**Issue by jb4479** [Wutname1/SpartanUI#409]
The setup wizard pops up evry time I long in, with the settings for objectives, before going to finish. 

![WoWScrnShot_022621_210524](https://user-images.githubusercontent.com/16572065/109374983-7c311e80-7876-11eb-8d20-d12be44b0fc7.jpg)

**Comment by fireymerlin** [comment]
I just loaded SpartanUI and I'm having the same issue.

**Comment by draknyte1** [comment]
This has only started occuring for me since the latest update today.

**Comment by Wutname1** [comment]
Enable Objectives module.
/reload
click continue
disable module

**Comment by Wutname1** [comment]
Thank's for the screenshot so I can see what module was doing it. too many times I just get half the info a fix will be in the next build as well.
