### ISSUE TITLE
Spartan UI Error Handler Button on Minimap is ultra bothering!!!

### ISSUE THREAD

**Issue by Percula5470** [Wutname1/SpartanUI#410]
The Spartan UI Error Handler Button on Minimap ist not PERMANENTLY movable and not disabable!
VERRY BOTHERING!!! because it is directly over the Sanktums button.

**Comment by Shaanea** [comment]
great idea with the error handlerm - but same problem here - the button is movable but not permanently movable - one reload and it is again covering the Covenant button - pls fix it
