### ISSUE TITLE
Green bar appeared after name and race change.

### ISSUE THREAD

**Issue by drathmorgh** [Wutname1/SpartanUI#413]
Its version 2.6.1 and 3.0.0 as they are the 2 versions that I have working on 3.3.5a Warmane servers. 
(nothing on the forums there)

The issue is as follows, I changed my mage from bloodelf to troll, on the next login the green bar appeared in the bottom right See the image with my mage footrot, you can see the green bar under scada. 
I then deleted Footrots folder from within the account folder and replaced it with my warlocks renamed folder, the green bar is still there. 
I use this same UI set up for all 17 toons over 5 accounts. none of them have this green bar just my low geared mage.
I can take any of my toons folders and rename them to any other toon and this issue is not present.

I have effectively reinstalled all the addons fresh. from an old back up and rebuild the whole UI from scratch,
I have added the addons back one by one to see if its any other addon that's causing this but its there when only spartan UI is installed. 
I have taken my mages UI and renamed it to anyone of my other toons on any of the accounts and none of them have this green bar. it seems like its actually attached to this one toon. I have looked at the LUA files but with my limited understanding of it all, I am now lost and asking for help. 

I know its an outdated version so it's one of them. If I'm asking in the wrong place or need to ask some other place I would be grateful to be pointed in the right direction. 
Pic 1- Footrot my mage with the green bar bottom right.
Pic 2- Lockgar my lock example after I copyed over footrots account folder and loaded it up with him.
![Footrot](https://user-images.githubusercontent.com/81181296/112247552-65e76a00-8c4c-11eb-89b6-86265ffdec59.jpg)
![Lockgar](https://user-images.githubusercontent.com/81181296/112247554-66800080-8c4c-11eb-9e08-30a9a415e379.jpg)

**Comment by raineday** [comment]
Not sure if bartender has an option for an XP bar or not in that version but you could try to check if it does /bartender>xp bar> uncheck it? Also not sure if you'll get support for this version.
