### ISSUE TITLE
Settings under UnitFrame are not saved 

### ISSUE THREAD

**Issue by Lujuya** [Wutname1/SpartanUI#419]
Deactivated functions are displayed again after a reload, but the checkmark remains out, and players, targets, etc. no longer move. At the top right at the edge of the screen there is also a red box without function, but it cannot be removed

**Comment by Scuffedaf** [comment]
Player, target and target of target frames don't keep their positions after reload. Also got the red box in the corner.

**Comment by Wutname1** [comment]
Red box means you copied a old SUI 5 profile into SUI 6 and corrupted your database.

Reset your profile.

SUI should be spamming your chat on logon and when you mouse over the red box telling you.
