### ISSUE TITLE
Suggestion: 3D party portrait and pet portrait

### ISSUE THREAD

**Issue by jinkusu121** [Wutname1/SpartanUI#42]
Hello,

I am using the War skin with transparent party frames and I was wondering if there was a way to/would it be possible to add 3D party portraits to the left of the current frames.

Also a 3D portrait for my player pet frame (not party), maybe on top of the health bar.

If another addon does this let me know.

Thank you,

![wowscrnshot_071918_170406](https://user-images.githubusercontent.com/41452128/42970473-613b9496-8b77-11e8-81f4-da673486d15a.jpg)

**Comment by jinkusu121** [comment]
Raid I am ok with very plain frames.  Right now I have it set to classic and it is perfect.  The only thing I can't find is how to set tank/healer icon on the important people.  Will tinker with it some more!

**Comment by Wutname1** [comment]
Implemented for SUI 6.0 17de95ca85994c0765935e0a840874fdec27cc67
