### ISSUE TITLE
Error loading Unit Frames

### ISSUE THREAD

**Issue by enbaik** [Wutname1/SpartanUI#420]
Classic TBC unable to find updater for pet, entire unit frame component not working

**Comment by dirtyjobs** [comment]
same exact thing in wow classic-era as well.

**Comment by Wutname1** [comment]
Looks like the packager failed to uncomment out the proper unit frame library. Fix has been pushed. Also once the new buiild is up for BCC ensure that the correct version is being installed CurseForge was installing wow 1.x version not bcc 2.x for me
