### ISSUE TITLE
Energy Bar display

### ISSUE THREAD

**Issue by enbaik** [Wutname1/SpartanUI#421]
Energy bar for Paladin would extend left out of unit frame when depleted, then refill slowly.
![image](https://user-images.githubusercontent.com/37854417/118838194-56feeb80-b87a-11eb-8471-7d4dd33aabc7.png)

**Comment by catiktiks** [comment]
same here

**Comment by Wutname1** [comment]
Fix was pushed a bit ago. Should be up in curseforge by now.
