### ISSUE TITLE
Issues noticed since updating addon/Pre-Patch

### ISSUE THREAD

**Issue by draknyte1** [Wutname1/SpartanUI#422]
Since TBC Pre-patch and updating to SpartanUI-6.0.20-classic, I've noticed a few weird things. Was previously using SpartanUI-6.0.19-classic, for reference. I will update this ticket as I play more. Don't hold me to it, but I may poke about, see what changed and try fix it + PR.

My Rage bar now displays weirdly. The bar moves across the text, making it unreadable and is white, although I didn't poke any setting between yesterday and today.
Yesterday before Pre-Patch:
![image](https://user-images.githubusercontent.com/3060479/118887486-52761980-b8f2-11eb-8b75-5c88f8f16b9e.png)
Today After Pre-Patch and Addon update.
![image](https://user-images.githubusercontent.com/3060479/118887152-daa7ef00-b8f1-11eb-8edd-cdb6a21f55da.png)

I can't see the bar text 1 & 2 if the bar rendering itself is disabled. Mitigated short term by setting myself as focus.

**Comment by Wutname1** [comment]
Update SUI

**Comment by draknyte1** [comment]
> 
> 
> Update SUI

I will tomorrow when I play again, Just thought I'd make an issue to keep track of any abnormalities found.
There are others, I just don't recall which at this point of the evening.
Greatly appreciate your work as I cannot play without SUI after using it for the past 9/10 years. :)
