### ISSUE TITLE
TBCC - Pet Happiness not showing

### ISSUE THREAD

**Issue by valepu** [Wutname1/SpartanUI#423]
I'm using version 6.0.21 and my pet's happiness is not showing. I have found in another issue to check if isClassic is true but when i ran the script it returned false. I checked on the code and i have noticed that isClassic and isBCC are two different variables. Maybe the part that shows or not pet's happiness is only checking if it's classic?
when i changed isClassic like this (just as a test ofc):

SUI.IsClassic = (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC)

pet happiness showed up,

**Comment by Wutname1** [comment]
That will cause many more issues as it will load things specific to classic that do not apply to BCC

Fixed in 6.0.22 2fd2eb3777bbd8f7b31303d8d02a82b7566b5ecc
