### ISSUE TITLE
Battle Ground Error

### ISSUE THREAD

**Issue by Mangchode** [Wutname1/SpartanUI#426]
Everytime I get the que for a battleground, I get the following errors.
![image](https://user-images.githubusercontent.com/84625490/119225747-b130d280-bb40-11eb-9d52-aaee163d8a03.png)

**Comment by Wutname1** [comment]
The error is not being caused by SUI but another addon, That messagebox is notorious at just blaming the last addon to do something.

Looks like it is blaming SUI's error catcher for detecting the issue, one of your other addons is likely setting a variable wrong and the blizz ui is freaking out.

**Comment by Mangchode** [comment]
ok thank you. i will delve further.
