### ISSUE TITLE
buffs

### ISSUE THREAD

**Issue by Alitaa80** [Wutname1/SpartanUI#427]
something is this UI is making me see ather players buffs on top of there names and it is enyoing as hell. Pls can someone tell me how to remove it?
![buffs](https://user-images.githubusercontent.com/85362733/120837234-bfcab100-c566-11eb-8bac-c549b791f9a1.jpg)

**Comment by Wutname1** [comment]
Looks like the option to disable them was missed. Odd this has not came up in the last year. Just added a option it will be in the next release under `/sui > Modules > Nameplates > Indicators > Auras`
