### ISSUE TITLE
Enemy health not dropping instant

### ISSUE THREAD

**Issue by Zhexuz** [Wutname1/SpartanUI#43]
When i cleave or AOE a grp of enemyes and i fixate on one enemy, the others do not loose hp unless i fixate on them, meaning i have to stwitch target if i wish to know all of the enemy's hp.

**Comment by Wutname1** [comment]
Is this for the target frame or nameplates?

**Comment by Whatsatotem** [comment]
i noticed this too, definatly the nameplates
