### ISSUE TITLE
Missing XP and Honor frames  and a large black circle

### ISSUE THREAD

**Issue by ki8w** [Wutname1/SpartanUI#431]
ON all but the Fire and Ice skin I am missing XP and Honor bars.  I checked the UI it it says they are enabled.

On the Classic Skin I have a large black circle on top of my player panel.  I have seen this before but that was years ago and I do not remember the fix for it.

**Comment by Wutname1** [comment]
screenshot?

**Comment by ki8w** [comment]
> screenshot?

I have no way to submit a screenshot.  Sorry.
