### ISSUE TITLE
Shaman totem under player unit frames not working

### ISSUE THREAD

**Issue by Zorachi** [Wutname1/SpartanUI#433]
it keeps giving me this UI error
2x ...faceSpartanUI\modules\UnitFrames\Options-Options.lua:860: attempt to index field '?' (a nil value)
[string "@SpartanUI\modules\UnitFrames\Options-Options.lua"]:860: in function <...faceSpartanUI\modules\UnitFrames\Options.lua:849>
[string "=[C]"]: ?
[string "@Attune\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-81.lua"]:51: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:49>
[string "@Attune\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-81.lua"]:847: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:668>
[string "=[C]"]: ?
[string "@Attune\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Attune\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Attune\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Attune\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...ne\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

**Comment by Wutname1** [comment]
Options being rebuilt (again) for SUI 6.1 error is no longer valid for current alpha builds.
