### ISSUE TITLE
Unable to see WoW Quest Tracker when SpartanUI 6.0.26 addon is enabled. 

### ISSUE THREAD

**Issue by Brewslei** [Wutname1/SpartanUI#435]
In the latest updates, we lost the WoW interface Quest Tracker. After resetting the Wow Interface and disabling all addons and adding them one by one, it was SpartanUI that made the Quest Tracker go away again. I'm running Retail Wow latest version 9.1.0.39335 on Windows 10 Home  Build 19043.1083

**Comment by danger83** [comment]
I am having the same problem and its annoying. Updated to SpartanUI 6.0.26, and the tracker is gone. WoW version 9.1.0.39335, Windows 10 Home 19041.1083

**Comment by Wutname1** [comment]
Was this due to objectives module hiding the panel while in combat? if this is still an issue let me know. I will reopen this and we can figure it out
