### ISSUE TITLE
party pets are not showing 

### ISSUE THREAD

**Issue by tenderdove** [Wutname1/SpartanUI#439]
I am using the classic skin in Retail.  I have tried to get the party pets to load but I can't even find them on the UI using moveit.  I have the module enabled.   Any help would be appreciated!

![image](https://user-images.githubusercontent.com/92654954/137605340-b355ff75-3031-46af-849c-6264f1662d7a.png)
![image](https://user-images.githubusercontent.com/92654954/137605300-5f7f06ba-be25-45a0-bb53-42b052acb15d.png)

**Comment by Scuffedaf** [comment]
Don't think there's an option for pets. I'd suggest a separate addon for unit frames.
