### ISSUE TITLE
No Class colours in tooltip

### ISSUE THREAD

**Issue by johndolotko** [Wutname1/SpartanUI#440]
Since the 9.1.5 update, the class colours are missing from the tooltip, it looks exactly like the default tooltip now.

**Comment by DasAoD** [comment]
Since the update, the tooltip will no longer shown on mouse position.
But maybe it's just me.

**Comment by DasAoD** [comment]
Seems to be fixed. :-)
https://github.com/Wutname1/SpartanUI/actions/runs/1457509777

![Screenshot 2021-11-18 210837](https://user-images.githubusercontent.com/42589682/142489223-1660b7e9-4728-47fb-8a75-2d6e7e58c35f.png)

**Comment by Wutname1** [comment]
40c710d7b3d8c6985f0c2271f349946ea9584258 Tooltip updates are in for next update.
