### ISSUE TITLE
Classic Era (1.14) Power Bars are blacked out

### ISSUE THREAD

**Issue by mireigi** [Wutname1/SpartanUI#442]
When using the Classic Style all power bars (energy, focus, mana, rage) are displayed in black color, rather than their respective native colors (yellow, orange?, blue, red).

The only way to fix this issue is to manually disable and re-enable each power bar within the /sui settings.

Relogging or reloading the UI will reintroduce the issue, requiring the same fix.

**Comment by Wutname1** [comment]
Let me know if this continues with 6.0.28
