### ISSUE TITLE
Cast bar keeps going on its own

### ISSUE THREAD

**Issue by Scuffedaf** [Wutname1/SpartanUI#443]
The cast bar seems to want to complete the cast visual even after I stop the cast. Got this issue since p3 patch.

**Comment by Scuffedaf** [comment]
Bump

**Comment by Scuffedaf** [comment]
Still doing it... you guys gave up on this addon or?

**Comment by Schrederick** [comment]
same here

**Comment by zeress** [comment]
Sadly can confirm still an issue

**Comment by Scuffedaf** [comment]
Gonna have to look for another ui, shame...

**Comment by Wutname1** [comment]
Hope to have a fix for this latter this week. I made a bunch of changes last night I just need to test it across all versions of the game.

**Comment by Wutname1** [comment]
Let me know if this continues with 6.0.28 I was not able to get it to happen to me spamming heals.
