### ISSUE TITLE
Is Wutname alive? We need patches for 9.2

### ISSUE THREAD

**Issue by Nemesis2354** [Wutname1/SpartanUI#444]
Hello Wutname. Give us a Livesign

**Comment by mlecuyer** [comment]
Until it happens, just locate the files `SpartanUI.toc` and `SpartanUI-Mainline.toc` in your wow addons folder and replace them with the files in this repo (they were updated 3 weeks ago):

https://github.com/Wutname1/SpartanUI/blob/master/SpartanUI.toc
https://github.com/Wutname1/SpartanUI/blob/master/SpartanUI-Mainline.toc

... that worked for me.

**Comment by Nemesis2354** [comment]
thx, that worked for me too
