### ISSUE TITLE
Player unitframe issues

### ISSUE THREAD

**Issue by Scuffedaf** [Wutname1/SpartanUI#447]
Player frame doesn't keep it's size (and position) after reload and can't set health bar background colour for some reason, only transparent.

I tried a suggestion from another topic to delete old .toc files hoping it would solve some of these small bugs but it didn't unfortunately.

**Comment by Scuffedaf** [comment]
TBCC
Classic framestyle

**Comment by Scuffedaf** [comment]
Still not keeping its position after reload. This counts for player, target, targetoftarget frames...

**Comment by Scuffedaf** [comment]
Hope you fix this for wotlk

**Comment by Scuffedaf** [comment]
Everytime I zone or reload unit frames they don't keep their settings, also when I join groups/raids. The 3D-portraits' square edges are also showing outside the circle frames. Also still not showing correct hp/mana numbers sometimes.

**Comment by Scuffedaf** [comment]
Can you PLEASE fix this? It's really annoying having to confirm the size of the unit frames 50 times an hour...

**Comment by Scuffedaf** [comment]
Also an option to turn off cooldown numbers on buffs would be nice.

**Comment by Wutname1** [comment]
![Animation](https://user-images.githubusercontent.com/704321/189426461-940a2617-bcd4-4f34-9ada-6c5c0cd1f2f0.gif)

I cannot replicate I can move and scale then /reload and they are the same. What and how are you trying to do exactly, can you record it?

**Comment by Scuffedaf** [comment]
I used original scale and now it keeps it position. But after I scale up its size it won't keep it's size after reload.

**Comment by Scuffedaf** [comment]
I fixed it I hope. I used the movers to scale a bit and apparently now it decided to save the settings. Before I was using only scale options without the movers. ;)

**Comment by Wutname1** [comment]
> I fixed it I hope. I used the movers to scale a bit and apparently now it decided to save the settings. Before I was using only scale options without the movers. ;)

In the options screen?

**Comment by Scuffedaf** [comment]
> 

Yes

**Comment by Romeus83** [comment]
Can we keep the default unit frames by any chance? 6.1.15 is giving issues. Many thanks!

**Comment by Wutname1** [comment]
> Yes

Hopefully this will resolve this ab406a9f952e11570c3c85feb1f64263620cef27



> Can we keep the default unit frames by any chance? 6.1.15 is giving issues. Many thanks!

You can disable the SUI unitframes under modules. It's pre-patch and there are alot changing, with more changes coming on the 15th with evokers. Blizzard effectively is doing 2 pre-patches as far as UI changes go.
