### ISSUE TITLE
Target Health number and percentage not updating correctly

### ISSUE THREAD

**Issue by brycesimm** [Wutname1/SpartanUI#448]
The target health number and percentage are one instance of damage behind, and each tick of damage refreshes to the previous health value. I believe the player numbers are correct. e.g. Target starts with 5000/5000 hp, I do 1000 damage and the heath stays at 5000/5000. I do another 1000 damage and the health goes down to 4000/5000 even though it should be 3000/5000 at this point. The actual health bar seems to be correct in its positioning, but the numbers themselves are not working correctly.

**Comment by Summersisle** [comment]
I have the same issue.

**Comment by Scuffedaf** [comment]
Same, not always correct values.

**Comment by Wutname1** [comment]
UNIT_HEALTH is bugged on TBC Blizzard has fixed the API for Wrath.
