### ISSUE TITLE
[Retail Bug Report]

### ISSUE THREAD

**Issue by stefanw1337** [Wutname1/SpartanUI#449]
**Describe the bug**
Player Buffs remains even after Buff/debuff module is disabled.

**To Reproduce**

1. Turn off the Buff/debuff module
2. See the buffs being on the top left of screen.

**Screenshots**

**Game details:**

- Disabled Modules:
Buff/debuff

**Additional context**

**Comment by Wutname1** [comment]
Buff module only allows you & SUI to move the blizzard buffs. Not hide them as only the blizzard buff ui can be right clicked to remove a buff. this is due to a limitation imposed on addons back in wrath or cata.
