### ISSUE TITLE
LUA Error SUI and BT4 only addons

### ISSUE THREAD

**Issue by Verelidaine** [Wutname1/SpartanUI#45]
Message: ...rface\AddOns\SpartanUI_Artwork\SpartanUI_Artwork.lua:502: attempt to index global 'addon' (a nil value)
Time: Thu Jul 19 23:50:06 2018
Count: 1
Stack: ...rface\AddOns\SpartanUI_Artwork\SpartanUI_Artwork.lua:502: attempt to index global 'addon' (a nil value)
...rface\AddOns\SpartanUI_Artwork\SpartanUI_Artwork.lua:502: in function `BartenderProfileCheck'
...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:51: in function <...ce\AddOns\SpartanUI_Artwork\Themes\Classic\Style.lua:42>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:571: in function `EnableAddon'
...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:445: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:564: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1187: in function <Interface\FrameXML\UIParent.lua:1085>

Locals: <none>

**Comment by Verelidaine** [comment]
Have to disable them, as my entire UI is broken visually.  Just happened in the middle of playing tonight as I switched to a druid alt from my hunter.  It is the same on all of my characters now.

**Comment by Wutname1** [comment]
Bartender is not loading. That error is SUI trying to popup the no bartender notification.
