### ISSUE TITLE
Error when Logging In

### ISSUE THREAD

**Issue by MCSlaven** [Wutname1/SpartanUI#450]
I am playing in the Classic ERA servers (Vanilla) @Blizzard
Below is the error I get every time I log in.

Date: 2022-07-31 11:08:19
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\SpartanUI\modules\AutoTurnIn.lua line 890:
   attempt to index field 'AutoSelectLoot' (a nil value)
Debug:
   [string "@SpartanUI\modules\AutoTurnIn.lua"]:890: BuildOptions()
   [string "@SpartanUI\modules\AutoTurnIn.lua"]:730:
      SpartanUI\modules\AutoTurnIn.lua:729
   [string "=[C]"]: ?
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: EnableAddon()
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: EnableAddon()
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:615
   [string "=[C]"]: LoadAddOn()
   [string "		local loadType = Stubby.GetConfig("Informant", "LoadType")
   		if (loadType == "always") then
   			LoadAddOn("Informant")
   		else
   			Stubby.Print("Informant is not loaded. Type /informant for more info."); -- ### _TRANS
   		end
   	"]:3: in main chunk
   [string "=[C]"]: RunScript()
   [string "@Stubby\Stubby.lua"]:914:
      Stubby\Stubby.lua:907
   [string "@Stubby\Stubby.lua"]:927: f()
   [string "@Stubby\Stubby.lua"]:738: EventWatcher()
   [string "@Stubby\Stubby.lua"]:958: Events()
   [string "*:OnEvent"]:1:
      [string "*:OnEvent"]:1
Locals:
None
AddOns:
  Swatter, v2.5.6773 (SwimmingSeadragon)
  AtlasLootClassic, vv2.4.3
  AtlasLootClassicData, vv2.4.3
  AtlasLootClassicDungeonsAndRaids, vv2.4.3
  AucAdvanced, v2.5.6733 (SwimmingSeadragon)
  AucFilterBasic, v2.5.6759 (SwimmingSeadragon)
  AucStatHistogram, v2.5.6761 (SwimmingSeadragon)
  AucStatiLevel, v2.5.6765 (SwimmingSeadragon)
  AucStatPurchased, v2.5.6762 (SwimmingSeadragon)
  AucStatSimple, v2.5.6763 (SwimmingSeadragon)
  AucStatStdDev, v2.5.6764 (SwimmingSeadragon)
  AucUtilFixAH, v2.5.6766 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.2.0
  Bartender4, v4.11.2
  BeanCounter, v2.5.6767 (SwimmingSeadragon)
  CharacterStatsClassic, v3.8.3
  DBMCore, vee0b66f
  DBMStatusBarTimers, vee0b66f
  DBMVPVEM, vbffd391
  Details, v
  DetailsTinyThreat, v
  Enchantrix, v2.5.6768 (SwimmingSeadragon)
  EnchantrixBarker, v2.5.6769 (SwimmingSeadragon)
  Gargul, v4.3.2
  Grid2, v2.0.44
  Grid2LDB, v2.0.44
  Grid2RaidDebuffs, v2.0.44
  IceHUD, v1.13.13
  Informant, v2.5.6770 (SwimmingSeadragon)
  NovaWorldBuffs, v2.28
  SlideBar, v2.5.6771 (SwimmingSeadragon)
  SpartanUI, v6.0.39
  Stubby, v2.5.6772 (SwimmingSeadragon)
  TitanClassic, v1.3.1.11401
  TitanClassicAmmo, v1.3.1.11401
  TitanClassicBag, v1.3.1.11401
  TitanClassicClock, v1.3.1.11401
  TitanClassicGold, v1.3.1.11401
  TitanClassicLocation, v1.3.1.11401
  TitanClassicLootType, v1.3.1.11401
  TitanClassicPerformance, v1.3.1.11401
  TitanClassicRegen, v1.3.1.11401
  TitanClassicRepair, v1.3.1.11401
  TitanClassicVolume, v1.3.1.11401
  TitanClassicXP, v1.3.1.11401
  TranqRotate, v2.2.3
  WeakAuras, v3.7.16
  WeaponSwingTimer, v7.1.1
  BlizRuntimeLib_enUS v1.14.3.11403 <none>
  (ck=675)

**Comment by Wutname1** [comment]
Fixed in alpha builds
