### ISSUE TITLE
Quest Tracking not appearing [Retail Bug Report]

### ISSUE THREAD

**Issue by Delvianna01** [Wutname1/SpartanUI#451]
**Describe the bug**
When tracking quests, the quest tracking is not showing up. I have made sure that nothing is being hidden under the "objectives" section of spartan. I know it is spartan because when it is disabled, I am able to see the quest objectives, but when it's enabled, it goes away.

**To Reproduce**
Steps to reproduce the behavior: It's like this all the time, on every character, not just one.

There are no errors showing.

**Game details:**
Running latest expansion and patch
- Disabled Modules: Spartanui

**Additional context**
N.A

**Comment by Wutname1** [comment]
Objective tracking module for SUI removed until further notice
