### ISSUE TITLE
[Wrath Bug Report] Chat arrows don't remember correct side on startup

### ISSUE THREAD

**Issue by EGDWind** [Wutname1/SpartanUI#453]
When moving an unlocked chat window to the left edge of the screen mid-session, it switches the 'up/down/all-the-way-down'  scroll arrows to the right side of the chat box to keep them accessible. Upon logging out and back in, the arrows are back on the left side until you move the window again.

1. Unlock your chat pane.
2. Move the chat pane to the left edge of the screen, far enough that the scroll arrow buttons flip to the right side of the chat pane.
3. /reload or log out and back in.
4. See that the arrows are gone. Unlocking the chat pane again and moving it right reveals they're back to the left edge again.

**Screenshots**
Chat UI before a reload:
![image](https://user-images.githubusercontent.com/54424288/188289914-40ffa93c-3020-4600-9ee6-a4b2a2345489.png)

Chat UI after a reload:
![image](https://user-images.githubusercontent.com/54424288/188289920-a38622d0-3a25-4ddc-a1b1-ac46d75a009d.png)

**Game details:**

- Disabled Modules:
AFK Effects
Auto sell
Auto turn in
Buffs
Combat logging
Nameplates
TauntWatcher
Tooltips

SpartanUI Wrath 6.1.0-Beta5
Classic skin

**Comment by Wutname1** [comment]
SUI does not move the buttons this is a blizzard bug. Ill look into skinning and handling the bugs in the future.
