### ISSUE TITLE
Cant get the submenu when you right click on portrait...

### ISSUE THREAD

**Issue by darthyoda74** [Wutname1/SpartanUI#455]
Normally you can right click your portrait to change loot spec and raid types....
Same with your target - you cant right click on them to inspect/whisper/invite...anythiing.

Am i missing something or is this not possible with Spartan?

How can i access this menu to change raid/loot specs?

Thanks.

**Comment by Wutname1** [comment]
Right click on your health/mana/castbar. The portrait can be disabled or overlayed on top of your bars so it is not part of the clickable area as it would cause issues.
