### ISSUE TITLE
[Beta Bug Report] Unit frames are not showing up.

### ISSUE THREAD

**Issue by Aerisot** [Wutname1/SpartanUI#456]
As discussed on Discord, the unit frames are not showing up in any version of SpartanUI for me, I have tried to delete the addon, and tried to reinstall it, I even tried using previous versions, they just will not show up.

These are the three errors that pop up.

1)

1x Interface/AddOns/Bartender4/PetButton.lua:119: attempt to index field 'autocastable' (a nil value)
[string "@Interface/AddOns/Bartender4/PetButton.lua"]:119: in function `func'
[string "@Interface/AddOns/Bartender4/ButtonBar.lua"]:246: in function `ForAll'
[string "@Interface/AddOns/Bartender4/PetBar.lua"]:133: in function `ApplyConfig'
[string "@Interface/AddOns/Bartender4/PetBar.lua"]:101: in function `ApplyConfig'
[string "@Interface/AddOns/Bartender4/PetBar.lua"]:69: in function <Interface/AddOns/Bartender4/PetBar.lua:38>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:630: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:526: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:739: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:104: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:97: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:92: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:84: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:80>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:58: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:59: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:31: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:26>

2) 

1x Interface/AddOns/Bartender4/PetButton.lua:119: attempt to index field 'autocastable' (a nil value)
[string "@Interface/AddOns/Bartender4/PetButton.lua"]:119: in function `func'
[string "@Interface/AddOns/Bartender4/ButtonBar.lua"]:246: in function `ForAll'
[string "@Interface/AddOns/Bartender4/PetBar.lua"]:133: in function `ApplyConfig'
[string "@Interface/AddOns/Bartender4/PetBar.lua"]:101: in function `ApplyConfig'
[string "@Interface/AddOns/Bartender4/PetBar.lua"]:69: in function <Interface/AddOns/Bartender4/PetBar.lua:38>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:630: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:526: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:739: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:104: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:97: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:92: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:84: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:80>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:58: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:59: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:31: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:26>

3)

1x ...ns/SpartanUI/modules/UnitFrames/Elements/Castbar.lua:105: attempt to call global 'CastingBarFrame_SetUnit' (a nil value)
[string "@Interface/AddOns/SpartanUI/modules/UnitFrames/Elements/Castbar.lua"]:105: in function `Build'
[string "@Interface/AddOns/SpartanUI/modules/UnitFrames/Handlers/Elements.lua"]:110: in function `Build'
[string "@Interface/AddOns/SpartanUI/modules/UnitFrames/Units/player.lua"]:43: in function `builder'
[string "@Interface/AddOns/SpartanUI/modules/UnitFrames/Handlers/Units.lua"]:223: in function `BuildFrame'
[string "@Interface/AddOns/SpartanUI/modules/UnitFrames/SpawnFrames.lua"]:208: in function `styleFunc'
[string "@Interface/AddOns/SpartanUI/libs/oUF/ouf.lua"]:348: in function <Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:273>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/SpartanUI/libs/oUF/ouf.lua"]:753: in function `Spawn'
[string "@Interface/AddOns/SpartanUI/modules/UnitFrames/SpawnFrames.lua"]:252: in function `SpawnFrames'
[string "@Interface/AddOns/SpartanUI/modules/UnitFrames/Framework.lua"]:141: in function <...ce/AddOns/SpartanUI/modules/UnitFrames/Framework.lua:135>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:70: in function <...AddOns/Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:65>
...
[string "@Interface/FrameXML/UIParent.lua"]:526: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:739: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:104: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:97: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:92: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:84: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:80>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:58: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:59: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:31: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:26>

Export String: Unit Frames

AV4xXlReU1VuaXRGcmFtZXNeVF5TU3R5bGVeU0NsYXNzaWNedF50Xl4=

**Comment by Caladryl91** [comment]
1x ...SpartanUI\modules\UnitFrames\Elements\SpartanArt.lua:64: attempt to call field 'ForceUpdate' (a nil value)
[string "@SpartanUI\modules\UnitFrames\Elements\SpartanArt.lua"]:64: in function `Update'
[string "@SpartanUI\modules\UnitFrames\Handlers\Elements.lua"]:120: in function `Update'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:127: in function `ElementUpdate'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:210: in function `styleFunc'
[string "@SpartanUI\libs\oUF\ouf.lua"]:348: in function <SpartanUI\libs\oUF\ouf.lua:273>
[string "=(tail call)"]: ?
[string "@SpartanUI\libs\oUF\ouf.lua"]:753: in function `Spawn'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:250: in function `SpawnFrames'
[string "@SpartanUI\modules\UnitFrames\Framework.lua"]:141: in function <...ceSpartanUI\modules\UnitFrames\Framework.lua:135>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by Caladryl91** [comment]
I have the same issue. As soon as I change something in my UI. The whole Unit Frame is disappearing including from the Settings
