### ISSUE TITLE
Escape Menu

### ISSUE THREAD

**Issue by Romeus83** [Wutname1/SpartanUI#461]
Hi, 

Thanks for the update and look forward to still using Spartan UI in Dragon Flight expansion. Just like to check is there anyway i can get back the old escape menu after the latest update? Prefer the old school UI menu personally. 

Cheers!

**Comment by VynashDawnheart** [comment]
Bump. I would like the old one back as well, and will just revert until.

**Comment by Wutname1** [comment]
Added in SUI 6.1.8

**Comment by Romeus83** [comment]
Sorry but hw do i make it back? it's still the spartan menu
