### ISSUE TITLE
[Retail Bug Report] Minimap Clock/Zone bar is blank

### ISSUE THREAD

**Issue by Elfykins** [Wutname1/SpartanUI#462]
**Describe the bug**
With SUI enabled, the minimap/zone bar does not have the clock or zone present.
**To Reproduce**

1. Disabled SUI - top right will show clock/zone in the little bar next to the search binocular icon.
2.  Enable SUI - the bar becomes blank.

**Comment by Wutname1** [comment]
Fixed in: 13f326aaa74910122507484bdd4cd42825c97937

**Comment by Wutname1** [comment]
SUI 6.1.14 will include the fix, I hope to release it tonight.
