### ISSUE TITLE
[Request] Minimap time

### ISSUE THREAD

**Issue by Scuffedaf** [Wutname1/SpartanUI#463]
Hi,

Any possibility to add some settings for the minimap time indicator?

It is overlapping with NovaWorldBuff's layer indicator.

- location
- background
- colours
- ...

**Comment by Scuffedaf** [comment]
Not sure why you removed the background, it's not easy to read the time now.

**Comment by Scuffedaf** [comment]
Bump

**Comment by Wutname1** [comment]
retail or wrath?

**Comment by Scuffedaf** [comment]
Wrath
