### ISSUE TITLE
[Retail Bug Report] Unable to click on consolidated abilities (eg Portals/Hunter Pet Utility)

### ISSUE THREAD

**Issue by Elfykins** [Wutname1/SpartanUI#465]
This may not be an issue with SUI, but could be Bartender, but considering that these 2 are needed for each other, I am posting here first.

Trying to click on any of the abilities that are consolidated when they are on the bar (eg Portals/Hero's Paths/Pet Utility) results in nothing happening, the button does not work and the abilities do not "pop out" from their bar.

Sorry if this is confusing.

**Comment by Wutname1** [comment]
Known blizzard bug. https://github.com/Nevcairiel/Bartender4/issues/92
