### ISSUE TITLE
WOTLK Classic: Party pets non-functional

### ISSUE THREAD

**Issue by XWingMitch0** [Wutname1/SpartanUI#468]
![image](https://user-images.githubusercontent.com/58368127/200084387-b9ee74db-cfcf-4a0f-9234-87cba7f207b9.png)
SpartanUI Wrath 6.1.20
no LUA errors
Partypets module will not load...makes it quite difficult to keep my wife's bear alive on elite pulls without using focus (a bad workaround that will need to be fixed for later play)

**Comment by Wutname1** [comment]
You need to enable them if you want them under unitframes

![image](https://user-images.githubusercontent.com/704321/200141090-40ee371c-c531-44a1-b8c6-9050c5a6c7b9.png)

**Comment by XWingMitch0** [comment]
Well S***, now I feel stupid. Thanks Wtname, sorry for the wasted ticket :-/
