### ISSUE TITLE
Interference with Details Addon

### ISSUE THREAD

**Issue by Scuffedaf** [Wutname1/SpartanUI#469]
1x Details\startup.lua:78: attempt to call method 'InitializeMacrosWindow' (a nil value)
[string "@Details\startup.lua"]:78: in function `StartMeUp'
[string "@Details\core\parser.lua"]:5813: in function <Details\core\parser.lua:5812>

Locals:
self = <table> {
 SetBarSpecIconSettings = <function> defined @Details\frames\window_main.lua:4368
 APITopics = <table> {
 }
 InitializeRunCodeWindow = <function> defined @Details\frames\window_runcode.lua:8
 EncounterDetailsTempWindow = <function> defined @Details_EncounterDetails\frames.lua:49
 EntrarEmCombate = <function> defined @Details\core\control.lua:311
 hex = <function> defined @Details\core\util.lua:900
 BuildSpellList = <function> defined @Details\functions\spellcache.lua:390
 opened_windows = 2
 RefreshAttributeTextSize = <function> defined @Details\frames\window_main.lua:7787
 PotionList = <table> {
 }
 EndRefresh = <function> defined @Details\core\control.lua:1730
 FechaJanelaInfo = <function> defined @Details\frames\window_playerbreakdown.lua:481
 GetMode = <function> defined @Details\classes\class_instance.lua:173
 SetMode = <function> defined @Details\classes\class_instance.lua:2819
 RestoreState_CurrentMythicDungeonRun = <function> defined @Details\functions\profiles.lua:1567
 APIVersion = 146
 IsPluginEnabled = <function> defined @Details\core\plugins.lua:59
 ImportProfile = <function> defined @Details\functions\profiles.lua:1726
 show_totalhitdamage_on_overkill = false
 raid = 2
 SetNickname = <function> defined @Details\Libs\NickTag-1.0\NickTag-1.0.lua:573
 color_by_arena_team = true
 SortKeyGroupHeal = <function> defined @Details\classes\class_heal.lua:146
 SortKeyGroup = <function> defined @Details\classes\class_damage.lua:143
 IsInEncounter = <function> defined @Details\core\parser.lua:6280
 Check_ZONE_CHANGED_NEW_AREA = <function> defined @Details\core\parser.lua:4927
 plugin_window_pos = <table> {
 }
 gump = <table> {
 }
 ShowDeathTooltipFunction = <function> defined @Details\classes\class_utility.lua:210
 CaptureRefresh = <function> defined @Details\core\parser.lua:4577
 NewModule = <function> defined @Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InstancesToStoreData = <table> {
 }
 name_space_info = <function> defined @Details\core\util.lua:1616
 ShowDelayMsg = <function> defined @Details\boot.lua:1031
 Resize = <function> defined @Details\classes\class_instance.lua:2003
 GetEncounterActorsName = <function> defined @Details\functions\boss.lua:306
 RequestCloudData = <function> defined @Details\core\network.lua:603
 RestauraJanela = <function> defined @Details\classes\class_instance.lua:1519
 default_skin_to_use = "Minimalistic"
 GetOpenedWindowsAmount = <function> defined @Details\classes\class_instance.lua:285
 GetInstanceGroup = <function> defined @Details\frames\window_main.lua:8326
 deadlog_events = 32
 Dump = <function> defined @Details\frames\window_dump.lua:20
 OpenNewsWindow = <function> defined @Details\frames\window_news.lua:7
 last_instance_id = 575
 _detalhes_props = <table> {
 }
 atributo_energy = <table> {
 }
 UnitDamageOnUnit = <function> defined @Details\functions\api2.lua:1134
 name_space_generic = <function> defined @Details\core\util.lua:1626
 storage = <table> {
 }
 FadeHandler = <table> {
 }
 AdjustAlphaByContext = <function> defined @Details\frames\window_main.lua:7531
 ContainerSortEnemies = <function> defined @Details\classes\class_damage.lua:274
 ToolBar = <table> {
 }
 GetTitleBarText = <function> defined @Details\frames\window_main.lua:7967
 FixToolbarMenu = <function> defined @Details\classes\class_instance.lua:1505
 UseWestNumericalSystem = <function> defined @Details\core\util.lua:539
 FazerAnimacao_Esquerda = 

------------------

1x Details\startup.lua:71: attempt to call method 'InitializeAuraCreationWindow' (a nil value)
[string "@Details\startup.lua"]:71: in function <Details\startup.lua:70>

Locals:
(*temporary) = nil
(*temporary) = <table> {
 SetBarSpecIconSettings = <function> defined @Details\frames\window_main.lua:4368
 APITopics = <table> {
 }
 InitializeRunCodeWindow = <function> defined @Details\frames\window_runcode.lua:8
 EncounterDetailsTempWindow = <function> defined @Details_EncounterDetails\frames.lua:49
 EntrarEmCombate = <function> defined @Details\core\control.lua:311
 hex = <function> defined @Details\core\util.lua:900
 BuildSpellList = <function> defined @Details\functions\spellcache.lua:390
 opened_windows = 2
 RefreshAttributeTextSize = <function> defined @Details\frames\window_main.lua:7787
 PotionList = <table> {
 }
 EndRefresh = <function> defined @Details\core\control.lua:1730
 FechaJanelaInfo = <function> defined @Details\frames\window_playerbreakdown.lua:481
 GetMode = <function> defined @Details\classes\class_instance.lua:173
 SetMode = <function> defined @Details\classes\class_instance.lua:2819
 RestoreState_CurrentMythicDungeonRun = <function> defined @Details\functions\profiles.lua:1567
 APIVersion = 146
 IsPluginEnabled = <function> defined @Details\core\plugins.lua:59
 ImportProfile = <function> defined @Details\functions\profiles.lua:1726
 show_totalhitdamage_on_overkill = false
 raid = 2
 SetNickname = <function> defined @Details\Libs\NickTag-1.0\NickTag-1.0.lua:573
 color_by_arena_team = true
 SortKeyGroupHeal = <function> defined @Details\classes\class_heal.lua:146
 SortKeyGroup = <function> defined @Details\classes\class_damage.lua:143
 IsInEncounter = <function> defined @Details\core\parser.lua:6280
 Check_ZONE_CHANGED_NEW_AREA = <function> defined @Details\core\parser.lua:4927
 plugin_window_pos = <table> {
 }
 gump = <table> {
 }
 ShowDeathTooltipFunction = <function> defined @Details\classes\class_utility.lua:210
 CaptureRefresh = <function> defined @Details\core\parser.lua:4577
 NewModule = <function> defined @Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 InstancesToStoreData = <table> {
 }
 name_space_info = <function> defined @Details\core\util.lua:1616
 ShowDelayMsg = <function> defined @Details\boot.lua:1031
 Resize = <function> defined @Details\classes\class_instance.lua:2003
 GetEncounterActorsName = <function> defined @Details\functions\boss.lua:306
 RequestCloudData = <function> defined @Details\core\network.lua:603
 RestauraJanela = <function> defined @Details\classes\class_instance.lua:1519
 default_skin_to_use = "Minimalistic"
 GetOpenedWindowsAmount = <function> defined @Details\classes\class_instance.lua:285
 GetInstanceGroup = <function> defined @Details\frames\window_main.lua:8326
 deadlog_events = 32
 Dump = <function> defined @Details\frames\window_dump.lua:20
 OpenNewsWindow = <function> defined @Details\frames\window_news.lua:7
 last_instance_id = 575
 _detalhes_props = <table> {
 }
 atributo_energy = <table> {
 }
 UnitDamageOnUnit = <function> defined @Details\functions\api2.lua:1134
 name_space_generic = <function> defined @Details\core\util.lua:1626
 storage = <table> {
 }
 FadeHandler = <table> {
 }
 AdjustAlphaByContext = <function> defined @Details\frames\window_main.lua:7531
 ContainerSortEnemies = <function> defined @Details\classes\class_damage.lua:274
 ToolBar = <table> {
 }
 GetTitleBarText = <function> defined @Details\frames\window_main.lua:7967
 FixToolbarMenu = <function> defined @Details\classes\class_instance.lua:1505
 UseWestNumericalSystem = <function> defined @Details\core\util.lua:539

**Comment by Wutname1** [comment]
Details works just fine with SUI this is not an interference issue.

**Comment by Scuffedaf** [comment]
Reinstalled Details, seems to work fine now.
