### ISSUE TITLE
Autosell LUA error

### ISSUE THREAD

**Issue by Doompa** [Wutname1/SpartanUI#47]
Message: Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)
Time: Sat Jul 21 00:51:53 2018
Count: 1
Stack: Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)
[C]: in function `GetItemIDs'
Interface\AddOns\SpartanUI\components\AutoSell.lua:336: in function `SellTrash'
Interface\AddOns\SpartanUI\components\AutoSell.lua:380: in function <Interface\AddOns\SpartanUI\components\AutoSell.lua:375>

Locals: (*temporary) = "Usage: local itemIDs = C_EquipmentSet.GetItemIDs(equipmentSetID)"

Got this after the most recent update (which was 4 hours ago as of this post). It still works on 1 character out of 5 but I can't figure out why. It seems you had a previous issue similar to this but the bug seems to be back.

**Comment by Wutname1** [comment]
#29
