### ISSUE TITLE
[Wrath Bug Report] Local Error

### ISSUE THREAD

**Issue by lectrcsprx** [Wutname1/SpartanUI#470]
7x Attempt to register unknown event "UNIT_POWER_POINT_CHARGE"
[string "=[C]"]: ?
[string "=[C]"]: in function `xpcall'
[string "@SpartanUI\libs\Non-Retail\oUF\private.lua"]:74: in function <...aceSpartanUI\libs\Non-Retail\oUF\private.lua:73>
[string "@SpartanUI\libs\Non-Retail\oUF\events.lua"]:128: in function `RegisterEvent'
[string "@SpartanUI\libs\Non-Retail\oUF\elements\classpower.lua"]:260: in function <...partanUI\libs\Non-Retail\oUF\elements\classpower.lua:254>
[string "@SpartanUI\libs\Non-Retail\oUF\elements\classpower.lua"]:216: in function <...partanUI\libs\Non-Retail\oUF\elements\classpower.lua:180>
[string "=(tail call)"]: ?
[string "@SpartanUI\libs\Non-Retail\oUF\ouf.lua"]:221: in function `UpdateAllElements'
[string "@SpartanUI\modules\UnitFrames\Elements\Debuffs.lua"]:43: in function `Update'
[string "@SpartanUI\modules\UnitFrames\Handlers\Elements.lua"]:120: in function `Update'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:134: in function `ElementUpdate'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:84: in function `UpdateAll'
[string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:332: in function `SpawnFrames'
[string "@SpartanUI\modules\UnitFrames\Framework.lua"]:148: in function <...ceSpartanUI\modules\UnitFrames\Framework.lua:142>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:540: in function `EnableAddon'
[string "@Atlas\Libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <...faceAtlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>**Describe the bug**

**To Reproduce**

**Screenshots**

**Game details:**

- Disabled Modules:

**Additional context**

**Comment by lectrcsprx** [comment]
It looks like a bug in Spartan up.  Help!

**Comment by Wutname1** [comment]
What class are you playing?

**Comment by lectrcsprx** [comment]
Combat rogue


Sent from Yahoo Mail for iPhone


On Sunday, November 6, 2022, 6:49 PM, wutname1 ***@***.***> wrote:




What class are you playing?

**Comment by lectrcsprx** [comment]
Please add fix to Overwolf Addon site.  Im not a good copy n paste person.  Thanks,  Sambucca
    On Monday, November 7, 2022 at 11:37:42 PM CST, wutname1 ***@***.***> wrote:  
 
 


Closed #470 as completed via 5384842.

**Comment by lectrcsprx** [comment]
Ty Wutname1!  I sent you a $100 for all the work you do.  Luv your add on!!Sambucca


Sent from Yahoo Mail for iPhone


On Monday, November 7, 2022, 11:37 PM, wutname1 ***@***.***> wrote:




Closed #470 as completed via 5384842.
