### ISSUE TITLE
[Wrath Bug Report] - Version 6.1.22 is unable to load Unit Frames

### ISSUE THREAD

**Issue by nerbos** [Wutname1/SpartanUI#471]
**Describe the bug**
Getting a crash which results in not being able to load unit frames in spartan UI classic view. This happens whenever I logged in a character. Already tried to uninstall and install it without any luck. Information:

Date: 2022-11-08 12:57:24
ID: 1
Error occured in: Global
Count: 1
Message: ...ce\AddOns\SpartanUI\libs\Non-Retail\oUF\blizzard.lua line 109:
   attempt to index global 'PartyFrame' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "@SpartanUI\libs\Non-Retail\oUF\blizzard.lua"]:109: DisableBlizzard()
   [string "@SpartanUI\libs\Non-Retail\oUF\ouf.lua"]:714: SpawnHeader()
   [string "@SpartanUI\modules\UnitFrames\Units\raid.lua"]:42: groupbuilder()
   [string "@SpartanUI\modules\UnitFrames\Handlers\Units.lua"]:94: BuildGroup()
   [string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:286: SpawnFrames()
   [string "@SpartanUI\modules\UnitFrames\Framework.lua"]:195:
      ...ce\AddOns\SpartanUI\modules\UnitFrames\Framework.lua:189
   [string "=[C]"]: ?
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:66:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:61
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:536: EnableAddon()
   [string "@Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:626:
      Ace3\AceAddon-3.0\AceAddon-3.0.lua:611
Locals:
None
AddOns:
  Swatter, v3.4.6817 (SwimmingSeadragon)
  Ace3, vRelease-r1294
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  AucAdvanced, v3.4.6825 (SwimmingSeadragon)
  AucFilterBasic, v3.4.6803 (SwimmingSeadragon)
  AucStatHistogram, v3.4.6805 (SwimmingSeadragon)
  AucStatiLevel, v3.4.6809 (SwimmingSeadragon)
  AucStatPurchased, v3.4.6806 (SwimmingSeadragon)
  AucStatSimple, v3.4.6807 (SwimmingSeadragon)
  AucStatStdDev, v3.4.6808 (SwimmingSeadragon)
  AucUtilFixAH, v3.4.6810 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v10.0.3
  BagnonItemInfo, v2.0.42-Release
  BagnonItemLevel, v2.0.61-Release
  BeanCounter, v3.4.6811 (SwimmingSeadragon)
  BuffwatchClassic, v3.00
  ChatCopyPaste, v1.13
  ClassicAuraDurations, v3.0
  ClassicLootManager, vv2.6.0
  Clique, vv3.4.10-release
  DBMCore, v11fef96
  DBMStatusBarTimers, v11fef96
  DBMVPVEM, v0dab85c
  Details, v#Details.DF.Wrath.10259.146
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  Enchantrix, v3.4.6821 (SwimmingSeadragon)
  EnchantrixBarker, v3.4.6813 (SwimmingSeadragon)
  ExRT, v4680
  Grid2, v2.0.63
  Grid2LDB, v2.0.63
  Grid2RaidDebuffs, v2.0.63
  GuildRosterManager, v1.946
  HealBarsClassic, v
  LeatrixMaps, v3.0.48
  LFGBulletinBoard, v3.05
  MikScrollingBattleText, v5.7.153
  MRT, v4680
  NovaInstanceTracker, v1.37
  NovaWorldBuffs, v2.40
  Outfitter, v3.0.0
  PallyPower, vv1.5.0-classic
  Quartz, v3.7.0
  RaidBuffTracker, v3.00
  SimpleDruidMana, v0.6.0
  SlideBar, v3.4.6815 (SwimmingSeadragon)
  SpartanUI, v6.1.22
  Stubby, v3.4.6816 (SwimmingSeadragon)
  ThreatClassic2, v2.45
  TomTom, vv3.3.4-release
  TotemTimers, v3.1.11
  VendorPrice, v1.6.1
  WeakAuras, v5.1.0
  WoWPro, v2022.11.03.A
  WoWProLeveling, v2022.11.03.A
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=74a)

**Comment by nerbos** [comment]
Work around, delete account saved variables for SpartanUI, and install the previous version 6.1.21. (**WARNING:** By doing this you will need to configure it again your SpartanUI)

**Comment by Shaanea** [comment]
yes, true - player and other unitframes are gone in WOTLK (not in Retail) - installed 6.1.2.1 again for WOTLK - didn't had to configure new as far as I can just see

**Comment by Wutname1** [comment]
Sorry, new update out to fix it. I caught this last night but accidently only applied it to the coming SUI 6.2 builds

**Comment by nerbos** [comment]
Confirmed, 6.1.23 solves it. Much appreciated!
