### ISSUE TITLE
[Retail Bug Report] Mini-map quest arrow is cutofff

### ISSUE THREAD

**Issue by Yamr3** [Wutname1/SpartanUI#472]
**Describe the bug**
Latest update seems to made the Quest arrow not show up clearly anymore. The arrow is pointing towards the "or" in Darkshore. Just to help find where it is in the picture.

**To Reproduce**

See picture referenced.

**Screenshots**

**Game details:**

- Disabled Modules:

**Additional context**
![Screenshot 2022-11-15 185615](https://user-images.githubusercontent.com/58268653/202056994-c6bf9bfd-5dc1-4ab1-94fc-b536e47ef554.png)

**Comment by Mike160770** [comment]
same problem when you are tracking quest hubs.

**Comment by Wutname1** [comment]
Note: I am aware of this, part of it is due to the size of the new default map being so large it does not handle being shrunk well. will take some time to look into. I may increase the minimap size for non-classic skins for the time being.
