### ISSUE TITLE
[Wrath Bug Report] Can't hide auto-turn-in module

### ISSUE THREAD

**Issue by Scuffedaf** [Wutname1/SpartanUI#474]
Can't hide auto-turn-in module though I turned it off. Can't move it neither. Annoying because it's on top of my chat now.

**Comment by EGDWind** [comment]
I ran into auto-turnin being stuck on as well. On top of that, it seemed to forget which modules I had disabled & re-enabled everything. Had to downgrade to 6.1.28 to avoid the issue for a bit.

**Comment by Scuffedaf** [comment]
Hey, any fix?

**Comment by Scuffedaf** [comment]
Bump

**Comment by Scuffedaf** [comment]
Still not fixed btw.

**Comment by Scuffedaf** [comment]
Still can't hide the bar...

**Comment by Scuffedaf** [comment]
Did you gave up on this addon or?

![WoWScrnShot_090423_024728](https://github.com/Wutname1/SpartanUI/assets/72989740/1226533b-621f-4624-9375-2835dd19af3f)

**Comment by Wutname1** [comment]
> Did you gave up on this addon or?

I don't play Classic so updates are as needed when patches land. Then there is Baldur's Gate 3...

The X was added by the Hardcore mode patch new update addresses it.

**Comment by Scuffedaf** [comment]
No the x was also in normal classic era.

**Comment by Scuffedaf** [comment]
The x is gone thank you.
