### ISSUE TITLE
[Wrath Bug Report] SpawnFrames error

### ISSUE THREAD

**Issue by fibbetmoff** [Wutname1/SpartanUI#478]
Greetings! So, every time I log in to WotLK Classic, I get the error below. I am not well versed in this. I've poked around in the front-end in-game but can't find anything related to "SpawnFrames," and I don't know if there is a particular addon I'm using alongside SpartanUI that is interfering somehow, so I am not sure how to fix this on my end. How can I keep this from popping up every time I log in or reload? Thank you for your time!! :)

> Date: 2022-12-06 01:08:41
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\SpartanUI\modules\UnitFrames\SpawnFrames.lua line 61:
   attempt to index field 'DB' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "=[C]"]: ?
   [string "@..\FrameXML\RestrictedFrames.lua"]:674:
      ..\FrameXML\RestrictedFrames.lua:673
   [string "@..\FrameXML\RestrictedFrames.lua"]:812: CallMethod()
   [string "		local header = self:GetParent()
   		local frames = table.new()
   		table.insert(frames, self)
   		self:GetChildList(frames)
   		for i = 1, #frames do
   			local frame = frames[i]
   			local unit
   			-- There's no need to do anything on frames with onlyProcessChildren
   			if(not frame:GetAttribute('oUF-onlyProcessChildren')) then
   				RegisterUnitWatch(frame)
   				-- Attempt to guess what the header is set to spawn.
   				local groupFilter = header:GetAttribute('groupFilter')
   				if(type(groupFilter) == 'string' and groupFilter:match('MAIN[AT]')) then
   					local role = groupFilter:match('MAIN([AT])')
   					if(role == 'T') then
   						unit = 'maintank'
   					else
   						unit = 'mainassist'
   					end
   				elseif(header:GetAttribute('showRaid')) then
   					unit = 'raid'
   				elseif(header:GetAttribute('showParty')) then
   					unit = 'party'
   				end
   				local headerType = header:GetAttribute('oUF-headerType')
   				local suffix = frame:GetAttribute('unitsuffix')
   				if(unit and suffix) then
   					if(headerType == 'pet' and suffix == 'target') then
   						unit = unit .. headerType .. suffix
   					else
   						unit = unit .. suffix
   					end
   				elseif(unit and headerType == 'pet') then
   					unit = unit .. headerType
   				end
   				frame:SetAttribute('*type1', 'target')
   				frame:SetAttribute('*type2', 'togglemenu')
   				frame:SetAttribute('oUF-guessUnit', unit)
   			end
   			local body = header:GetAttribute('oUF-initialConfigFunction')
   			if(body) then
   				frame:Run(body, unit)
   			end
   		end
   		header:CallMethod('styleFunction', self:GetName())
   		local clique = header:GetFrameRef('clickcast_header')
   		if(clique) then
   			clique:SetAttribute('clickcast_button', self)
   			clique:RunAttribute('clickcast_register')
   		end
   	"]:51:
      [string "		local header = self:GetParent()..."]:1
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@..\FrameXML\RestrictedExecution.lua"]:484:
      ..\FrameXML\RestrictedExecution.lua:447
   [string "@..\FrameXML\SecureGroupHeaders.lua"]:116:
      ..\FrameXML\SecureGroupHeaders.lua:110
   [string "@..\FrameXML\SecureGroupHeaders.lua"]:173:
      ..\FrameXML\SecureGroupHeaders.lua:130
   [string "@..\FrameXML\SecureGroupHeaders.lua"]:495:
      ..\FrameXML\SecureGroupHeaders.lua:394
   [string "=[C]"]: Show()
   [string "@SpartanUI\modules\UnitFrames\Units\party.lua"]:64: groupbuilder()
   [string "@SpartanUI\modules\UnitFrames\Handlers\Units.lua"]:94: BuildGroup()
   [string "@SpartanUI\modules\UnitFrames\SpawnFrames.lua"]:286: SpawnFrames()
   [string "@SpartanUI\modules\UnitFrames\Framework.lua"]:156:
      ...ce\AddOns\SpartanUI\modules\UnitFrames\Framework.lua:150
   [string "=[C]"]: ?
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:66:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:61
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:523: EnableAddon()
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:536: EnableAddon()
   [string "@Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua"]:626:
      ...AddOns\Bartender4\libs\AceAddon-3.0\AceAddon-3.0.lua:611
Locals:
None
AddOns:
  Swatter, v3.4.6837 (SwimmingSeadragon)
  AtlasLootClassic, vv3.0.7
  AtlasLootClassicData, vv3.0.7
  AtlasLootClassicDungeonsAndRaids, vv3.0.7
  BagBrother, v
  Bagnon, v10.0.10
  Bartender4, v4.14.3
  DBMCore, v5bd31e2
  DBMSoundEventsPack, v1.6.20
  DBMSpellTimers, vr143
  DBMStatusBarTimers, v5bd31e2
  DBMVPVEM, vfce23ce
  Details, v#Details.DF.Wrath.10333.147
  DetailsCompare2, v
  DetailsEncounterDetails, v
  DetailsRaidCheck, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DetailsVanguard, v
  GatherMate2, v1.46.3-classic
  LeatrixMaps, v3.0.65
  Questie, v7.4.5
  SlideBar, v3.4.6851 (SwimmingSeadragon)
  SpartanUI, v6.1.29
  Stubby, v3.4.6816 (SwimmingSeadragon)
  TacoTip, v0.3.4
  BlizRuntimeLib_enUS v3.4.0.30400 <none>
  (ck=2e4)

**Comment by Wutname1** [comment]
> I originally could not get Party frames to display in Spartan so had disabled the frame in UnitFrames.
> 
> Whilst testing this a couple of times I have now ended up with the error shown above and the UnitFrames options having completely disappeared from the Spartan UI menu

Sounds like a setting is erroring and corrupted the unit frames, can you export your unitframe profile `/sui` export button on the bottom of the window, then uncheck everything except unit frames. and post that string here?

**Comment by Trantore** [comment]
As requested here is the output from the Export function -

AypbAgBrhTSb4jai7ERkr+xGMoyo+K1kKFGGK3KQqOoYkXNEpYUIlioliyktBx6iqqfQYwXPUSYqxFTQZELTVVcVymXSdVSxUaHarBSfkfqO0GGqZQSNVqpnqJLTqNxSSl1DVOcV9Y3ANlSpaUSVk4LhGMV9HDiZsmCIn42GfOOMcUM4xhSg/hxFs2DIN84YNwTDzRp42B3Q+mAPJ30wdHDiAqPBcMNjTDBUyq1RMUJIA592bgj5xhnjht57OOnvgNYHQ6XcGhWzPXSglAd7aBdjwR5ODj4HQ7YvIi6zIoRsX8Qt58QIIdsXUWZ8VhAhVMqtUTFCyPZFlDn4HKGHmzXwsGAP74DWB0M1SqbUWTCULXDg3IPh50lD4UgP+c5uHQRDSwdDpdwaFbO999DBiQuMBkNLB0Ol3BoVsyENfNq5IZQPBqd0S8XeewicE4OhUm6NitmQ7Ysoc/A5Qg8n47OCYKhGyZQ6C4ayBQ6cezD8PGkoHOkh39mtg2Bo6WColFujYjYcllkgGEmKJEUSRpIi8YokRZLXuEAoh1zAW5KEkkAgVyBJbbbJyXvvvYd3QOvvgNYHe++9Fw==

**Comment by Trantore** [comment]
Found {Reset UnitFrame Customizations] option - and that has re-enabled Unit Frames

So all good!!

**Comment by Wutname1** [comment]
Todays release should fix the error
