### ISSUE TITLE
Nameplates not disabled after unchecking the features

### ISSUE THREAD

**Issue by Belladora1** [Wutname1/SpartanUI#48]
When I uncheck all three checkboxes from the Nameplates Module (Show castbar, Show level, Show name) all those three are hidden but the nameplate does not revert back to the Blizzard default. It stays in the SpartanUI style just without any information. When SpartanUI is disabled completly the nameplates revert back to the Blizzard default.
This also means that with any specific nameplate add on I know have dublicate nameplates as the basic nameplate from spartan UI sticks.

**Comment by Wutname1** [comment]
@whatsatotem is correct on how to disable nameplates. All you are doing is toggling options for the nameplate.
