### ISSUE TITLE
Interrupt module error message

### ISSUE THREAD

**Issue by Mike160770** [Wutname1/SpartanUI#480]
2x SendChatMessage(): Unknown chat type
[string "=[C]"]: ?
[string "=[C]"]: in function `SendChatMessage'
[string "@Interface/AddOns/SpartanUI/modules/InterruptAnnounce.lua"]:41: in function <...rface/AddOns/SpartanUI/modules/InterruptAnnounce.lua:7>
[string "@Interface/AddOns/SpartanUI/modules/InterruptAnnounce.lua"]:107: in function <...rface/AddOns/SpartanUI/modules/InterruptAnnounce.lua:73>
[string "=[C]"]: ?
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Interface/AddOns/Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Interface/AddOns/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by Wutname1** [comment]
Were you in a Group finder, party, or raid?

**Comment by Mike160770** [comment]
> Were you in a Group finder, party, or raid?

I was in a dungeon - but solo (not in a group). Maybe that caused the error.
