### ISSUE TITLE
[Wrath Bug Report] Cant change unitframes

### ISSUE THREAD

**Issue by Wizard-911** [Wutname1/SpartanUI#484]
**Describe the bug**
Since CurseForge updated the Spartan UI to Classic Version (and messing up my existing UI), I cannot change a thing in the unitframes.

**To Reproduce**

1. /sui
2. Click on 'unitframes'
3. Choose 'player/health/text'
4. Try to change 'position Y-Axis'
5. See error

**Error Handler 6.2.0-CLASSIC**
17x ...faceSpartanUI\modules\UnitFrames\Options-Optionen.lua:743: attempt to index field 'position' (a nil value)
[string "@SpartanUI\modules\UnitFrames\Options-Optionen.lua"]:743: in function <...faceSpartanUI\modules\UnitFrames\Options.lua:739>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:45: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:43>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:836: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:658>
[string "@Bartender4\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-86.lua"]:888: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:876>
[string "=[C]"]: ?
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:66: in function <...aceBartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:64>
[string "@Bartender4\libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:300: in function `Fire'
[string "@Bartender4\libs\AceGUI-3.0-41\widgets\AceGUIWidget-Slider.lua"]:65: in function <...der4\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:56>

**Game details:**

Reinstalled everything: WoW, Curseforge, AddOns. No change.

Thanks a lot.

**Comment by Th3AnG3L** [comment]
I have issue with 3.3.5 version cannot run at all the addon
