### ISSUE TITLE
New : numbers in nameplates show special characters between thousands and hundreds

### ISSUE THREAD

**Issue by GekiCrew** [Wutname1/SpartanUI#485]
Hi,

Special character (double ??) appears in all nameplates like 18??500.

I'm a french user (don't know if related to localization).

Also spotted an "autoturnin" error => issue already posted in the forum

Edit : not only in nameplates, in all text

**Comment by Wutname1** [comment]
I know this is an old issue but if you still use SUI i think this is going to be a localization issue with the default SUI font, if you change it away from roboto in `General > Font` i think it will start working.  I stopped hard coding a `,` and started using the localized large number Seperator. 

![Image](https://github.com/user-attachments/assets/7f8a7952-b800-4cf2-8891-236bb9eb0854)

you could also try changing the large number Seperator as well, if your drop down is empty by default then that would point to localization likely. 

![Image](https://github.com/user-attachments/assets/10ce431b-c127-4e92-b8cd-30c49a83e048)
