### ISSUE TITLE
Wrath 6.2.0 classic not able to see target buffs

### ISSUE THREAD

**Issue by catarrer** [Wutname1/SpartanUI#486]
I am not able to see any buffs on my tagret that are NOT from me. older versions solve this problem. 

As a heal this is mandatory so i hope you get this fixed soon. 

Other AddOns installed:
Bagnon, DBM, Attune, Auctioneer, LeatrixMaps, Pawn, Atlas Loot, Questie and Gathermate.

**Comment by catarrer** [comment]
On 6.1.28 its working fine, if I do the update via CurseForge App the buffs don't show up. any solutions here?

**Comment by dirtyjobs** [comment]
thanks for the heads up on 6.1.28 working. this  bug has been driving me mad for ever

**Comment by dirtyjobs** [comment]
> On 6.1.28 its working fine, if I do the update via CurseForge App the buffs don't show up. any solutions here?

thanks for the heads up on 6.1.28 working. this bug has been driving me mad for ever

**Comment by catarrer** [comment]
You are welcome my friend

**Comment by catarrer** [comment]
any updates here for newer versions?

**Comment by Burteman** [comment]
I am having the same issue, it almost renders the addon unusable when in a party, especially if your a buffing/debuffing.

**Comment by catarrer** [comment]
come on dudes... nothing here? neither a word nor a single note that you guys have noticed this bug?

**Comment by Wutname1** [comment]
It is working currently if you check Helpful, without Helpful check only buffs casted by you are counted as valid

![image](https://github.com/user-attachments/assets/cc65de38-a6a2-4f65-9e36-b710c34223c8)
