### ISSUE TITLE
[Wrath Bug Report] Customizing Unit Frames does not save/implement certain settings, or disables Unit Frames module entirely

### ISSUE THREAD

**Issue by bloodtalonx** [Wutname1/SpartanUI#490]
**Describe the bug**
After installing SpartanUI, I began making modifications to certain modules to tweak the display to what I am used to or how I like information presented. Modifying the text for the HP display would either not take certain layout/tag settings into effect until a reload, or they would wipe out my configuration changes entirely.

When I thought I had found the settings I wanted to modify and changed them for player, target, targetoftarget, focus, focustarget unit frames and performed a /reload, it caused the default unit frames to display instead of the SpartanUI unit frames. The SpartanUI unit frame module is still checked as enabled, but does not load and configuration section for unit frames has disappeared also.

**To Reproduce**

First, text alignment changes roll back whenever they are set:
1. Go to the SpartanUI Configuration panel > Unit Frames configuration > Player > Bars > Health > Texts section
2. Attempt to change the text alignment to "right". Nothing happens - the frame does not update to reflect the changes.
3. I saw a developer remark indicating that some settings require a /reload to take effect. Other addons handle this without a reload, but I tried a reload. After a reload, the configuration setting reverts to its "center" alignment. No lua error occurs (that I see), but the configuration changes are lost.
4. Similarly, the Text 2 "HP %" tag that is present but disabled was not working, so I tried adding " ([perhp]%)" to Text 1 to see if I could enable it that way. This seemed to work.
5.  I proceeded to add it to the other similar frames - target, targetoftarget, focus, focustarget - and flipped each to align right, in case any of the other frames accepted the alignment setting properly.
6.  I performed a /reload and the SpartanUI unit frames stopped loading. There was no error, and the options section for Unit Frames is no longer present.

**Screenshots**
![image](https://user-images.githubusercontent.com/102393418/213885775-2f1f9ba2-acbb-4c38-b135-219ab8b1e889.png)

**Game details:**

- Disabled Modules:

**Additional context**

**Comment by Wutname1** [comment]
Can you export your unit frames settings for me so I can see all the settings that changed/saved.
