### ISSUE TITLE
No pet name in transparent unitframes

### ISSUE THREAD

**Issue by johndolotko** [Wutname1/SpartanUI#495]
I am using the transparent skin and the name for the pet is missing as shown in the screenshot. It just displayes 3 white dots.

Pet Name Indicator Settings
![Screenshot 2023-05-11 164627](https://github.com/Wutname1/SpartanUI/assets/49884783/1f78023b-17dc-4347-a600-39ff646d39ea)

![Screenshot 2023-05-11 164420](https://github.com/Wutname1/SpartanUI/assets/49884783/422a89d2-280f-4023-882e-414910c00859)

**Comment by johndolotko** [comment]
Any news on this issue?

**Comment by johndolotko** [comment]
This issue only affects the transparant unitframes if that helps matters on getting this fixed.

**Comment by Wutname1** [comment]
Looks like a issue with competing size sliders. Next version will clean it up but I found that this size slider:
![image](https://github.com/Wutname1/SpartanUI/assets/704321/3ed50da5-c506-47f3-aedb-27d851d25ad5)
should be set to 0 It being a text element that slider is messing it up.
