### ISSUE TITLE
player frames bugged

### ISSUE THREAD

**Issue by jbulls94** [Wutname1/SpartanUI#5]
We talked on discord my frames dont work properly, ty

**Comment by Wutname1** [comment]
Let me know if the 4.4.9 Beta solves this for you

https://github.com/Wutname1/SpartanUI/wiki/How-to-download-Beta-releases

**Comment by jbulls94** [comment]
Still not staying in place when I switch character, the heal bar problem seems to be gone though

**Comment by Wutname1** [comment]
DB cleanup on BfA Build has made dragging more reliable and i cannot replicate this anymore on the BFA build. Closing for now. If after 8.0 launches the issue comes back please open a new bug or reopen this one.
