### ISSUE TITLE
Autosell only sells a small handful at a time

### ISSUE THREAD

**Issue by Doompa** [Wutname1/SpartanUI#50]
The latest update fixed autosell, but the add-on will only sell anywhere from 5-7 at a time. I have to keep reclicking the vendor to eventually empty my bags.

For example if I have 25 greys from ICC, I have to click a vendor 3-4 times to get them emptied.

**Comment by Wutname1** [comment]
This is due to a issue where the addon can sell items too fast and cause errors.

**Comment by Wutname1** [comment]
![wowscrnshot_072218_235708](https://user-images.githubusercontent.com/704321/43058042-0bfe4d3e-8e0b-11e8-9e0e-b2fa6df075fe.jpg)
