### ISSUE TITLE
[Retail Bug Report] Wago Analytics Error

### ISSUE THREAD

**Issue by Nemesis2354** [Wutname1/SpartanUI#501]
There are 3 Errors with Wago

7x ...aceSpartanUI/libs/WagoAnalyticsShim/Shim.lua:3: attempt to index local 'WagoAnalyticsShim' (a nil value)
[string "@SpartanUI/libs/WagoAnalyticsShim/Shim.lua"]:3: in main chunk

Locals:
WagoAnalyticsShim = nil
(temporary) = <function> defined @SpartanUI/libs/WagoAnalyticsShim/Shim.lua:3
(temporary) = "WagoAnalytics"
(temporary) = 2
(temporary) = "attempt to index local 'WagoAnalyticsShim' (a nil value)"

and

7x SpartanUI/libs/WagoAnalyticsShim/Shim.lua:1 (null)

and

7x FrameXML\Bindings.xml:1 Interface/AddOns/SpartanUI/libs/WagoAnalyticsShim/Shim.lua:1 (null)
[00:52]

These Errors are new with WoW V 10.1.7
I am using Spartan 6.2.22

**Comment by Wutname1** [comment]
04bbd64190ba11f471da8347fe84acb615d43372 Wago Analytics will be removed in the next release I will be pushing it out latter this week.
