### ISSUE TITLE
[Wrath Bug Report]: Minimap moved to upper left after SpartanUI uninstall. 

### ISSUE THREAD

**Issue by Ultican** [Wutname1/SpartanUI#502]
**Describe the bug**
I installed SpartanUI and ran through the setup. I played for a few mins and decided I didnt like it. I uninstalled the addon and restarted wow and everything went back to normal EXCEPT for the minimap being moved to the upper left. Im unable to move it back. 

**To Reproduce**

1. Install Spartain UI
2. Uninstall SpartanUI
3. See minimap in wrong spot

**Screenshots**

**Game details:**

- Disabled Modules:

**Additional context**

**Comment by Wutname1** [comment]
If you uninstall SUI then SUI cannot be affecting your minmap.

**Comment by Ultican** [comment]
Well, my minimap was on the right where it was always, I installed SUI and then uninstalled SUI and now it's on the left.

**Comment by Ultican** [comment]
By the way...the fix was to disable all addons and then reenable them. 
I know this because I fixed it and then reinstalled SUI and uninstalled it again and it broke even more things and a mass disable and reenable fixed it again. 
Thanks for ALL your amazing help. :-\
