### ISSUE TITLE
[Retail Bug Report] Pet battle UI does not appear for 2nd battle.

### ISSUE THREAD

**Issue by fotoman-62** [Wutname1/SpartanUI#503]
When doing pet battles, everything works fine the first time I battle. However, the second battle there will be no UI for the battle. A /reload will get everything working and it will likely be fine for many battles after that. Quite strange, I do use Rematch. Not sure who is to blame for this weird behaviour.

**Comment by Wutname1** [comment]
Are you still having this issue? I run rematch as well but cannot get it to happen. I did 4 pet battles in a row with no issues.

**Comment by fotoman-62** [comment]
Yes thank you seems fine now!
