### ISSUE TITLE
bags and menu icons missing

### ISSUE THREAD

**Issue by jack413man** [Wutname1/SpartanUI#505]
Not sure if id describe this as a bug, maybe more of something missing when using this addon. I love the addon, except one thing missing 
![Screenshot 2023-12-28 115736](https://github.com/Wutname1/SpartanUI/assets/155107228/d1efb17c-2819-4f00-bc0f-e9195dc10ca4)
Everything else is fine, except this.
Im using the latest dragonflight expansion.

**Comment by Wutname1** [comment]
Install Bartender4
