### ISSUE TITLE
[Vanilla Bug Report]

### ISSUE THREAD

**Issue by ricewzrd** [Wutname1/SpartanUI#506]
Player frame reverts to default and the party/raid/target/targettargert frames are missing altogether.

> 1x SUI_UF_pet:SetPoint(): Couldn't find region named 'SUI_UF_player'
> [string "=[C]"]: in function `SetPoint'
> [string "@Interface/AddOns/SpartanUI/modules/UnitFrames/Framework.lua"]:87: in function `PositionFrame'
> [string "@Interface/AddOns/SpartanUI/modules/UnitFrames/Framework.lua"]:151: in function <...ce/AddOns/SpartanUI/modules/UnitFrames/Framework.lua:144>
> [string "=[C]"]: ?
> [string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
> [string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
> [string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:536: in function `EnableAddon'
> [string "@Interface/AddOns/Atlas/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <...face/AddOns/Atlas/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
> 
> Locals:
> (*temporary) = SUI_UF_pet {
>  0 = <userdata>
>  __tags = <table> {
>  }
>  PLAYER_ENTERING_WORLD = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:73
>  Range = <table> {
>  }
>  DispelHighlight = Texture {
>  }
>  UNIT_PET = <table> {
>  }
>  UNIT_HEALTH_FREQUENT = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  UNIT_MAXHEALTH = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  __elements = <table> {
>  }
>  unitOnCreate = "pet"
>  raised = Frame {
>  }
>  PARTY_MEMBER_ENABLE = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  Portrait3D = PlayerModel {
>  }
>  Castbar = StatusBar {
>  }
>  UNIT_DISPLAYPOWER = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  style = "SpartanUI_UnitFrames"
>  elementList = <table> {
>  }
>  UNIT_EXITED_VEHICLE = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:73
>  UNIT_POWER_BAR_SHOW = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  UNIT_CONNECTION = <table> {
>  }
>  Debuffs = petDebuffs {
>  }
>  Portrait = PlayerModel {
>  }
>  UNIT_POWER_BAR_HIDE = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  DB = <table> {
>  }
>  UNIT_MAXPOWER = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  RaidTargetIndicator = Texture {
>  }
>  unit = "pet"
>  UNIT_POWER_FREQUENT = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  config = <table> {
>  }
>  UNIT_FACTION = <table> {
>  }
>  RAID_TARGET_UPDATE = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/elements/raidtargetindicator.lua:62
>  UNIT_AURA = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  UNIT_ENTERED_VEHICLE = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:73
>  UNIT_SPELLCAST_SENT = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/elements/castbar.lua:114
>  IsBuilt = true
>  PARTY_MEMBER_DISABLE = <function> defined @Interface/AddOns/SpartanUI/libs/oUF/ouf.lua:1082
>  Health = StatusBar {
>  }
>  unitEvents = <table> {
>  }
>  SpartanArt = Frame {
>  }
>  ThreatIndicator = Texture {
>  }
>  ElementUpdate = <function> defined @Interface/AddOns/SpartanUI/modules/UnitFrames/SpawnFrames.lua:98
>  Portrait2D = Texture {
>  }
>  Name = FontString {
>  }
>  Power = StatusBar {
>  }
>  UpdateAll = <function> defined @Interface/AddOns/SpartanUI/modules/UnitFrames/SpawnFrames.lua:48
>  Buffs = petBuffs {
>  }
>  elementDB = <table> {
>  }
>  ClassIcon = Texture {
>  }
> }
> (*temporary) = "BOTTOMRIGHT"
> (*temporary) = "SUI_UF_player"
> (*temporary) = "BOTTOMLEFT"
> (*temporary) = "20"
> (*temporary) = "0"
>

**Comment by Wutname1** [comment]
Not reproduceable, if still an issue for you please see if there are other errors.
