### ISSUE TITLE
No Unit Frames[Vanilla Bug Report]

### ISSUE THREAD

**Issue by Xaataana** [Wutname1/SpartanUI#507]
I just updated SpartanUI this morning & I have no unit frames other than the default WoW ones. I love this UI & have never had this issue until now. 
**To Reproduce**

**Screenshots**

**Game details:**
Classic Hardcore, Defias Pillager, all characters. Currently 2, Melanicia, lvl 15 Forsaken Mage & Mayhealyu, lvl 6 Troll Priest
- Disabled Modules:
![image](https://github.com/Wutname1/SpartanUI/assets/168675163/76a58a1f-c072-4473-8e35-af750cade694)
![image](https://github.com/Wutname1/SpartanUI/assets/168675163/72acc9e2-efac-4347-9b64-b45826b07569)

**Additional context**

**Comment by Xaataana** [comment]
This appears to only be affecting Classic, Cata Classic looks fine.

**Comment by Northyman** [comment]
Have the same issue in Classic SOD.
Also seems to quite a lot of LUA errors from Spartan

**Comment by Xaataana** [comment]
I'm seeing a decent number of LUA errors between Spartan & UnitScan. It seems to only be on any of the Classic servers, SOD/HC/Era. Cata Classic appears to be good.

**Comment by Wutname1** [comment]
Cata update broke it. Just pushed a update. Let me know if you see more issues and how to reproduce it as I don't play SOD.

**Comment by Northyman** [comment]
Seems to work fine again now. Thank you very much!
