### ISSUE TITLE
Taunt Watcher Problem

### ISSUE THREAD

**Issue by Nemesis2354** [Wutname1/SpartanUI#514]
**Describe the bug**

1x [ADDON_ACTION_BLOCKED] AddOn 'Bartender4' hat versucht die geschützte Funktion 'UNKNOWN()' aufzurufen.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:485: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: in function SendChatMessage'
[string "@Interface/AddOns/SpartanUI/modules/TauntWatcher.lua"]:57: in function <Interface/AddOns/SpartanUI/modules/TauntWatcher.lua:27>
[string "@Interface/AddOns/SpartanUI/modules/TauntWatcher.lua"]:132: in function ?'
[string "@Interface/AddOns/Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...er4/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...er4/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Bartender4/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

**To Reproduce**

1. Click on Taunt a Single Mob with Hand of Rekoning in solo Mode
2. See error

**Screenshots**

**Game details:** Newest Version v.10.2.7.54904

**Comment by Wutname1** [comment]
Can you provide a screenshot of your taunt settings

**Comment by Nemesis2354** [comment]
![WoWScrnShot_060224_122848](https://github.com/Wutname1/SpartanUI/assets/72879850/962dcb9c-a26e-42fc-ac42-b684ea25ac8d)
