### ISSUE TITLE
[Retail Bug Report] Unable to open ui settings

### ISSUE THREAD

**Issue by Pouchy20** [Wutname1/SpartanUI#518]
After doing the most recent update this morning, I am unable to open my ui settings by typing the following, /sui, /spartan or /spartanui. I have gone through my addons and deleted any that were causing bugs and I figured I should redo  my spartan settings in game. I am not new to SUI, havving been a user for quite a few years but this is the first time that this issue has happened. Also as you can see from the screenshots, Bartender is not showing up either. Could that be due to an issue with SUI?

![2024-08-15 (1)](https://github.com/user-attachments/assets/921671b9-06f8-47c7-8fb0-f09e2c4988f7)
![2024-08-15](https://github.com/user-attachments/assets/e1d6ca64-eb5d-4798-a786-0e293a6d1280)

**Comment by Wutname1** [comment]
Are you still having this issue with the latest updates? If you install manually by copying the files over make sure to delete the existing SUI files first.

**Comment by Pouchy20** [comment]
Thanks for the reply, after extensive searching and reworking the PC I figured out that I must've got a virus or hacked at some stage because all my addons were in a different drive and the downloads weren't syncing up with battle net. Anyway, uninstalled everything and start again from fresh. Working good now. The game just didn't feel right without Spartan UI after all these years. Keep up the good work.
