### ISSUE TITLE
Pet bar, bag bar, micro menu keep resetting position

### ISSUE THREAD

**Issue by jinkusu121** [Wutname1/SpartanUI#52]
Hello there,

I am using Spartanui with the War theme.  I decided to rearrange the Bartender bars but every time I go through a load screen or logout the three bars that anchor at the top of the HUD get their position reset.

- Pet Bar
- Micro Menu
- Bag Bar

If it could stop moving them back to the default position that would be great.
Minimizing the top red art also hides those bars.  Right now I leave them popped out and ignore them but if it is possible to disassociate them from that action that would be great too.

![wowscrnshot_072218_165609](https://user-images.githubusercontent.com/41452128/43050088-2cdf9ef2-8dd1-11e8-944c-bdaf21c54fed.jpg)

**Comment by jinkusu121** [comment]
Actually I think it does it even if I change subzone.  lol

**Comment by Whatsatotem** [comment]
looks like default UI to me, u sure it isnt a bartender doing?
