### ISSUE TITLE
[Retail Bug Report] Missing show icons in minimap "Always"

### ISSUE THREAD

**Issue by AldeanoRojo** [Wutname1/SpartanUI#523]
In the classic UI, the option to always display icons has disappeared (Now is always when "mouse over"). I use MinimapButtonButton, and without this option the icons are not displayed in the addon.

**Comment by hildekv** [comment]
The same on retail btw, i can just hover over the buttons and not have them there permanently, it's enoying

**Comment by Elfykins** [comment]
Yup, really liked this feature, I hope it wasn't intentionally removed.
