### ISSUE TITLE
[Retail Bug Report] Extra Action Buttons stacking

### ISSUE THREAD

**Issue by AlexHaible** [Wutname1/SpartanUI#525]
**Describe the bug**
If you've got extra actions from multiple sources, for example Woven Cocoon from The Weaver in Azj-Kahet, but a quest gives you one, they're stacking on top of each other, making it so you need to disable the addon to even access the buttons. 

**To Reproduce**

1. Use Classic style (Not sure if it applies to other styles, as I don't use 'em)
2. Have an area specific extra ability
3. Get another one from a quest
4. See they stack and thus one of them can't be interacted with.

**Comment by Wutname1** [comment]
I've seen people having the same issue even with the blizzard UI. Are you able to drag the first one to your bar it will go away and give you access to the second one.

**Comment by AlexHaible** [comment]
Sadly no. For some reason the zone ability added to the bar didn't make the extra button go away. I verified that I could indeed access them by disabling the addon. Using the default UI they sit next to each other, rather than being stacked.

**Comment by Wutname1** [comment]
You happen to know the quests specifically caused it? wowhead link would be amazing, I have not cleared the quests in that zone yet

**Comment by AlexHaible** [comment]
I've pacted with The Weaver for the week, giving me access to this zone ability: https://www.wowhead.com/spell=442323/woven-cocoon, then I did this quest here: https://www.wowhead.com/quest=80204/espionage-and-ventriloquism

During it, you pick up a paralytic potion that gives an extra action button, and this is the one that got placed under the zone button.
