### ISSUE TITLE
Problems in SOD Classic since Battle.net-Update today with minimap

### ISSUE THREAD

**Issue by Shaanea** [Wutname1/SpartanUI#532]
That's how the fault is described in the error handler

17x Interface/AddOns/SpartanUI/modules/Minimap.lua:40: attempt to call global 'GetMouseFocus' (a nil value)
[string "@Interface/AddOns/SpartanUI/modules/Minimap.lua"]:40: in function <Interface/AddOns/SpartanUI/modules/Minimap.lua:39>
[string "@Interface/AddOns/SpartanUI/modules/Minimap.lua"]:89: in function <Interface/AddOns/SpartanUI/modules/Minimap.lua:85>

The minimap is now shown top right side instead of below middle

Hope u can fix it
thx in advance

**Comment by Wutname1** [comment]
Fixed https://github.com/Wutname1/SpartanUI/commit/aae659861a779a0424ecc5349cb95e83bb555617 New version will be live soon.
