### ISSUE TITLE
Debuffs in party/raid frames

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#55]
did nighthold and Antorus this week (did nighthold for achievements) and i noticed this when i first got the addon years and years ago that i cant see healers debuffs (Chilled Blood on Coven of the Shivarra or Time Release on chronomatic Anomaly) 
As a healer it is SUPER important to be able to see these, but all threw legion i've had to disable SUI raid frames and turn default on just so i can see them, and i don't want to have to do that anymore

**Comment by Wutname1** [comment]
Thought on display? Should the debuffs be on the bottom of the health bar and go left to right? Should all debuffs be shown or should we try to setup a filter system?

**Comment by Whatsatotem** [comment]
i like a filter setup, i personally don't need dispellable debuffs because i have decursive, but at the same time i don't wanna see everyones exhaustion from heroism if u know what i mean

**Comment by Whatsatotem** [comment]
![buffsdebuffs](https://user-images.githubusercontent.com/41389109/43061238-10b9f4cc-8e1a-11e8-84a0-89b19c0d616a.png)

my mad paint skills! :P  i had a little trouble cropping
this is the same image you saw before when i mentioned where the player names should go, i just edited that image so you can ignore that but with the "100 namehere"

**Comment by Xatrith** [comment]
An other option would be to create an option that would let us move the portraits as a group and change the space between them. At this point it would be great to have that for the raid interface too.

**Comment by Wutname1** [comment]
Bumping this to 5.2 since it makes more sense to do this with the rest of the unit frame rebuild. 

What ever changes i make to this system now will end up being redone then anyways. If the first raid has some crazy debuff that is a tank/raid killer I will consider moving this back up on the priority list.
