### ISSUE TITLE
SUI causing Bartender Bag Bar to move on itss own

### ISSUE THREAD

**Issue by Evolution85** [Wutname1/SpartanUI#56]
SUI is causing my bag bar to move to the upper mid-right side of the screen no matter where I move it to.  If I run Bartender by itself this does not happen. Only with SUI and Bartender loaded.
![aaa](https://user-images.githubusercontent.com/41559955/43055528-0d1ca5f4-8e05-11e8-9d60-6820f27a3653.jpg)

![bbb](https://user-images.githubusercontent.com/41559955/43055531-109d0390-8e05-11e8-9851-87368d6eda45.jpg)

**Comment by Wutname1** [comment]
What style?

**Comment by Evolution85** [comment]
War

**Comment by Wutname1** [comment]
See. #52 You can enable notifications for that report.
