### ISSUE TITLE
Extra Action Button

### ISSUE THREAD

**Issue by Kruxifixion** [Wutname1/SpartanUI#57]
not sure if this is a issue with the UI or not but I've lost the extra action button sometime in the last cpl of days. Want to make sure if it's a issue then it's known or if not then I can start looking elsewhere..

**Comment by Wutname1** [comment]
What skin?

**Comment by Wutname1** [comment]
Once updated to [4.6.6](https://github.com/Wutname1/SpartanUI/releases/tag/4.6.6) reset the action bars from the /suihelp screen.

**Comment by Kruxifixion** [comment]
awesome... that fixed it... thanks and sorry I didn't reply with more info, I never saw the replies till just now
