### ISSUE TITLE
xp and reputation bar centered and a little bigger (Classic)

### ISSUE THREAD

**Issue by raineday** [Wutname1/SpartanUI#62]
This is the old layout

http://oi64.tinypic.com/119tg7m.jpg

The new version it's offset and smaller than it used to be.

http://oi68.tinypic.com/se7ic2.jpg 

*update link*

**Comment by Wutname1** [comment]
In previous 4.x build the status bar was cropped and scaled up in size. The way it is now is actually the full statusbar graphic and is not scaled up or off set from where it was originally meant to be.

**Comment by raineday** [comment]
just thought i'd point out if you the scale is at  full scale and you use the transparency effect it doesn't line up it the center image (base-center.blp) using your coding 

> _function module:SetupStatusBars()
> 	local StatusBars = SUI:GetModule('Artwork_StatusBars')
> 	StatusBars:Initalize(module.StatusBarSettings)
> 
> 	StatusBars.bars.SUI_StatusBar_Left:SetPoint('BOTTOMRIGHT', 'SUI_ActionBarPlate', 'BOTTOM', -92, -2)
> 	StatusBars.bars.SUI_StatusBar_Right:SetPoint('BOTTOMLEFT', 'SUI_ActionBarPlate', 'BOTTOM', 70, 0)
> end_

 but i took the time to figure it out it actually lines up properly with the center image (base-center.blp) using the code below.

function module:SetupStatusBars()
	local StatusBars = SUI:GetModule('Artwork_StatusBars')
	StatusBars:Initalize(module.StatusBarSettings)

	StatusBars.bars.SUI_StatusBar_Left:SetPoint('BOTTOMRIGHT', 'SUI_ActionBarPlate', 'BOTTOM', -96, 0)
	StatusBars.bars.SUI_StatusBar_Right:SetPoint('BOTTOMLEFT', 'SUI_ActionBarPlate', 'BOTTOM', 78, 0)
end

**Comment by raineday** [comment]
http://oi65.tinypic.com/xfdp9f.jpg proof it doesn't line up
