### ISSUE TITLE
Revamp Buffs/Debuffs options/customization

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#67]
/sui > Player Frames > Buffs & Debuffs > Target 
when the settings is set to icons or both Bars and Icons, doesnt matter what the "Number to Show" bar is set to, it seems to default to 8 buffs (mentioned in discord was brought up he couldnt set to 4, and mine personally was set to 10)  but remained 8 would show

**Comment by Stidnoob** [comment]
Also it'S impossible to change the settings on the target of target buffs/debuffs
