### ISSUE TITLE
New Setup Wizard Layout & Style

### ISSUE THREAD

**Issue by Wutname1** [Wutname1/SpartanUI#70]

**Comment by Wutname1** [comment]
First Progress! ![wowscrnshot_080118_024139](https://user-images.githubusercontent.com/704321/43508102-9af8453c-9534-11e8-98ee-fe445ff7bcfb.jpg)

**Comment by Khiswow** [comment]
Got this error when using the wizard on a new toon when clicking <Finish> after selecting War art style : 
Date: 2018-08-05 13:32:46
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\SpartanUI_Artwork\SpartanUI_Artwork.lua line 486:
   Usage: AceDBObject:SetProfile(name): 'name' - string expected.
Debug:
   [C]: ?
   ...rface\AddOns\Bartender4\libs\AceDB-3.0\AceDB-3.0.lua:432: SetProfile()
   ...rface\AddOns\SpartanUI_Artwork\SpartanUI_Artwork.lua:486: SetupProfile()
   ...rface\AddOns\SpartanUI_Artwork\SpartanUI_Artwork.lua:342: Next()
   SpartanUI\core\Installer.lua:226:
      SpartanUI\core\Installer.lua:224
Locals:
(*temporary) = "Usage: AceDBObject:SetProfile(name): 'name' - string expected."

AddOns:
  Swatter, v7.7.6000 (SwimmingSeadragon)
  Bartender4, v4.8.1
  Dresser, v8.0.1.180804
  SlideBar, v7.7.6000 (SwimmingSeadragon)
  SpartanUI, v4.6.7
  SpartanUIArtwork, v4.6.7
  SpartanUIFilmEffects, v4.6.7
  SpartanUIPartyFrames, v4.6.7
  SpartanUIPlayerFrames, v4.6.7
  SpartanUIRaidFrames, v4.6.7
  SpartanUISpinCam, v4.6.7
  SpartanUIStyleMinimal, v4.6.7
  SpartanUIStyleTransparent, v4.6.7
  BlizRuntimeLib_frFR v8.0.1.80000 <none>
  (ck=1b5)
