### ISSUE TITLE
War Style Raid Frames 

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#74]
![wowscrnshot_080718_124036](https://user-images.githubusercontent.com/41389109/43792953-c312eb98-9a3f-11e8-8d9a-7d0a241eaf9e.jpg)

i certainly hope this gets fixed, i cant see the left half of the frames, which is aids for a healer lol

**Comment by Whatsatotem** [comment]
should of changed specs and then took screenshot xD

**Comment by Wutname1** [comment]
> while on the topic, any way to make it so when a party/raid member is in a vehicle you can still target the player to heal them? (talkin from a High Command point of view)

In a raid no, the amount of room you need to show all those frames it would be unusable. In a party, yes, by showing the players pets (the player is the vehicle and the players character is a pet from a unit frame point of view)

**Comment by Whatsatotem** [comment]
dont need to see the vehicle, 99% of the time you cant heal them anyway, just need to be able to see the person inside the pods
