### ISSUE TITLE
lua when changing buffs/debuffs

### ISSUE THREAD

**Issue by jdennis131** [Wutname1/SpartanUI#75]
Just to verify it was not a conflict, I deleted my addons folder and installed just spartanui and bartender.

When I try to modify any of the sliders in party frames - buffs and debuffs or in raid frames - debuffs there is an lua error. Pasting below:

Message: ...SpartanUI_PartyFrames\scripts\FrameStyle_Classic.lua:577: attempt to index global 'addon' (a nil value)
Time: Tue Aug  7 18:51:19 2018
Count: 1
Stack: ...SpartanUI_PartyFrames\scripts\FrameStyle_Classic.lua:577: attempt to index global 'addon' (a nil value)
...SpartanUI_PartyFrames\scripts\FrameStyle_Classic.lua:577: in function <...SpartanUI_PartyFrames\scripts\FrameStyle_Classic.lua:575>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:818: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:639>
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:870: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:858>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...ace\AddOns\Bartender4\libs\AceGUI-3.0\AceGUI-3.0.lua:314: in function `Fire'
...der4\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:70: in function <...der4\libs\AceGUI-3.0\widgets\AceGUIWidget-Slider.lua:60>

Locals: <none>

**Comment by Wutname1** [comment]
Known issue will be addressed via #67
