### ISSUE TITLE
AceLocale issues

### ISSUE THREAD

**Issue by Eiltherune** [Wutname1/SpartanUI#76]
Since updating to version 4.6.8, I am getting 4 lua errors on login all relating to SUI and AceLocale:

<pre>Message: AceLocale-3.0: SpartanUI: Missing entry for 'GFontSet'
Debug:
   SpartanUI\core\Options.lua:492:
      SpartanUI\core\Options.lua:24</pre>

<pre>Message: AceLocale-3.0: SpartanUI: Missing entry for 'FontType'
Debug:
   SpartanUI\core\Options.lua:506:
      SpartanUI\core\Options.lua:24</pre>

<pre>Message: AceLocale-3.0: SpartanUI: Missing entry for 'FontStyle'
Debug:
   SpartanUI\core\Options.lua:517:
      SpartanUI\core\Options.lua:24</pre>

<pre>Message: AceLocale-3.0: SpartanUI: Missing entry for 'AdjFontSize'
Debug:
   SpartanUI\core\Options.lua:533:
      SpartanUI\core\Options.lua:24</pre>

Everything seems to be working properly as far as I can tell so I'm not too worried...just mildly inconvenienced by having to close an error message each time I login or reload.

**Comment by Wutname1** [comment]
fixed in 29c69155d6f7caf9ef414a26b588af562ef7ab66
