### ISSUE TITLE
Bug with SpartanUI minimap

### ISSUE THREAD

**Issue by anyanyanyx** [Wutname1/SpartanUI#8]
So I believe this is a SpartanUI problem, I use sexymap to position my minimap in a specific spot however when I enter the vehicle and exit, or open my map to fullscreen and then close it, the minimap gets very dim, resets to circular and resizes completely as if to fit the SpartanUI artwork, which I have turned off. Is there any way to disable SpartanUI minimap control?

![1](https://user-images.githubusercontent.com/30761501/41722778-58937628-7561-11e8-95e3-9c70b94a2d6a.png)

![2](https://user-images.githubusercontent.com/30761501/41722779-58bf8ec0-7561-11e8-9449-3085117e0518.png)

These are 2 images describing what I mean, first one being the way I want it to be and second one being what happens after exiting a vehicle / closing full map.

**Comment by Wutname1** [comment]
As per our discord conversation since you have the minimap module disabled this is a issue with Sexymap.
