### ISSUE TITLE
How to cancel BUFF

### ISSUE THREAD

**Issue by sao001** [Wutname1/SpartanUI#86]
How to cancel unwanted BUFF（such as spell 227723）

**Comment by Wutname1** [comment]
Right click the buff.

**Comment by sao001** [comment]
Right click the buff Unable to cancel

**Comment by sao001** [comment]
Right click the buff Unable to cancel

发送自 Windows 10 版邮件应用

发件人: wutname1
发送时间: 2018年8月23日 2:40
收件人: Wutname1/SpartanUI
抄送: sao001; Author
主题: Re: [Wutname1/SpartanUI] How to cancel BUFF (#86)

Right click the buff.
