### ISSUE TITLE
Minimap Posistion Issue when Switching to the Vehicle UI

### ISSUE THREAD

**Issue by Kaori1** [Wutname1/SpartanUI#90]
This bug has been around for me for quite some time and I've mostly been ignoring it up until now since it is mostly just a minor annoyance. 

Every time I enter the vehicle UI my minimap jumps to the top center of my screen making it quite difficult to see things. Something I've tried is moving the minimap while in the vehicle UI, however this causes the normal UI minimap position to completely change when leaving the vehicle. As such, is there a text file that I can edit to change the position SUI moves the minimap to when entering Vehicle mode? 

I've been using SUI since TBC, thank you for providing us with such an amazing UI mod.

**Comment by Lvs2Spooge** [comment]
I have the same issue.  will this be fixed?

**Comment by Kamear** [comment]
I have been using this UI for many years and I contributed a couple of times so I'm not a parasite. But this issue is so obvious. The minimap could not possibly be in a worse place in the vehicle UI. It blocks what you need to see. Come on guys, we need a way to move this thing!

**Comment by Lvs2Spooge** [comment]
as I said in my comment I am in agreement with you. 
It happened again when I entered the oculus dungeon.  
Have you tried move anything addon?  
I was thinking about trying it, but I don’t know if it would work.
