### ISSUE TITLE
Error on Login on character

### ISSUE THREAD

**Issue by Mercian** [Wutname1/SpartanUI#91]
7x ...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:203: Usage: SUI_focusFrame:SetPoint("point" [, region or nil] [, "relativePoint"] [, offsetX, offsetY])
[C]: in function `SetPoint'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:203: in function `AddMover'
...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:312: in function <...s\SpartanUI_PlayerFrames\scripts\Unit-FrameSpawn.lua:300>
[C]: ?
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:540: in function `EnableAddon'
...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...ceArcHUD3\Libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1192: in function <FrameXML\UIParent.lua:1090>

**Comment by Wutname1** [comment]
Should be fixed in SUI 5.0 (Released today), let me know if it is not.
