### ISSUE TITLE
Transparent Colors 

### ISSUE THREAD

**Issue by Whatsatotem** [Wutname1/SpartanUI#93]
![transparent](https://user-images.githubusercontent.com/41389109/45003817-110b7780-afac-11e8-886c-1294c4e56cab.png)

Suggested by: Pachari (Discord) 
have a setting that changes Player/Target colors to either match (the artwork), or make separate colors for Player/Target

**Comment by Hydrair** [comment]
Hey, this is Pachari from discord!

I looked into it and added another Color Chooser to Spartan_Style_Transparent/Style.lua by adding the following to module:SetupMenus 

`PlayerColor = {  
name = L['ArtColor'],  
				type = 'color',
				hasAlpha = true,
				order = 1,
				width = 'full',
				get = function(info)
					return unpack(SUI.DB.Styles.Transparent.Color.PlayerFrames)
				end,
				set = function(info, r, b, g, a)
					SUI.DB.Styles.Transparent.Color.PlayerFrames = {r, b, g, a}
					module:SetColor()
				end
			}`

This will let the user choose both colors for player and artwork separately. 
Also I'm not sure how to adjust the language file for translating UnitFramePlayer.
(I don't know how to put newlines in the code-part, sorry about that)

![sui](https://user-images.githubusercontent.com/20782832/45024571-a4d75500-b039-11e8-8e48-a134c381bb2f.png)

**Comment by Wutname1** [comment]
This was added back in August last year 0f02be2b24d97a9e2e60af4cfa4c8e904ce50881 and was part of 5.0 release. Closing this got missed.
