### ISSUE TITLE
I want to make my healthbars/buff/CD bigger 

### ISSUE THREAD

**Issue by Shaunay** [Wutname1/SpartanUI#96]
Hello,

Everything is in the title, i wanted to know how could i put my player frame, health bar end everything appearing at the bottom of my screen (except for my bars i know how to use bartender) bigger.

Thank you very much if you can help me.

I'm in the profil minimal, if you need any additional info or screenshot, i'll send it

If possible, I wanted to know how to make my minimap bigger too.

**Comment by Wutname1** [comment]
Unitframes are currently not siazable, it is a planned feature in SUI 5.1

You can adjust the buff icon sizes under Player frames  > Buffs & Debuffs > Player/Target
