### ISSUE TITLE
Nameplate Targetmarks

### ISSUE THREAD

**Issue by darok91** [Wutname1/SpartanUI#97]
Hello, every time i try to add Targetmarks to an enemys i don't see them on the Nameplates. When i deactivate SpartanUI everything works. And if i deactivate all other addons except SpartanUI it is still missing.. Someone a fix for that?

Greetings Darok91

![wowscrnshot_091018_180843](https://user-images.githubusercontent.com/43145906/45309839-f04f9e80-b524-11e8-87cc-08e46672bb9a.jpg)

**Comment by Wutname1** [comment]
These have been added in SUI 5.0
