### ISSUE TITLE
Minimap border still in corner

### ISSUE THREAD

**Issue by grimmcurse** [Wutname1/SpartanUI#98]
Hi
The corner of the minimap still show up in the corner : 
![image](https://user-images.githubusercontent.com/43217425/45444454-c2ef2600-b6c7-11e8-8d6f-7c474e820db1.png)

**Comment by Wutname1** [comment]
Do you have any other minimap addons?

**Comment by grimmcurse** [comment]
No ! But today I don't have this bug anymore (so after a restart of the computer, this is my only hint..)
